const vocabulary = [
  // あ
  {k:'相変わらず',r:'あいかわらず',m:'as before/usual'},
  {k:'相次いで',r:'あいついで',m:'one after the other'},
  {k:'アイデア',r:'アイデア',m:'idea'},
  {k:'あいにく',r:'あいにく',m:'unfortunately'},
  {k:'あいまい',r:'あいまい',m:'vague, unclear'},
  {k:'遭う',r:'あう',m:'encounter'},
  {k:'青白い',r:'あおじろい',m:'pale'},
  {k:'赤字',r:'あかじ',m:'deficit, loss'},
  {k:'あがる',r:'あがる',m:'get nervous'},
  {k:'飽きっぽい',r:'あきっぽい',m:'soon get tired of'},
  {k:'あきらめる',r:'あきらめる',m:'give up'},
  {k:'飽きる',r:'あきる',m:'get tired of, sick of'},
  {k:'あきれる',r:'あきれる',m:'be dumbfounded/astounded'},
  {k:'握手',r:'あくしゅ',m:'handshake'},
  {k:'あくび',r:'あくび',m:'yawn'},
  {k:'あくまで',r:'あくまで',m:'to the last, persistently'},
  {k:'明け方',r:'あけがた',m:'dawn'},
  {k:'明ける',r:'あける',m:'end, break'},
  {k:'揚げる',r:'あげる',m:'fry'},
  {k:'あこがれる',r:'あこがれる',m:'long for'},
  {k:'味付け',r:'あじつけ',m:'seasoning'},
  {k:'味わう',r:'あじわう',m:'taste'},
  {k:'預ける',r:'あずける',m:'entrust, leave with'},
  {k:'汗',r:'あせ',m:'sweat'},
  {k:'与える',r:'あたえる',m:'give'},
  {k:'あたかも',r:'あたかも',m:'as if'},
  {k:'温かみ',r:'あたたかみ',m:'warmth'},
  {k:'温まる',r:'あたたまる',m:'warm up'},
  {k:'暖まる',r:'あたたまる',m:'warm up'},
  {k:'温め直す',r:'あたためなおす',m:'reheat'},
  {k:'温める',r:'あたためる',m:'heat/warm up'},
  {k:'暖める',r:'あたためる',m:'heat/warm up'},
  {k:'厚かましい',r:'あつかましい',m:'shameless'},
  {k:'集まり',r:'あつまり',m:'gathering'},
  {k:'厚み',r:'あつみ',m:'thickness'},
  {k:'あてはまる',r:'あてはまる',m:'fit, apply to'},
  {k:'あてはめる',r:'あてはめる',m:'apply to'},
  {k:'跡',r:'あと',m:'remains, site'},
  {k:'暴れる',r:'あばれる',m:'act violently'},
  {k:'甘み',r:'あまみ',m:'sweetness'},
  {k:'編み物',r:'あみもの',m:'knitting'},
  {k:'編む',r:'あむ',m:'knit'},
  {k:'危うい',r:'あやうい',m:'in danger, dangerous'},
  {k:'怪しむ',r:'あやしむ',m:'doubt, suspect'},
  {k:'荒い',r:'あらい',m:'rough, coarse'},
  {k:'粗い',r:'あらい',m:'rough, coarse'},
  {k:'あらかじめ',r:'あらかじめ',m:'beforehand, in advance'},
  {k:'あらし',r:'あらし',m:'storm'},
  {k:'粗筋',r:'あらすじ',m:'outline'},
  {k:'改めて',r:'あらためて',m:'again'},
  {k:'改める',r:'あらためる',m:'reform, alter'},
  {k:'あらゆる',r:'あらゆる',m:'every'},
  {k:'ありがたい',r:'ありがたい',m:'appreciate, grateful'},
  {k:'ありがたさ',r:'ありがたさ',m:'blessing'},
  {k:'あれこれ',r:'あれこれ',m:'this and that'},
  {k:'荒れる',r:'あれる',m:'get rough'},
  {k:'慌ただしい',r:'あわただしい',m:'busy'},
  {k:'慌てる',r:'あわてる',m:'panic, get flustered'},
  {k:'哀れ',r:'あわれ',m:'pitiful'},
  {k:'案',r:'あん',m:'proposal, idea'},
  {k:'安易',r:'あんい',m:'easy'},
  {k:'案外',r:'あんがい',m:'unexpectedly'},
  {k:'暗記',r:'あんき',m:'learning by heart'},
  {k:'安全性',r:'あんぜんせい',m:'safety'},
  {k:'案の定',r:'あんのじょう',m:'as expected'},
  // い
  {k:'言い合う',r:'いいあう',m:'argue, have an exchange'},
  {k:'言い出す',r:'いいだす',m:'bring up a subject'},
  {k:'言いつける',r:'いいつける',m:'tell'},
  {k:'言い張る',r:'いいはる',m:'insist on, stick to one\'s point'},
  {k:'意外',r:'いがい',m:'unexpected'},
  {k:'生かす',r:'いかす',m:'make good use of'},
  {k:'生き生き',r:'いきいき',m:'lively'},
  {k:'いきなり',r:'いきなり',m:'suddenly'},
  {k:'意義深い',r:'いぎぶかい',m:'significant'},
  {k:'幾分',r:'いくぶん',m:'somewhat'},
  {k:'意識',r:'いしき',m:'consciousness'},
  {k:'いずれ',r:'いずれ',m:'some day'},
  {k:'依然',r:'いぜん',m:'still'},
  {k:'以前',r:'いぜん',m:'before'},
  {k:'偉大',r:'いだい',m:'great'},
  {k:'抱く',r:'いだく',m:'have, cherish'},
  {k:'痛み',r:'いたみ',m:'pain, ache'},
  {k:'痛み出す',r:'いたみだす',m:'start to hurt'},
  {k:'痛む',r:'いたむ',m:'ache'},
  {k:'位置',r:'いち',m:'location, position'},
  {k:'一応',r:'いちおう',m:'just in case, at any rate'},
  {k:'一段と',r:'いちだんと',m:'even more'},
  {k:'一面',r:'いちめん',m:'front page'},
  {k:'一家',r:'いっか',m:'whole family'},
  {k:'一切',r:'いっさい',m:'absolutely (not)'},
  {k:'一瞬',r:'いっしゅん',m:'an instant'},
  {k:'一斉に',r:'いっせいに',m:'all together'},
  {k:'一層',r:'いっそう',m:'much more'},
  {k:'いったん',r:'いったん',m:'temporarily, once'},
  {k:'一致',r:'いっち',m:'agreement, consistency'},
  {k:'一定',r:'いってい',m:'fixed, constant'},
  {k:'いつのまに',r:'いつのまに',m:'before you know it, without even noticing'},
  {k:'いつまでも',r:'いつまでも',m:'forever'},
  {k:'移転',r:'いてん',m:'transfer'},
  {k:'遺伝',r:'いでん',m:'inheritance'},
  {k:'遺伝子',r:'いでんし',m:'gene'},
  {k:'稲',r:'いね',m:'rice plant'},
  {k:'祈る',r:'いのる',m:'pray'},
  {k:'威張る',r:'いばる',m:'put on airs'},
  {k:'違反',r:'いはん',m:'violation'},
  {k:'衣服',r:'いふく',m:'clothes'},
  {k:'今更',r:'いまさら',m:'(too late) now'},
  {k:'未だに',r:'いまだに',m:'yet, even now'},
  {k:'今に',r:'いまに',m:'sooner or later, in time'},
  {k:'今にも',r:'いまにも',m:'at any moment'},
  {k:'今や',r:'いまや',m:'now (in contrast with the past)'},
  {k:'嫌がる',r:'いやがる',m:'hate'},
  {k:'いよいよ',r:'いよいよ',m:'finally'},
  {k:'依頼',r:'いらい',m:'request, commission'},
  {k:'以来',r:'いらい',m:'since'},
  {k:'いらいら',r:'いらいら',m:'irritation'},
  {k:'いる',r:'いる',m:'roast'},
  {k:'引用',r:'いんよう',m:'citation, quotation'},
  // う
  {k:'ウイルス',r:'ウイルス',m:'virus'},
  {k:'植える',r:'うえる',m:'plant'},
  {k:'受け入れる',r:'うけいれる',m:'accept'},
  {k:'受け継ぐ',r:'うけつぐ',m:'inherit'},
  {k:'受け取る',r:'うけとる',m:'receive'},
  {k:'受け持つ',r:'うけもつ',m:'be in charge of'},
  {k:'失う',r:'うしなう',m:'lose'},
  {k:'薄暗い',r:'うすぐらい',m:'dim'},
  {k:'薄まる',r:'うすまる',m:'become diluted'},
  {k:'薄める',r:'うすめる',m:'dilute'},
  {k:'疑う',r:'うたがう',m:'doubt'},
  {k:'打ち合わせ',r:'うちあわせ',m:'meeting'},
  {k:'打ち合わせる',r:'うちあわせる',m:'have a meeting'},
  {k:'内気',r:'うちき',m:'shy'},
  {k:'打ち消す',r:'うちけす',m:'deny, contradict'},
  {k:'うっかり',r:'うっかり',m:'carelessly'},
  {k:'訴えかける',r:'うったえかける',m:'appeal'},
  {k:'訴える',r:'うったえる',m:'take legal action, appeal, complain'},
  {k:'腕が上がる',r:'うでがあがる',m:'become more skillful'},
  {k:'腕がいい',r:'うでがいい',m:'be skilled'},
  {k:'腕を上げる',r:'うでをあげる',m:'improve one\'s skill'},
  {k:'奪う',r:'うばう',m:'steal'},
  {k:'うまみ',r:'うまみ',m:'taste'},
  {k:'生まれる',r:'うまれる',m:'be born'},
  {k:'生み出す',r:'うみだす',m:'produce, create'},
  {k:'埋める',r:'うめる',m:'bury, fill in'},
  {k:'敬う',r:'うやまう',m:'respect'},
  {k:'裏',r:'うら',m:'back, reverse side'},
  {k:'裏返す',r:'うらがえす',m:'turn over, reverse'},
  {k:'裏切る',r:'うらぎる',m:'betray'},
  {k:'恨む',r:'うらむ',m:'hold a grudge'},
  {k:'うらやましい',r:'うらやましい',m:'envious'},
  {k:'うらやむ',r:'うらやむ',m:'envy'},
  {k:'うんと',r:'うんと',m:'really, very'},
  // え
  {k:'永遠',r:'えいえん',m:'eternity'},
  {k:'影響',r:'えいきょう',m:'influence'},
  {k:'衛生的',r:'えいせいてき',m:'hygienic, sanitary'},
  {k:'映像',r:'えいぞう',m:'image, picture'},
  {k:'栄養',r:'えいよう',m:'nutrition'},
  {k:'えさ',r:'えさ',m:'feed, food'},
  {k:'エチケット',r:'エチケット',m:'etiquette'},
  {k:'宴会',r:'えんかい',m:'party'},
  {k:'演技',r:'えんぎ',m:'acting'},
  {k:'演劇',r:'えんげき',m:'play'},
  {k:'演習',r:'えんしゅう',m:'practice'},
  {k:'援助',r:'えんじょ',m:'aid, assistance'},
  {k:'演説',r:'えんぜつ',m:'speech, address'},
  {k:'演奏',r:'えんそう',m:'performance'},
  // お
  {k:'追いかける',r:'おいかける',m:'chase'},
  {k:'追い越す',r:'おいこす',m:'overtake'},
  {k:'追い出す',r:'おいだす',m:'chase away, throw out'},
  {k:'追い付く',r:'おいつく',m:'overtake'},
  {k:'応援',r:'おうえん',m:'support, cheering for'},
  {k:'横断',r:'おうだん',m:'crossing'},
  {k:'往復',r:'おうふく',m:'both ways, round trip'},
  {k:'大雨洪水警報',r:'おおあめこうずいけいほう',m:'heavy rain and flood warning'},
  {k:'大いに',r:'おおいに',m:'hugely, very much'},
  {k:'大げさ',r:'おおげさ',m:'exaggerated'},
  {k:'大通り',r:'おおどおり',m:'main street'},
  {k:'大幅',r:'おおはば',m:'major, drastic'},
  {k:'大まか',r:'おおまか',m:'rough'},
  {k:'丘',r:'おか',m:'hill'},
  {k:'犯す',r:'おかす',m:'commit'},
  {k:'補う',r:'おぎなう',m:'make up for'},
  {k:'怒り出す',r:'おこりだす',m:'lose one\'s temper'},
  {k:'押さえる',r:'おさえる',m:'hold down, restrain'},
  {k:'抑える',r:'おさえる',m:'keep under control, suppress'},
  {k:'納める',r:'おさめる',m:'pay'},
  {k:'惜しむ',r:'おしむ',m:'regret, begrudge'},
  {k:'汚染',r:'おせん',m:'pollution'},
  {k:'襲う',r:'おそう',m:'attack'},
  {k:'恐らく',r:'おそらく',m:'perhaps'},
  {k:'恐れる',r:'おそれる',m:'fear'},
  {k:'恐ろしい',r:'おそろしい',m:'terrible'},
  {k:'穏やか',r:'おだやか',m:'calm, mild'},
  {k:'落ち込む',r:'おちこむ',m:'be depressed'},
  {k:'おっとり',r:'おっとり',m:'gentle, easy-going'},
  {k:'おどおど',r:'おどおど',m:'anxiously'},
  {k:'驚く',r:'おどろく',m:'be surprised'},
  {k:'思いがけない',r:'おもいがけない',m:'unexpected'},
  {k:'思い切って',r:'おもいきって',m:'daringly'},
  {k:'思い切り',r:'おもいきり',m:'to one\'s heart\'s content'},
  {k:'思い込む',r:'おもいこむ',m:'be under the impression'},
  {k:'思いつく',r:'おもいつく',m:'hit upon, come up with'},
  {k:'思いのほか',r:'おもいのほか',m:'unexpectedly'},
  {k:'面白み',r:'おもしろみ',m:'fun'},
  {k:'主に',r:'おもに',m:'mainly'},
  {k:'重み',r:'おもみ',m:'dignity, weight'},
  {k:'思わず',r:'おもわず',m:'accidentally, automatically'},
  {k:'及ぶ',r:'およぶ',m:'reach, extend'},
  {k:'及ぼす',r:'およぼす',m:'exert, cause'},
  {k:'恩',r:'おん',m:'obligation, debt of gratitude'},
  {k:'音声',r:'おんせい',m:'sound'},
  {k:'温暖',r:'おんだん',m:'warm'},
  {k:'温暖化',r:'おんだんか',m:'global warming'},
  // か
  {k:'顔が広い',r:'かおがひろい',m:'know a lot of people'},
  {k:'顔つき',r:'かおつき',m:'looks, facial expression'},
  {k:'香り',r:'かおり',m:'fragrance'},
  {k:'顔を貸す',r:'かおをかす',m:'join, come along'},
  {k:'顔を出す',r:'かおをだす',m:'make an appearance'},
  {k:'価格',r:'かかく',m:'price'},
  {k:'化学',r:'かがく',m:'chemistry'},
  {k:'科学',r:'かがく',m:'science'},
  {k:'科学者',r:'かがくしゃ',m:'scientist'},
  {k:'科学的',r:'かがくてき',m:'scientific'},
  {k:'かかる',r:'かかる',m:'get, catch'},
  {k:'書き上がる',r:'かきあがる',m:'finish writing'},
  {k:'書き直す',r:'かきなおす',m:'rewrite'},
  {k:'かく',r:'かく',m:'to (sweat, snore, etc.)'},
  {k:'かぐ',r:'かぐ',m:'smell'},
  {k:'家具',r:'かぐ',m:'furniture'},
  {k:'隠す',r:'かくす',m:'hide'},
  {k:'確保',r:'かくほ',m:'securement'},
  {k:'革命',r:'かくめい',m:'revolution'},
  {k:'影',r:'かげ',m:'reflection, shadow'},
  {k:'陰',r:'かげ',m:'behind'},
  {k:'掛け算',r:'かけざん',m:'multiplication'},
  {k:'掛ける',r:'かける',m:'multiply, times'},
  {k:'過去',r:'かこ',m:'past'},
  {k:'家事',r:'かじ',m:'housework'},
  {k:'果実',r:'かじつ',m:'fruit'},
  {k:'かじる',r:'かじる',m:'take a bite out of'},
  {k:'稼ぐ',r:'かせぐ',m:'earn'},
  {k:'河川',r:'かせん',m:'river'},
  {k:'型',r:'かた',m:'mold, model, form'},
  {k:'課題',r:'かだい',m:'task, challenge'},
  {k:'形',r:'かたち',m:'shape, style'},
  {k:'固まる',r:'かたまる',m:'harden, solidify'},
  {k:'片道',r:'かたみち',m:'one way'},
  {k:'傾く',r:'かたむく',m:'lean, decline'},
  {k:'固める',r:'かためる',m:'harden, stiffen'},
  {k:'肩を落とす',r:'かたをおとす',m:'be disappointed/let down'},
  {k:'肩を貸す',r:'かたをかす',m:'lend somebody one\'s shoulder (to lean on)'},
  {k:'担ぐ',r:'かつぐ',m:'carry on one\'s shoulder'},
  {k:'勝手',r:'かって',m:'do as one pleases, selfish'},
  {k:'かつて',r:'かつて',m:'once, before'},
  {k:'活発',r:'かっぱつ',m:'lively'},
  {k:'活躍',r:'かつやく',m:'active part, success'},
  {k:'悲しみ',r:'かなしみ',m:'sadness'},
  {k:'悲しむ',r:'かなしむ',m:'feel sad, feel sorry for'},
  {k:'必ずしも',r:'かならずしも',m:'not always/necessarily'},
  {k:'加熱',r:'かねつ',m:'heating'},
  {k:'金遣い',r:'かねづかい',m:'spending money'},
  {k:'かび',r:'かび',m:'mold'},
  {k:'株',r:'かぶ',m:'stock'},
  {k:'株式',r:'かぶしき',m:'company stock'},
  {k:'花粉',r:'かふん',m:'pollen'},
  {k:'構う',r:'かまう',m:'take care of'},
  {k:'神',r:'かみ',m:'god'},
  {k:'かみそり',r:'かみそり',m:'razor'},
  {k:'科目',r:'かもく',m:'subject'},
  {k:'かゆみ',r:'かゆみ',m:'itch'},
  {k:'柄',r:'がら',m:'pattern'},
  {k:'体つき',r:'からだつき',m:'build'},
  {k:'辛み',r:'からみ',m:'hot flavor'},
  {k:'刈る',r:'かる',m:'cut, harvest'},
  {k:'乾かす',r:'かわかす',m:'dry'},
  {k:'勘',r:'かん',m:'intuition'},
  {k:'考え直す',r:'かんがえなおす',m:'rethink, reconsider'},
  {k:'間隔',r:'かんかく',m:'space, interval'},
  {k:'観客',r:'かんきゃく',m:'audience, spectator'},
  {k:'看護師',r:'かんごし',m:'nurse'},
  {k:'患者',r:'かんじゃ',m:'patient'},
  {k:'勘定',r:'かんじょう',m:'calculation, counting'},
  {k:'感染',r:'かんせん',m:'infection'},
  {k:'監督',r:'かんとく',m:'coach'},
  {k:'看病',r:'かんびょう',m:'nurse'},
  {k:'管理',r:'かんり',m:'management, care'},
  // き
  {k:'気が合う',r:'きがあう',m:'get along well with'},
  {k:'危害',r:'きがい',m:'harm'},
  {k:'気が重い',r:'きがおもい',m:'feel depressed'},
  {k:'気が利く',r:'きがきく',m:'smart'},
  {k:'気が進まない',r:'きがすすまない',m:'be not in the mood for'},
  {k:'気が済む',r:'きがすむ',m:'be satisfied, feel fine'},
  {k:'気が小さい',r:'きがちいさい',m:'timid'},
  {k:'気が散る',r:'きがちる',m:'get distracted'},
  {k:'気が早い',r:'きがはやい',m:'hasty'},
  {k:'気が短い',r:'きがみじかい',m:'short-tempered'},
  {k:'気が向く',r:'きがむく',m:'feel like'},
  {k:'気軽',r:'きがる',m:'casual, light-hearted'},
  {k:'機嫌',r:'きげん',m:'mood'},
  {k:'危険性',r:'きけんせい',m:'dangerousness'},
  {k:'気候',r:'きこう',m:'climate'},
  {k:'気候変動',r:'きこうへんどう',m:'climate change'},
  {k:'既婚者',r:'きこんしゃ',m:'married person'},
  {k:'刻む',r:'きざむ',m:'chop'},
  {k:'岸',r:'きし',m:'coast'},
  {k:'記事',r:'きじ',m:'article'},
  {k:'記者',r:'きしゃ',m:'journalist, reporter'},
  {k:'築く',r:'きずく',m:'build'},
  {k:'着せる',r:'きせる',m:'dress'},
  {k:'貴族',r:'きぞく',m:'aristocracy'},
  {k:'規則正しい',r:'きそくただしい',m:'regular'},
  {k:'貴重',r:'きちょう',m:'valuable'},
  {k:'気遣い',r:'きづかい',m:'concern'},
  {k:'きっかけ',r:'きっかけ',m:'opportunity'},
  {k:'ぎっしり',r:'ぎっしり',m:'tightly'},
  {k:'きっぱり',r:'きっぱり',m:'flatly, decisively'},
  {k:'起動',r:'きどう',m:'start-up, activation'},
  {k:'気に入る',r:'きにいる',m:'like'},
  {k:'気に掛かる',r:'きにかかる',m:'be concerned about'},
  {k:'気に食わない',r:'きにくわない',m:'dislike'},
  {k:'気にする',r:'きにする',m:'be concerned about'},
  {k:'規模',r:'きぼ',m:'scale'},
  {k:'希望',r:'きぼう',m:'hope, wish'},
  {k:'気まぐれ',r:'きまぐれ',m:'whimsy'},
  {k:'気まずい',r:'きまずい',m:'awkward'},
  {k:'決まって',r:'きまって',m:'always, without fail'},
  {k:'逆',r:'ぎゃく',m:'reverse/opposite/inverse'},
  {k:'球',r:'きゅう',m:'sphere'},
  {k:'休暇',r:'きゅうか',m:'holiday'},
  {k:'急カーブ',r:'きゅうカーブ',m:'sharp curve'},
  {k:'救済',r:'きゅうさい',m:'help, relief'},
  {k:'急上昇',r:'きゅうじょうしょう',m:'sudden rise'},
  {k:'旧市街',r:'きゅうしがい',m:'old town'},
  {k:'旧姓',r:'きゅうせい',m:'maiden name'},
  {k:'急接近',r:'きゅうせっきん',m:'rapid approach'},
  {k:'休息',r:'きゅうそく',m:'rest'},
  {k:'急展開',r:'きゅうてんかい',m:'rapid development'},
  {k:'急テンポ',r:'きゅうテンポ',m:'quick tempo'},
  {k:'急ブレーキ',r:'きゅうブレーキ',m:'sudden breaking'},
  {k:'休養',r:'きゅうよう',m:'rest, recreation'},
  {k:'給料',r:'きゅうりょう',m:'salary'},
  {k:'器用',r:'きよう',m:'dexterity, skillfulness'},
  {k:'教育実習',r:'きょういくじっしゅう',m:'teaching practice'},
  {k:'教員',r:'きょういん',m:'teaching staff'},
  {k:'強化',r:'きょうか',m:'strengthening'},
  {k:'教科書',r:'きょうかしょ',m:'textbook'},
  {k:'競技',r:'きょうぎ',m:'competition'},
  {k:'供給',r:'きょうきゅう',m:'supply'},
  {k:'教師',r:'きょうし',m:'teacher'},
  {k:'業績',r:'ぎょうせき',m:'accomplishment'},
  {k:'興味深い',r:'きょうみぶかい',m:'interesting'},
  {k:'行列',r:'ぎょうれつ',m:'line, queue'},
  {k:'許可証',r:'きょかしょう',m:'license, permit'},
  {k:'曲',r:'きょく',m:'number, piece of music'},
  {k:'距離',r:'きょり',m:'distance'},
  {k:'嫌う',r:'きらう',m:'hate'},
  {k:'気楽',r:'きらく',m:'carefree'},
  {k:'霧',r:'きり',m:'fog'},
  {k:'議論',r:'ぎろん',m:'discussion'},
  {k:'極めて',r:'きわめて',m:'extremely'},
  {k:'気を落とす',r:'きをおとす',m:'be discouraged'},
  {k:'気を遣う',r:'きをつかう',m:'take care of, be considerate'},
  {k:'気を取られる',r:'きをとられる',m:'be distracted'},
  {k:'菌',r:'きん',m:'fungus'},
  {k:'金額',r:'きんがく',m:'amount of money'},
  {k:'銀行口座',r:'ぎんこうこうざ',m:'bank account'},
  {k:'緊張',r:'きんちょう',m:'strain, tension'},
  {k:'金融界',r:'きんゆうかい',m:'financial world'},
  {k:'金融危機',r:'きんゆうきき',m:'financial crisis'},
  // く
  {k:'食う',r:'くう',m:'eat'},
  {k:'空間',r:'くうかん',m:'space'},
  {k:'偶然',r:'ぐうぜん',m:'by accident, by chance'},
  {k:'茎',r:'くき',m:'stalk'},
  {k:'腐る',r:'くさる',m:'go bad/off, rot'},
  {k:'くし',r:'くし',m:'comb'},
  {k:'くしゃみ',r:'くしゃみ',m:'sneeze'},
  {k:'苦情',r:'くじょう',m:'complaint'},
  {k:'崩す',r:'くずす',m:'break, demolish'},
  {k:'具体的',r:'ぐたいてき',m:'concrete'},
  {k:'くたくた',r:'くたくた',m:'exhausted'},
  {k:'くたびれる',r:'くたびれる',m:'be exhausted'},
  {k:'くだらない',r:'くだらない',m:'stupid, trashy'},
  {k:'口がうまい',r:'くちがうまい',m:'smooth talker'},
  {k:'口が重い',r:'くちがおもい',m:'taciturn'},
  {k:'口が堅い',r:'くちがかたい',m:'tight-lipped'},
  {k:'口が軽い',r:'くちがかるい',m:'be a blabbermouth'},
  {k:'口が滑る',r:'くちがすべる',m:'make a slip of the tongue'},
  {k:'口に合う',r:'くちにあう',m:'suit someone\'s taste'},
  {k:'口にする',r:'くちにする',m:'talk'},
  {k:'口に出す',r:'くちにだす',m:'say'},
  {k:'ぐちゃぐちゃ',r:'ぐちゃぐちゃ',m:'messy'},
  {k:'口を出す',r:'くちをだす',m:'have one\'s say, interfere'},
  {k:'苦痛',r:'くつう',m:'pain'},
  {k:'くっきり',r:'くっきり',m:'clearly'},
  {k:'ぐったり',r:'ぐったり',m:'dead-tired'},
  {k:'ぐっと',r:'ぐっと',m:'much'},
  {k:'くつろぐ',r:'くつろぐ',m:'relax'},
  {k:'くどい',r:'くどい',m:'long-winded, greasy, gaudy'},
  {k:'首にする',r:'くびにする',m:'fire from a job'},
  {k:'首になる',r:'くびになる',m:'be fired'},
  {k:'組み合わせる',r:'くみあわせる',m:'combine'},
  {k:'組み込む',r:'くみこむ',m:'integrate'},
  {k:'組み立てる',r:'くみたてる',m:'assemble, put together'},
  {k:'悔やむ',r:'くやむ',m:'regret'},
  {k:'くよくよ',r:'くよくよ',m:'brooding over'},
  {k:'暮らしぶり',r:'くらしぶり',m:'way of life'},
  {k:'狂う',r:'くるう',m:'go crazy/mad'},
  {k:'苦しみ',r:'くるしみ',m:'suffering'},
  {k:'苦しむ',r:'くるしむ',m:'suffer'},
  {k:'くるむ',r:'くるむ',m:'wrap'},
  {k:'クレーム',r:'クレーム',m:'claim'},
  {k:'暮れる',r:'くれる',m:'get dark'},
  {k:'黒字',r:'くろじ',m:'surplus'},
  {k:'加える',r:'くわえる',m:'do (harm) to, inflict on'},
  {k:'詳しい',r:'くわしい',m:'detailed'},
  {k:'加わる',r:'くわわる',m:'join, participate'},
  {k:'訓練',r:'くんれん',m:'training'},
  // け
  {k:'敬意',r:'けいい',m:'respect'},
  {k:'経営',r:'けいえい',m:'management'},
  {k:'経過',r:'けいか',m:'passage'},
  {k:'警戒',r:'けいかい',m:'warning, caution'},
  {k:'景気',r:'けいき',m:'business climate/conditions'},
  {k:'契機',r:'けいき',m:'opportunity'},
  {k:'軽減',r:'けいげん',m:'reduction'},
  {k:'敬語',r:'けいご',m:'honorific expression'},
  {k:'経済危機',r:'けいざいきき',m:'economic crisis'},
  {k:'計算',r:'けいさん',m:'calculation'},
  {k:'携帯電話',r:'けいたいでんわ',m:'mobile phone'},
  {k:'芸能界',r:'げいのうかい',m:'show business'},
  {k:'削る',r:'けずる',m:'plane, shave, sharpen'},
  {k:'けち',r:'けち',m:'stingy'},
  {k:'血圧',r:'けつあつ',m:'blood pressure'},
  {k:'月給',r:'げっきゅう',m:'monthly salary'},
  {k:'結局',r:'けっきょく',m:'finally'},
  {k:'結構',r:'けっこう',m:'quite'},
  {k:'結婚相手',r:'けっこんあいて',m:'marriage partner'},
  {k:'傑作',r:'けっさく',m:'masterpiece'},
  {k:'決して',r:'けっして',m:'by no means, never'},
  {k:'険しい',r:'けわしい',m:'steep, severe'},
  {k:'謙虚',r:'けんきょ',m:'modest'},
  {k:'現金',r:'げんきん',m:'cash'},
  {k:'検索',r:'けんさく',m:'search'},
  {k:'減少',r:'げんしょう',m:'decrease'},
  {k:'現状',r:'げんじょう',m:'present state'},
  {k:'研修',r:'けんしゅう',m:'training'},
  {k:'現代語',r:'げんだいご',m:'modern language'},
  {k:'現代風',r:'げんだいふう',m:'contemporary'},
  {k:'建築家',r:'けんちくか',m:'architect'},
  {k:'憲法',r:'けんぽう',m:'constitution'},
  {k:'権力',r:'けんりょく',m:'power, authority'},
  // こ
  {k:'合意',r:'ごうい',m:'agreement'},
  {k:'強引',r:'ごういん',m:'aggressive, forceful'},
  {k:'豪華',r:'ごうか',m:'gorgeous'},
  {k:'後悔',r:'こうかい',m:'regret'},
  {k:'公害',r:'こうがい',m:'pollution'},
  {k:'交換',r:'こうかん',m:'exchange'},
  {k:'好奇心',r:'こうきしん',m:'curiosity'},
  {k:'航空券',r:'こうくうけん',m:'air ticket'},
  {k:'工芸',r:'こうげい',m:'crafts'},
  {k:'高血圧',r:'こうけつあつ',m:'high blood pressure'},
  {k:'貢献',r:'こうけん',m:'contribution'},
  {k:'広告',r:'こうこく',m:'advertising'},
  {k:'交際',r:'こうさい',m:'association'},
  {k:'交渉',r:'こうしょう',m:'negotiation'},
  {k:'向上',r:'こうじょう',m:'improvement'},
  {k:'高速バス',r:'こうそくバス',m:'express bus'},
  {k:'交通機関',r:'こうつうきかん',m:'means of transportation'},
  {k:'交通事故',r:'こうつうじこ',m:'traffic accident'},
  {k:'高度',r:'こうど',m:'advanced'},
  {k:'強盗',r:'ごうとう',m:'robber'},
  {k:'強盗事件',r:'ごうとうじけん',m:'robbery'},
  {k:'効率',r:'こうりつ',m:'efficiency'},
  {k:'高齢化',r:'こうれいか',m:'aging (of the population)'},
  {k:'超える',r:'こえる',m:'exceed'},
  {k:'誤解',r:'ごかい',m:'misunderstanding'},
  {k:'国語',r:'こくご',m:'national language'},
  {k:'国際連合',r:'こくさいれんごう',m:'United Nations'},
  {k:'国連',r:'こくれん',m:'UN'},
  {k:'心が狭い',r:'こころがせまい',m:'be narrow-minded'},
  {k:'心が広い',r:'こころがひろい',m:'be big-hearted'},
  {k:'心を痛める',r:'こころをいためる',m:'be pained'},
  {k:'心を込める',r:'こころをこめる',m:'do whole-heartedly'},
  {k:'腰掛ける',r:'こしかける',m:'sit'},
  {k:'こしょう',r:'こしょう',m:'pepper'},
  {k:'個人競技',r:'こじんきょうぎ',m:'individual sports'},
  {k:'個人旅行',r:'こじんりょこう',m:'individual travel'},
  {k:'コスト',r:'コスト',m:'cost'},
  {k:'国家',r:'こっか',m:'country, nation'},
  {k:'国会',r:'こっかい',m:'national assembly, the Diet'},
  {k:'こつこつ',r:'こつこつ',m:'steadily'},
  {k:'骨折',r:'こっせつ',m:'bone fracture'},
  {k:'古典',r:'こてん',m:'classic'},
  {k:'古典的',r:'こてんてき',m:'classical'},
  {k:'言葉遣い',r:'ことばづかい',m:'wording, phrasing'},
  {k:'好み',r:'このみ',m:'liking, taste'},
  {k:'こぼす',r:'こぼす',m:'spill'},
  {k:'こぼれる',r:'こぼれる',m:'overflow'},
  {k:'コマーシャル',r:'コマーシャル',m:'commercial'},
  {k:'娯楽',r:'ごらく',m:'amusement, entertainment'},
  {k:'娯楽番組',r:'ごらくばんぐみ',m:'entertainment program'},
  {k:'殺し合う',r:'ころしあう',m:'kill each other'},
  {k:'殺す',r:'ころす',m:'kill'},
  {k:'今学期',r:'こんがっき',m:'this term'},
  {k:'今後',r:'こんご',m:'from now on'},
  {k:'混雑',r:'こんざつ',m:'congestion'},
  {k:'今世紀',r:'こんせいき',m:'this century'},
  {k:'献立',r:'こんだて',m:'menu'},
  {k:'昆虫',r:'こんちゅう',m:'insect'},
  {k:'今年度',r:'こんねんど',m:'this fiscal year'},
  {k:'婚約',r:'こんやく',m:'engagement'},
  {k:'混乱',r:'こんらん',m:'confusion'},
  // さ
  {k:'災害',r:'さいがい',m:'disaster'},
  {k:'細菌',r:'さいきん',m:'bacteria'},
  {k:'最高気温',r:'さいこうきおん',m:'highest temperature'},
  {k:'再三',r:'さいさん',m:'again and again'},
  {k:'財政的',r:'ざいせいてき',m:'financial'},
  {k:'最前列',r:'さいぜんれつ',m:'front row'},
  {k:'最大',r:'さいだい',m:'biggest'},
  {k:'最低気温',r:'さいていきおん',m:'lowest temperature'},
  {k:'採点',r:'さいてん',m:'scoring'},
  {k:'才能',r:'さいのう',m:'ability'},
  {k:'栽培',r:'さいばい',m:'cultivation'},
  {k:'裁判',r:'さいばん',m:'trial'},
  {k:'裁縫',r:'さいほう',m:'sewing'},
  {k:'再放送',r:'さいほうそう',m:'rebroadcast, repeat'},
  {k:'栄える',r:'さかえる',m:'flourish'},
  {k:'探し回る',r:'さがしまわる',m:'look around'},
  {k:'逆らう',r:'さからう',m:'defy, go against'},
  {k:'詐欺',r:'さぎ',m:'fraud'},
  {k:'索引',r:'さくいん',m:'index'},
  {k:'削減',r:'さくげん',m:'reduction'},
  {k:'削除',r:'さくじょ',m:'deletion'},
  {k:'作成',r:'さくせい',m:'making'},
  {k:'作物',r:'さくもつ',m:'crop'},
  {k:'避ける',r:'さける',m:'avoid'},
  {k:'差し押さえる',r:'さしおさえる',m:'seize'},
  {k:'差しかかる',r:'さしかかる',m:'approach'},
  {k:'差し出す',r:'さしだす',m:'hold out'},
  {k:'差し支えない',r:'さしつかえない',m:'having no objection'},
  {k:'差し引く',r:'さしひく',m:'deduct'},
  {k:'刺身',r:'さしみ',m:'sashimi'},
  {k:'撮影',r:'さつえい',m:'filming'},
  {k:'作家',r:'さっか',m:'writer'},
  {k:'さっさと',r:'さっさと',m:'quickly'},
  {k:'殺人事件',r:'さつじんじけん',m:'murder case'},
  {k:'早速',r:'さっそく',m:'immediately'},
  {k:'ざっと',r:'ざっと',m:'roughly'},
  {k:'さっぱり',r:'さっぱり',m:'refreshing, completely'},
  {k:'砂漠',r:'さばく',m:'desert'},
  {k:'砂漠化',r:'さばくか',m:'desertification'},
  {k:'寂しさ',r:'さびしさ',m:'sadness, loneliness'},
  {k:'作法',r:'さほう',m:'manners'},
  {k:'サポート',r:'サポート',m:'support'},
  {k:'サボる',r:'サボる',m:'skip'},
  {k:'さます',r:'さます',m:'get sober, wake up'},
  {k:'冷める',r:'さめる',m:'cool'},
  {k:'さめる',r:'さめる',m:'become sober'},
  {k:'更に',r:'さらに',m:'further'},
  {k:'騒がしい',r:'さわがしい',m:'noisy'},
  {k:'参考書',r:'さんこうしょ',m:'reference book'},
  {k:'参考文献',r:'さんこうぶんけん',m:'reference literature'},
  // し
  {k:'仕上がる',r:'しあがる',m:'be finished'},
  {k:'飼育',r:'しいく',m:'breeding'},
  {k:'強いる',r:'しいる',m:'force, thrust'},
  {k:'塩辛い',r:'しおからい',m:'salty'},
  {k:'時間割',r:'じかんわり',m:'time-table'},
  {k:'至急',r:'しきゅう',m:'urgent'},
  {k:'しきりに',r:'しきりに',m:'frequently'},
  {k:'資金',r:'しきん',m:'funds, money'},
  {k:'地獄',r:'じごく',m:'hell'},
  {k:'資産',r:'しさん',m:'asset'},
  {k:'指示',r:'しじ',m:'instructions, directions'},
  {k:'自習',r:'じしゅう',m:'self-study'},
  {k:'市場',r:'しじょう',m:'market'},
  {k:'システム',r:'システム',m:'system'},
  {k:'静まる',r:'しずまる',m:'subside'},
  {k:'沈む',r:'しずむ',m:'sink'},
  {k:'静める',r:'しずめる',m:'calm'},
  {k:'姿勢',r:'しせい',m:'posture'},
  {k:'事前',r:'じぜん',m:'in advance'},
  {k:'子孫',r:'しそん',m:'descendant'},
  {k:'次第に',r:'しだいに',m:'gradually'},
  {k:'従う',r:'したがう',m:'obey'},
  {k:'親しい',r:'したしい',m:'close'},
  {k:'親しみ',r:'したしみ',m:'familiarity'},
  {k:'親しむ',r:'したしむ',m:'be friendly'},
  {k:'質',r:'しつ',m:'quality'},
  {k:'失業',r:'しつぎょう',m:'unemployment'},
  {k:'失業率',r:'しつぎょうりつ',m:'unemployment rate'},
  {k:'じっくり',r:'じっくり',m:'carefully and deliberately'},
  {k:'実験',r:'じっけん',m:'experiment, test'},
  {k:'しつこい',r:'しつこい',m:'persistent, stubborn'},
  {k:'実施',r:'じっし',m:'implementation'},
  {k:'湿度',r:'しつど',m:'humidity'},
  {k:'しっとり',r:'しっとり',m:'moist'},
  {k:'実に',r:'じつに',m:'truly'},
  {k:'執筆',r:'しっぴつ',m:'writing'},
  {k:'失望',r:'しつぼう',m:'disappointment'},
  {k:'失恋',r:'しつれん',m:'broken heart'},
  {k:'指定',r:'してい',m:'designation'},
  {k:'指導',r:'しどう',m:'guidance'},
  {k:'支配',r:'しはい',m:'control, rule'},
  {k:'芝居',r:'しばい',m:'play'},
  {k:'しばしば',r:'しばしば',m:'often'},
  {k:'支払い',r:'しはらい',m:'payment'},
  {k:'支払う',r:'しはらう',m:'pay'},
  {k:'縛る',r:'しばる',m:'tie, restrict'},
  {k:'地盤',r:'じばん',m:'foundation, ground'},
  {k:'しびれる',r:'しびれる',m:'become numb'},
  {k:'絞る',r:'しぼる',m:'wring, focus on'},
  {k:'搾る',r:'しぼる',m:'squeeze'},
  {k:'自慢',r:'じまん',m:'pride'},
  {k:'地味',r:'じみ',m:'plain'},
  {k:'染み込む',r:'しみこむ',m:'permeate, soak into'},
  {k:'しみじみ',r:'しみじみ',m:'deeply'},
  {k:'染みる',r:'しみる',m:'soak, pierce, deeply moved'},
  {k:'じめじめ',r:'じめじめ',m:'gloomy'},
  {k:'しゃがむ',r:'しゃがむ',m:'squat, crouch'},
  {k:'若干',r:'じゃっかん',m:'a bit, slightly'},
  {k:'借金',r:'しゃっきん',m:'debt'},
  {k:'しゃっくり',r:'しゃっくり',m:'hiccup'},
  {k:'しゃぶる',r:'しゃぶる',m:'suck'},
  {k:'しゃれ',r:'しゃれ',m:'joke, pun'},
  {k:'ジャンル',r:'ジャンル',m:'genre, field'},
  {k:'周囲',r:'しゅうい',m:'surrounding'},
  {k:'収穫量',r:'しゅうかくりょう',m:'crop yield'},
  {k:'周期',r:'しゅうき',m:'cycle, period'},
  {k:'終始',r:'しゅうし',m:'from beginning to end'},
  {k:'重視',r:'じゅうし',m:'emphasis, regard as important'},
  {k:'収集',r:'しゅうしゅう',m:'collection'},
  {k:'就職',r:'しゅうしょく',m:'employment'},
  {k:'就職活動',r:'しゅうしょくかつどう',m:'job hunting'},
  {k:'修正',r:'しゅうせい',m:'correction'},
  {k:'収入',r:'しゅうにゅう',m:'income'},
  {k:'就任',r:'しゅうにん',m:'inauguration, taking up a post'},
  {k:'周辺',r:'しゅうへん',m:'around'},
  {k:'修理',r:'しゅうり',m:'repair'},
  {k:'縮小',r:'しゅくしょう',m:'shrink'},
  {k:'宿泊',r:'しゅくはく',m:'lodging'},
  {k:'取材',r:'しゅざい',m:'news gathering'},
  {k:'首相',r:'しゅしょう',m:'prime minister'},
  {k:'受賞',r:'じゅしょう',m:'prize winning'},
  {k:'受信',r:'じゅしん',m:'reception'},
  {k:'主張',r:'しゅちょう',m:'assertion, insistence'},
  {k:'出荷',r:'しゅっか',m:'shipment'},
  {k:'出張',r:'しゅっちょう',m:'business trip'},
  {k:'首都',r:'しゅと',m:'capital city'},
  {k:'首脳',r:'しゅのう',m:'leaders'},
  {k:'需要',r:'じゅよう',m:'demand'},
  {k:'消化',r:'しょうか',m:'digestion'},
  {k:'証言',r:'しょうげん',m:'testimony'},
  {k:'証拠',r:'しょうこ',m:'evidence'},
  {k:'詳細',r:'しょうさい',m:'details'},
  {k:'上司',r:'じょうし',m:'boss'},
  {k:'上旬',r:'じょうじゅん',m:'first ten days of the month'},
  {k:'少々',r:'しょうしょう',m:'a little'},
  {k:'症状',r:'しょうじょう',m:'symptom'},
  {k:'上昇',r:'じょうしょう',m:'rising'},
  {k:'承諾',r:'しょうだく',m:'acceptance'},
  {k:'上達',r:'じょうたつ',m:'progress'},
  {k:'消毒',r:'しょうどく',m:'disinfection'},
  {k:'衝突',r:'しょうとつ',m:'collision'},
  {k:'勝敗',r:'しょうはい',m:'victory or defeat'},
  {k:'消費',r:'しょうひ',m:'consumption'},
  {k:'消費者',r:'しょうひしゃ',m:'consumer'},
  {k:'賞品',r:'しょうひん',m:'prize, trophy'},
  {k:'勝負',r:'しょうぶ',m:'game'},
  {k:'丈夫',r:'じょうぶ',m:'strong, solid'},
  {k:'情報',r:'じょうほう',m:'information'},
  {k:'条約',r:'じょうやく',m:'treaty'},
  {k:'少量',r:'しょうりょう',m:'small amount'},
  {k:'助言',r:'じょげん',m:'advice'},
  {k:'初旬',r:'しょじゅん',m:'first ten days of the month'},
  {k:'徐々に',r:'じょじょに',m:'steadily'},
  {k:'書籍',r:'しょせき',m:'book'},
  {k:'ショッキング',r:'ショッキング',m:'shocking'},
  {k:'しょっちゅう',r:'しょっちゅう',m:'constantly'},
  {k:'しょっぱい',r:'しょっぱい',m:'salty'},
  {k:'庶民',r:'しょみん',m:'ordinary people'},
  {k:'白髪',r:'しらが',m:'grey hair'},
  {k:'知り合い',r:'しりあい',m:'acquaintance'},
  {k:'城',r:'しろ',m:'castle'},
  {k:'しわ',r:'しわ',m:'wrinkle'},
  {k:'進化',r:'しんか',m:'evolution'},
  {k:'進学',r:'しんがく',m:'moving onto the next stage of education'},
  {k:'深刻',r:'しんこく',m:'serious'},
  {k:'深刻化',r:'しんこくか',m:'becoming more serious'},
  {k:'診察',r:'しんさつ',m:'medical examination'},
  {k:'真実',r:'しんじつ',m:'truth'},
  {k:'申請',r:'しんせい',m:'application'},
  {k:'新鮮',r:'しんせん',m:'fresh'},
  {k:'親戚',r:'しんせき',m:'relative'},
  {k:'診断',r:'しんだん',m:'diagnosis'},
  {k:'慎重',r:'しんちょう',m:'careful'},
  {k:'新年',r:'しんねん',m:'New Year'},
  {k:'人物',r:'じんぶつ',m:'man, figure'},
  {k:'進歩',r:'しんぽ',m:'progress'},
  {k:'心理',r:'しんり',m:'state of mind, psychology'},
  {k:'心理的',r:'しんりてき',m:'psychological'},
  {k:'森林',r:'しんりん',m:'forest'},
  {k:'親類',r:'しんるい',m:'relative'},
  // す
  {k:'酢',r:'す',m:'vinegar'},
  {k:'炊事',r:'すいじ',m:'cooking'},
  {k:'随筆',r:'ずいひつ',m:'essay'},
  {k:'水平線',r:'すいへいせん',m:'horizon'},
  {k:'睡眠',r:'すいみん',m:'sleep'},
  {k:'睡眠不足',r:'すいみんぶそく',m:'lack of sleep'},
  {k:'ずうずうしい',r:'ずうずうしい',m:'brazen-faced, shameless'},
  {k:'末っ子',r:'すえっこ',m:'youngest child'},
  {k:'杉',r:'すぎ',m:'cedar'},
  {k:'優れる',r:'すぐれる',m:'be excellent'},
  {k:'スケジュール',r:'スケジュール',m:'schedule'},
  {k:'過ごす',r:'すごす',m:'pass'},
  {k:'涼む',r:'すずむ',m:'cool down'},
  {k:'勧める',r:'すすめる',m:'encourage, suggest'},
  {k:'頭痛',r:'ずつう',m:'headache'},
  {k:'ずっしり',r:'ずっしり',m:'heavily'},
  {k:'酸っぱい',r:'すっぱい',m:'sour'},
  {k:'既に',r:'すでに',m:'already'},
  {k:'ストレス',r:'ストレス',m:'stress'},
  {k:'砂',r:'すな',m:'sand'},
  {k:'ずばり',r:'ずばり',m:'frankly'},
  {k:'すべて',r:'すべて',m:'all'},
  {k:'済まない',r:'すまない',m:'be sorry'},
  {k:'スムーズ',r:'スムーズ',m:'smooth'},
  {k:'ずらりと',r:'ずらりと',m:'in a line'},
  {k:'鋭い',r:'するどい',m:'sharp, acute'},
  {k:'すれ違う',r:'すれちがう',m:'pass each other'},
  {k:'すんなり',r:'すんなり',m:'smoothly'},
  // せ
  {k:'正確',r:'せいかく',m:'accurate'},
  {k:'正確さ',r:'せいかくさ',m:'accuracy'},
  {k:'税関',r:'ぜいかん',m:'customs'},
  {k:'税金',r:'ぜいきん',m:'tax'},
  {k:'清潔',r:'せいけつ',m:'cleanliness'},
  {k:'制限',r:'せいげん',m:'restriction'},
  {k:'制作',r:'せいさく',m:'production'},
  {k:'生産',r:'せいさん',m:'production'},
  {k:'生産量',r:'せいさんりょう',m:'production volume/amount'},
  {k:'正式',r:'せいしき',m:'formally'},
  {k:'成人',r:'せいじん',m:'adult'},
  {k:'成人式',r:'せいじんしき',m:'coming-of-age ceremony'},
  {k:'せいぜい',r:'せいぜい',m:'at the most'},
  {k:'成績',r:'せいせき',m:'academic result/record'},
  {k:'製造',r:'せいぞう',m:'manufacturing'},
  {k:'盛大',r:'せいだい',m:'magnificent'},
  {k:'ぜいたく',r:'ぜいたく',m:'luxurious'},
  {k:'成長',r:'せいちょう',m:'growth'},
  {k:'生徒',r:'せいと',m:'student'},
  {k:'制度',r:'せいど',m:'system, institution'},
  {k:'性能',r:'せいのう',m:'performance'},
  {k:'整備',r:'せいび',m:'maintenance'},
  {k:'製品',r:'せいひん',m:'product'},
  {k:'政府',r:'せいふ',m:'government'},
  {k:'生物',r:'せいぶつ',m:'living thing, creature'},
  {k:'整理',r:'せいり',m:'arrangement'},
  {k:'背負う',r:'せおう',m:'carry on one\'s back'},
  {k:'せき',r:'せき',m:'cough'},
  {k:'石油',r:'せきゆ',m:'oil'},
  {k:'世間',r:'せけん',m:'society, world, people'},
  {k:'せっかく',r:'せっかく',m:'with considerable trouble, carefully'},
  {k:'積極的',r:'せっきょくてき',m:'positive, assertive'},
  {k:'せっせと',r:'せっせと',m:'busily, hard'},
  {k:'接続',r:'せつぞく',m:'connection'},
  {k:'設定',r:'せってい',m:'settings'},
  {k:'説得',r:'せっとく',m:'persuasion'},
  {k:'設備',r:'せつび',m:'equipment'},
  {k:'絶滅',r:'ぜつめつ',m:'extinction'},
  {k:'迫る',r:'せまる',m:'approach, press'},
  {k:'ゼミ',r:'ゼミ',m:'seminar'},
  {k:'せめて',r:'せめて',m:'at least'},
  {k:'セリフ',r:'セリフ',m:'lines'},
  {k:'栓',r:'せん',m:'stopper, cork, plug'},
  {k:'選挙',r:'せんきょ',m:'election'},
  {k:'専攻',r:'せんこう',m:'major'},
  {k:'全身',r:'ぜんしん',m:'whole body'},
  {k:'宣伝',r:'せんでん',m:'advertisement'},
  {k:'先輩',r:'せんぱい',m:'senior'},
  {k:'専門家',r:'せんもんか',m:'expert'},
  {k:'線路',r:'せんろ',m:'rail track'},
  // そ
  {k:'沿う',r:'そう',m:'go along'},
  {k:'騒音',r:'そうおん',m:'noise, din'},
  {k:'増加',r:'ぞうか',m:'increase'},
  {k:'倉庫',r:'そうこ',m:'warehouse'},
  {k:'操作',r:'そうさ',m:'operation'},
  {k:'捜査',r:'そうさ',m:'(criminal) investigation'},
  {k:'葬式',r:'そうしき',m:'funeral'},
  {k:'送信',r:'そうしん',m:'transmission, sending'},
  {k:'増大',r:'ぞうだい',m:'increase'},
  {k:'相談相手',r:'そうだんあいて',m:'advisor'},
  {k:'早朝',r:'そうちょう',m:'early morning'},
  {k:'相当',r:'そうとう',m:'considerable'},
  {k:'挿入',r:'そうにゅう',m:'insertion'},
  {k:'送別会',r:'そうべつかい',m:'farewell party'},
  {k:'続々',r:'ぞくぞく',m:'one after another'},
  {k:'測定',r:'そくてい',m:'measurement'},
  {k:'組織',r:'そしき',m:'organization'},
  {k:'祖先',r:'そせん',m:'ancestor'},
  {k:'注ぐ',r:'そそぐ',m:'pour, flow into, focus one\'s efforts'},
  {k:'そそっかしい',r:'そそっかしい',m:'careless'},
  {k:'育つ',r:'そだつ',m:'grow up'},
  {k:'そっくり',r:'そっくり',m:'spitting image, exactly (like)'},
  {k:'率直',r:'そっちょく',m:'frank'},
  {k:'備える',r:'そなえる',m:'prepare for'},
  {k:'そのうち',r:'そのうち',m:'before long'},
  {k:'ソフト',r:'ソフト',m:'software'},
  {k:'粗末',r:'そまつ',m:'shabby, plain, waste'},
  {k:'そる',r:'そる',m:'shave'},
  {k:'それぞれ',r:'それぞれ',m:'each'},
  {k:'そわそわ',r:'そわそわ',m:'uneasy'},
  {k:'損害',r:'そんがい',m:'damage'},
  {k:'尊敬',r:'そんけい',m:'respect'},
  // た
  {k:'退化',r:'たいか',m:'degeneration'},
  {k:'大気',r:'たいき',m:'atmosphere'},
  {k:'大気汚染',r:'たいきおせん',m:'air pollution'},
  {k:'大規模',r:'だいきぼ',m:'large scale'},
  {k:'滞在',r:'たいざい',m:'stay'},
  {k:'たいして',r:'たいして',m:'(not) that'},
  {k:'大臣',r:'だいじん',m:'minister'},
  {k:'体積',r:'たいせき',m:'volume'},
  {k:'大多数',r:'だいたすう',m:'great majority'},
  {k:'態度',r:'たいど',m:'attitude'},
  {k:'大統領',r:'だいとうりょう',m:'president'},
  {k:'逮捕',r:'たいほ',m:'arrest'},
  {k:'タイミング',r:'タイミング',m:'timing'},
  {k:'対立',r:'たいりつ',m:'opposition'},
  {k:'大量',r:'たいりょう',m:'a large amount'},
  {k:'ダウンロード',r:'ダウンロード',m:'download'},
  {k:'絶えず',r:'たえず',m:'constantly'},
  {k:'高まる',r:'たかまる',m:'increase, heighten'},
  {k:'高める',r:'たかめる',m:'increase'},
  {k:'耕す',r:'たがやす',m:'plough, cultivate'},
  {k:'滝',r:'たき',m:'waterfall'},
  {k:'炊く',r:'たく',m:'cook'},
  {k:'抱く',r:'だく',m:'hold/hug'},
  {k:'託児所',r:'たくじしょ',m:'nursery'},
  {k:'たくましい',r:'たくましい',m:'strong, burly'},
  {k:'足し算',r:'たしざん',m:'addition'},
  {k:'多少',r:'たしょう',m:'a bit, somewhat'},
  {k:'足す',r:'たす',m:'add'},
  {k:'助け',r:'たすけ',m:'help'},
  {k:'助け合う',r:'たすけあう',m:'help each other'},
  {k:'畳む',r:'たたむ',m:'fold'},
  {k:'立ち上がる',r:'たちあがる',m:'rise, stand up'},
  {k:'立ち上げる',r:'たちあげる',m:'launch'},
  {k:'たちまち',r:'たちまち',m:'immediately'},
  {k:'発つ',r:'たつ',m:'leave'},
  {k:'たつ',r:'たつ',m:'pass'},
  {k:'だっこ',r:'だっこ',m:'hug'},
  {k:'達する',r:'たっする',m:'reach'},
  {k:'たった',r:'たった',m:'only'},
  {k:'たっぷり',r:'たっぷり',m:'plenty'},
  {k:'建て直す',r:'たてなおす',m:'rebuild'},
  {k:'妥当',r:'だとう',m:'proper'},
  {k:'たとえ',r:'たとえ',m:'even if'},
  {k:'谷',r:'たに',m:'valley'},
  {k:'種',r:'たね',m:'seed'},
  {k:'楽しみ',r:'たのしみ',m:'pleasure'},
  {k:'頼もしい',r:'たのもしい',m:'reliable'},
  {k:'たびたび',r:'たびたび',m:'frequently'},
  {k:'たまに',r:'たまに',m:'occasionally'},
  {k:'黙り込む',r:'だまりこむ',m:'fall silent'},
  {k:'たまる',r:'たまる',m:'accumulate, build up'},
  {k:'ためる',r:'ためる',m:'save up'},
  {k:'頼り',r:'たより',m:'reliance'},
  {k:'だらしない',r:'だらしない',m:'slovenly'},
  {k:'短所',r:'たんしょ',m:'shortcomings'},
  {k:'担当',r:'たんとう',m:'in charge'},
  {k:'単なる',r:'たんなる',m:'mere'},
  {k:'単に',r:'たんに',m:'simply'},
  // ち
  {k:'誓う',r:'ちかう',m:'swear'},
  {k:'地下水',r:'ちかすい',m:'ground water'},
  {k:'近々',r:'ちかぢか',m:'shortly'},
  {k:'力を入れる',r:'ちからをいれる',m:'put effort into'},
  {k:'地球温暖化',r:'ちきゅうおんだんか',m:'global warming'},
  {k:'知人',r:'ちじん',m:'acquaintance'},
  {k:'父親',r:'ちちおや',m:'father'},
  {k:'縮む',r:'ちぢむ',m:'shrink'},
  {k:'ちっとも',r:'ちっとも',m:'(not a) bit'},
  {k:'地平線',r:'ちへいせん',m:'horizon'},
  {k:'地方',r:'ちほう',m:'region'},
  {k:'チャンス',r:'チャンス',m:'chance'},
  {k:'中間試験',r:'ちゅうかんしけん',m:'mid-term examination'},
  {k:'忠告',r:'ちゅうこく',m:'advice'},
  {k:'注射器',r:'ちゅうしゃき',m:'syringe'},
  {k:'中旬',r:'ちゅうじゅん',m:'middle ten days of a month'},
  {k:'中断',r:'ちゅうだん',m:'interruption'},
  {k:'注目',r:'ちゅうもく',m:'attention'},
  {k:'注文',r:'ちゅうもん',m:'order'},
  {k:'超一流',r:'ちょういちりゅう',m:'top-notch'},
  {k:'朝刊',r:'ちょうかん',m:'morning newspaper'},
  {k:'長所',r:'ちょうしょ',m:'strong point'},
  {k:'頂上',r:'ちょうじょう',m:'summit, top'},
  {k:'調整',r:'ちょうせい',m:'adjustment'},
  {k:'ちょうど',r:'ちょうど',m:'just'},
  {k:'長方形',r:'ちょうほうけい',m:'rectangle'},
  {k:'調味料',r:'ちょうみりょう',m:'seasoning'},
  {k:'貯金',r:'ちょきん',m:'savings'},
  {k:'著者',r:'ちょしゃ',m:'author, writer'},
  {k:'貯蓄',r:'ちょちく',m:'savings'},
  {k:'著名人',r:'ちょめいじん',m:'celebrity'},
  {k:'散らかる',r:'ちらかる',m:'be scattered'},
  {k:'ちらっと',r:'ちらっと',m:'glance'},
  // つ
  {k:'つい',r:'つい',m:'by accident, without meaning'},
  {k:'追加',r:'ついか',m:'addition'},
  {k:'ついに',r:'ついに',m:'finally'},
  {k:'費やす',r:'ついやす',m:'spend'},
  {k:'通学',r:'つうがく',m:'attending school'},
  {k:'通勤',r:'つうきん',m:'commuting'},
  {k:'通訳',r:'つうやく',m:'interpretation'},
  {k:'使い道',r:'つかいみち',m:'how to use'},
  {k:'捕まる',r:'つかまる',m:'get caught'},
  {k:'つかむ',r:'つかむ',m:'grab'},
  {k:'疲れ気味',r:'つかれぎみ',m:'feeling slightly tired'},
  {k:'付き合い',r:'つきあい',m:'relationship'},
  {k:'次々',r:'つぎつぎ',m:'one after another'},
  {k:'月日',r:'つきひ',m:'time'},
  {k:'つぐ',r:'つぐ',m:'pour'},
  {k:'つくづく',r:'つくづく',m:'thoroughly, deeply'},
  {k:'常に',r:'つねに',m:'always'},
  {k:'つぶす',r:'つぶす',m:'crush'},
  {k:'つぶれる',r:'つぶれる',m:'collapse'},
  {k:'つぼみ',r:'つぼみ',m:'flower bud'},
  {k:'つまむ',r:'つまむ',m:'pick up with one\'s fingers'},
  {k:'罪',r:'つみ',m:'crime'},
  {k:'積む',r:'つむ',m:'load, accumulate, pile up'},
  {k:'詰め込む',r:'つめこむ',m:'cram into'},
  {k:'詰める',r:'つめる',m:'fill'},
  {k:'梅雨',r:'つゆ',m:'rainy season'},
  {k:'強気',r:'つよき',m:'strong, aggressive'},
  {k:'強まる',r:'つよまる',m:'strengthen, intensify'},
  {k:'強み',r:'つよみ',m:'strength'},
  {k:'強める',r:'つよめる',m:'strengthen, increase'},
  {k:'つるす',r:'つるす',m:'hang'},
  {k:'連れ出す',r:'つれだす',m:'take out'},
  // て
  {k:'出会う',r:'であう',m:'meet, come across'},
  {k:'提案',r:'ていあん',m:'suggestion'},
  {k:'定員',r:'ていいん',m:'(seating) capacity'},
  {k:'低下',r:'ていか',m:'decrease'},
  {k:'定期券',r:'ていきけん',m:'commuter pass'},
  {k:'定期預金',r:'ていきよきん',m:'time deposit'},
  {k:'停車',r:'ていしゃ',m:'stopping'},
  {k:'訂正',r:'ていせい',m:'correction'},
  {k:'停電',r:'ていでん',m:'blackout, power failure'},
  {k:'停留所',r:'ていりゅうじょ',m:'stop'},
  {k:'データ',r:'データ',m:'data'},
  {k:'手が空く',r:'てがあく',m:'be free'},
  {k:'手が掛かる',r:'てがかかる',m:'difficult'},
  {k:'手が足りない',r:'てがたりない',m:'be short-handed'},
  {k:'手が出ない',r:'てがでない',m:'be out of one\'s reach'},
  {k:'手が離せない',r:'てがはなせない',m:'be in the middle of something'},
  {k:'敵',r:'てき',m:'enemy'},
  {k:'出来上がる',r:'できあがる',m:'be finished'},
  {k:'適応',r:'てきおう',m:'adaptation'},
  {k:'適切',r:'てきせつ',m:'appropriate'},
  {k:'出来立て',r:'できたて',m:'freshly made, just done'},
  {k:'適度',r:'てきど',m:'moderate'},
  {k:'適当',r:'てきとう',m:'suitable'},
  {k:'てきぱき',r:'てきぱき',m:'efficiently'},
  {k:'テクニック',r:'テクニック',m:'technique'},
  {k:'テクノロジー',r:'テクノロジー',m:'technology'},
  {k:'手続き',r:'てつづき',m:'procedure'},
  {k:'鉄道',r:'てつどう',m:'railway'},
  {k:'徹夜',r:'てつや',m:'staying/sitting up all night'},
  {k:'手につかない',r:'てにつかない',m:'can\'t focus/concentrate on'},
  {k:'手間',r:'てま',m:'time and effort'},
  {k:'出迎える',r:'でむかえる',m:'meet, greet'},
  {k:'手を貸す',r:'てをかす',m:'lend a hand'},
  {k:'手を借りる',r:'てをかりる',m:'accept help'},
  {k:'手を組む',r:'てをくむ',m:'join hands/forces'},
  {k:'手を出す',r:'てをだす',m:'have a finger in, start a fight'},
  {k:'手をつける',r:'てをつける',m:'set one\'s hand to, start work on'},
  {k:'転居',r:'てんきょ',m:'moving, change of address'},
  {k:'点検',r:'てんけん',m:'inspection'},
  {k:'転校',r:'てんこう',m:'changing schools'},
  {k:'天国',r:'てんごく',m:'heaven'},
  {k:'伝言',r:'でんごん',m:'(verbal) message'},
  {k:'伝染',r:'でんせん',m:'infection'},
  {k:'伝統的',r:'でんとうてき',m:'traditional'},
  {k:'天然',r:'てんねん',m:'natural'},
  {k:'天然ガス',r:'てんねんガス',m:'natural gas'},
  {k:'天皇',r:'てんのう',m:'emperor'},
  {k:'添付',r:'てんぷ',m:'attachment'},
  {k:'電力',r:'でんりょく',m:'electric power'},
  // と
  {k:'問いかける',r:'といかける',m:'inquire'},
  {k:'統一',r:'とういつ',m:'unification'},
  {k:'東京発',r:'とうきょうはつ',m:'departing Tokyo'},
  {k:'投資',r:'とうし',m:'investment'},
  {k:'どうせ',r:'どうせ',m:'anyway, at any rate'},
  {k:'到着',r:'とうちゃく',m:'arrival'},
  {k:'とうとう',r:'とうとう',m:'finally'},
  {k:'道徳',r:'どうとく',m:'moral'},
  {k:'道徳的',r:'どうとくてき',m:'moral, ethical'},
  {k:'盗難',r:'とうなん',m:'theft, robbery, burglary'},
  {k:'導入',r:'どうにゅう',m:'introduce'},
  {k:'投票',r:'とうひょう',m:'voting'},
  {k:'当分',r:'とうぶん',m:'for the time being'},
  {k:'どうも',r:'どうも',m:'for some reason'},
  {k:'同僚',r:'どうりょう',m:'colleague'},
  {k:'通りかかる',r:'とおりかかる',m:'happen to pass by'},
  {k:'通り過ぎる',r:'とおりすぎる',m:'pass over/by'},
  {k:'溶かす',r:'とかす',m:'melt'},
  {k:'とかす',r:'とかす',m:'comb, brush'},
  {k:'得意先',r:'とくいさき',m:'good customer'},
  {k:'読書',r:'どくしょ',m:'reading'},
  {k:'独身',r:'どくしん',m:'single'},
  {k:'独立',r:'どくりつ',m:'independence'},
  {k:'解ける',r:'とける',m:'be cleared up'},
  {k:'溶ける',r:'とける',m:'melt'},
  {k:'どける',r:'どける',m:'move'},
  {k:'所々',r:'ところどころ',m:'here and there'},
  {k:'土砂崩れ',r:'どしゃくずれ',m:'landslide'},
  {k:'都心',r:'としん',m:'center of a city'},
  {k:'とっくに',r:'とっくに',m:'already'},
  {k:'突如',r:'とつじょ',m:'suddenly'},
  {k:'怒鳴る',r:'どなる',m:'yell'},
  {k:'飛び込む',r:'とびこむ',m:'jump/dive in'},
  {k:'飛び出す',r:'とびだす',m:'run/rush out'},
  {k:'飛び回る',r:'とびまわる',m:'fly around'},
  {k:'乏しい',r:'とぼしい',m:'scarce, poor'},
  {k:'捕らえる',r:'とらえる',m:'capture'},
  {k:'ドラマ',r:'ドラマ',m:'drama'},
  {k:'取り上げる',r:'とりあげる',m:'take up'},
  {k:'とりあえず',r:'とりあえず',m:'for now, for the time being'},
  {k:'取り入れる',r:'とりいれる',m:'take in'},
  {k:'取り押さえる',r:'とりおさえる',m:'apprehend, arrest'},
  {k:'取り替える',r:'とりかえる',m:'replace'},
  {k:'取り組む',r:'とりくむ',m:'tackle, grapple with'},
  {k:'取り消す',r:'とりけす',m:'cancel'},
  {k:'取り締まる',r:'とりしまる',m:'crack down, control'},
  {k:'取り出す',r:'とりだす',m:'take out'},
  {k:'取り引き',r:'とりひき',m:'transaction'},
  {k:'トレーニング',r:'トレーニング',m:'training'},
  {k:'泥',r:'どろ',m:'mud'},
  // な
  {k:'内科',r:'ないか',m:'internal medicine'},
  {k:'内閣総理大臣',r:'ないかくそうりだいじん',m:'prime minister'},
  {k:'内容',r:'ないよう',m:'content'},
  {k:'なお',r:'なお',m:'even, further'},
  {k:'なおさら',r:'なおさら',m:'still more'},
  {k:'流す',r:'ながす',m:'broadcast'},
  {k:'中でも',r:'なかでも',m:'most especially'},
  {k:'仲直り',r:'なかなおり',m:'reconciliation, making up with'},
  {k:'なかなか',r:'なかなか',m:'(not) easily, hardly'},
  {k:'長年',r:'ながねん',m:'many years'},
  {k:'半ば',r:'なかば',m:'halfway, the middle'},
  {k:'眺め',r:'ながめ',m:'view'},
  {k:'眺める',r:'ながめる',m:'gaze'},
  {k:'長持ち',r:'ながもち',m:'long lasting'},
  {k:'流れる',r:'ながれる',m:'broadcast'},
  {k:'泣き出す',r:'なきだす',m:'start crying'},
  {k:'慰める',r:'なぐさめる',m:'cheer up'},
  {k:'嘆く',r:'なげく',m:'grieve about'},
  {k:'なだらか',r:'なだらか',m:'gently sloping'},
  {k:'懐かしい',r:'なつかしい',m:'nostalgic, fondly remembered'},
  {k:'なでる',r:'なでる',m:'stroke, pat'},
  {k:'何しろ',r:'なにしろ',m:'you know, in any case'},
  {k:'何より',r:'なにより',m:'more than anything'},
  {k:'生意気',r:'なまいき',m:'cheeky'},
  {k:'怠ける',r:'なまける',m:'be lazy, neglect'},
  {k:'波',r:'なみ',m:'wave'},
  {k:'並ぶ',r:'ならぶ',m:'be in a line'},
  {k:'何だか',r:'なんだか',m:'somehow'},
  {k:'なんと',r:'なんと',m:'how, what'},
  {k:'何とか',r:'なんとか',m:'somehow'},
  {k:'何となく',r:'なんとなく',m:'for some reason or other'},
  // に
  {k:'ニーズ',r:'ニーズ',m:'needs'},
  {k:'煮える',r:'にえる',m:'boil'},
  {k:'苦手',r:'にがて',m:'weak/poor at'},
  {k:'苦み',r:'にがみ',m:'bitterness'},
  {k:'握る',r:'にぎる',m:'seize'},
  {k:'憎い',r:'にくい',m:'hateful'},
  {k:'憎む',r:'にくむ',m:'hate'},
  {k:'憎らしい',r:'にくらしい',m:'detestable'},
  {k:'逃げ出す',r:'にげだす',m:'run away'},
  {k:'逃げ回る',r:'にげまわる',m:'run this way and that'},
  {k:'にこにこ',r:'にこにこ',m:'beaming, all smiles'},
  {k:'二酸化炭素',r:'にさんかたんそ',m:'carbon dioxide'},
  {k:'日中',r:'にっちゅう',m:'daytime'},
  {k:'日程',r:'にってい',m:'schedule'},
  {k:'鈍い',r:'にぶい',m:'blunt, thick-headed, dull'},
  {k:'日本産',r:'にほんさん',m:'made in Japan'},
  {k:'日本列島',r:'にほんれっとう',m:'Japanese archipelago'},
  {k:'にやにや',r:'にやにや',m:'grinning'},
  {k:'入社',r:'にゅうしゃ',m:'joining a company'},
  {k:'入手',r:'にゅうしゅ',m:'obtainment'},
  {k:'にらむ',r:'にらむ',m:'glare/stare at'},
  {k:'煮る',r:'にる',m:'boil'},
  {k:'にわかに',r:'にわかに',m:'suddenly'},
  {k:'鶏',r:'にわとり',m:'chicken'},
  {k:'人気',r:'にんき',m:'popular'},
  // ぬ
  {k:'縫う',r:'ぬう',m:'sew'},
  {k:'抜き出す',r:'ぬきだす',m:'pull out'},
  {k:'抜ける',r:'ぬける',m:'fall out'},
  // ね
  {k:'値上がり',r:'ねあがり',m:'rise in prices'},
  {k:'値上げ',r:'ねあげ',m:'price increase'},
  {k:'願う',r:'ねがう',m:'hope'},
  {k:'値下がり',r:'ねさがり',m:'decrease in prices'},
  {k:'ねじる',r:'ねじる',m:'twist'},
  {k:'熱する',r:'ねっする',m:'heat'},
  {k:'熱中',r:'ねっちゅう',m:'passionate, enthusiastic'},
  {k:'寝不足',r:'ねぶそく',m:'lack of sleep'},
  {k:'眠り込む',r:'ねむりこむ',m:'fall asleep'},
  {k:'眠る',r:'ねむる',m:'sleep'},
  {k:'ねらう',r:'ねらう',m:'target'},
  {k:'年賀状',r:'ねんがじょう',m:'New Year\'s card'},
  {k:'年月',r:'ねんげつ',m:'years'},
  {k:'年中',r:'ねんじゅう',m:'all year round'},
  // の
  {k:'農業',r:'のうぎょう',m:'agriculture'},
  {k:'農作業',r:'のうさぎょう',m:'farm work'},
  {k:'能率',r:'のうりつ',m:'efficiency'},
  {k:'逃す',r:'のがす',m:'miss'},
  {k:'ののしる',r:'ののしる',m:'curse'},
  {k:'伸ばす',r:'のばす',m:'smooth out'},
  {k:'のびのび',r:'のびのび',m:'free and easily'},
  {k:'乗り遅れる',r:'のりおくれる',m:'miss'},
  {k:'乗り越える',r:'のりこえる',m:'overcome'},
  {k:'乗り越す',r:'のりこす',m:'go beyond one\'s stop'},
  {k:'乗り込む',r:'のりこむ',m:'board'},
  {k:'のろのろ',r:'のろのろ',m:'sluggishly, slowly'},
  {k:'のん気',r:'のんき',m:'carefree'},
  {k:'のんびり',r:'のんびり',m:'laid-back'},
  // は
  {k:'排出量',r:'はいしゅつりょう',m:'emission amount'},
  {k:'配置',r:'はいち',m:'layout'},
  {k:'売店',r:'ばいてん',m:'stand, kiosk'},
  {k:'はう',r:'はう',m:'crawl'},
  {k:'墓',r:'はか',m:'grave'},
  {k:'墓参り',r:'はかまいり',m:'visit to a grave'},
  {k:'吐き気',r:'はきけ',m:'nausea'},
  {k:'はきはき',r:'はきはき',m:'frankly, clearly'},
  {k:'吐く',r:'はく',m:'vomit'},
  {k:'掃く',r:'はく',m:'sweep'},
  {k:'破産',r:'はさん',m:'bankruptcy'},
  {k:'走り回る',r:'はしりまわる',m:'run around'},
  {k:'パスポート',r:'パスポート',m:'passport'},
  {k:'肌',r:'はだ',m:'skin'},
  {k:'畑',r:'はたけ',m:'field'},
  {k:'果たす',r:'はたす',m:'carry out'},
  {k:'発芽',r:'はつが',m:'germination'},
  {k:'発見',r:'はっけん',m:'discovery'},
  {k:'発行',r:'はっこう',m:'issue'},
  {k:'発車',r:'はっしゃ',m:'departure'},
  {k:'発生',r:'はっせい',m:'occurrence'},
  {k:'発想',r:'はっそう',m:'idea'},
  {k:'発達',r:'はったつ',m:'development'},
  {k:'発展',r:'はってん',m:'development'},
  {k:'発電所',r:'はつでんしょ',m:'power plant'},
  {k:'発明',r:'はつめい',m:'invention'},
  {k:'初雪',r:'はつゆき',m:'first snow'},
  {k:'派手',r:'はで',m:'colorful, showy'},
  {k:'話し合い',r:'はなしあい',m:'discussion'},
  {k:'話し合う',r:'はなしあう',m:'discuss'},
  {k:'話しかける',r:'はなしかける',m:'talk'},
  {k:'話し込む',r:'はなしこむ',m:'be deep in talk'},
  {k:'話しぶり',r:'はなしぶり',m:'one\'s way of talking'},
  {k:'鼻が高い',r:'はながたかい',m:'proud'},
  {k:'鼻で笑う',r:'はなでわらう',m:'laugh scornfully'},
  {k:'花婿',r:'はなむこ',m:'bridegroom'},
  {k:'華やか',r:'はなやか',m:'gorgeous'},
  {k:'花嫁',r:'はなよめ',m:'bride'},
  {k:'跳ねる',r:'はねる',m:'jump, bounce'},
  {k:'幅',r:'はば',m:'width'},
  {k:'母親',r:'ははおや',m:'mother'},
  {k:'はまる',r:'はまる',m:'fit into, be caught'},
  {k:'早まる',r:'はやまる',m:'move forward, hasten'},
  {k:'速まる',r:'はやまる',m:'quicken'},
  {k:'早める',r:'はやめる',m:'move forward'},
  {k:'速める',r:'はやめる',m:'quicken'},
  {k:'払い込む',r:'はらいこむ',m:'pay'},
  {k:'腹が決まる',r:'はらがきまる',m:'make up one\'s mind'},
  {k:'腹が立つ',r:'はらがたつ',m:'get angry'},
  {k:'腹を決める',r:'はらをきめる',m:'make up one\'s mind'},
  {k:'腹を立てる',r:'はらをたてる',m:'get angry'},
  {k:'張り切る',r:'はりきる',m:'be enthusiastic'},
  {k:'はるか',r:'はるか',m:'faraway, a long time'},
  {k:'範囲',r:'はんい',m:'area, range'},
  {k:'反抗的',r:'はんこうてき',m:'defiant, rebellious'},
  {k:'犯罪防止',r:'はんざいぼうし',m:'crime prevention'},
  {k:'繁殖',r:'はんしょく',m:'breeding'},
  {k:'半世紀',r:'はんせいき',m:'half a century'},
  {k:'半そで',r:'はんそで',m:'short sleeve'},
  {k:'半透明',r:'はんとうめい',m:'translucent'},
  {k:'反時計回り',r:'はんとけいまわり',m:'anti-clockwise'},
  {k:'犯人',r:'はんにん',m:'criminal'},
  {k:'反比例',r:'はんぴれい',m:'inverse proportion'},
  {k:'はんらん',r:'はんらん',m:'flooding'},
  // ひ
  {k:'被害',r:'ひがい',m:'damage, harm'},
  {k:'非課税',r:'ひかぜい',m:'tax/duty free'},
  {k:'引き受ける',r:'ひきうける',m:'undertake'},
  {k:'引き返す',r:'ひきかえす',m:'turn back'},
  {k:'引き算',r:'ひきざん',m:'subtraction'},
  {k:'引き出す',r:'ひきだす',m:'pull out, withdraw'},
  {k:'引き止める',r:'ひきとめる',m:'hold back'},
  {k:'引き取る',r:'ひきとる',m:'pick up'},
  {k:'ひきょう',r:'ひきょう',m:'coward'},
  {k:'引き分け',r:'ひきわけ',m:'draw'},
  {k:'引く',r:'ひく',m:'subtract'},
  {k:'ひげ',r:'ひげ',m:'beard'},
  {k:'非公開',r:'ひこうかい',m:'not open to the public'},
  {k:'非公式',r:'ひこうしき',m:'informal'},
  {k:'日ごろ',r:'ひごろ',m:'usually'},
  {k:'日差し',r:'ひざし',m:'sunlight'},
  {k:'被災者',r:'ひさいしゃ',m:'victim'},
  {k:'非常に',r:'ひじょうに',m:'extremely'},
  {k:'ビタミン',r:'ビタミン',m:'vitamin'},
  {k:'引っかかる',r:'ひっかかる',m:'stuck, get caught'},
  {k:'引っかく',r:'ひっかく',m:'scratch'},
  {k:'引っかける',r:'ひっかける',m:'catch'},
  {k:'必死',r:'ひっし',m:'desperate'},
  {k:'びっしょり',r:'びっしょり',m:'drenched'},
  {k:'びっしり',r:'びっしり',m:'tightly packed, full of'},
  {k:'ひっそり',r:'ひっそり',m:'still, quiet'},
  {k:'ぴったり',r:'ぴったり',m:'exactly'},
  {k:'引っ張る',r:'ひっぱる',m:'lead'},
  {k:'否定',r:'ひてい',m:'negation, denial'},
  {k:'人違い',r:'ひとちがい',m:'mistaking one person for another'},
  {k:'ひとまず',r:'ひとまず',m:'for now'},
  {k:'一人暮らし',r:'ひとりぐらし',m:'living alone'},
  {k:'避難',r:'ひなん',m:'evacuation'},
  {k:'皮肉',r:'ひにく',m:'irony'},
  {k:'ひねる',r:'ひねる',m:'twist'},
  {k:'批判',r:'ひはん',m:'criticism'},
  {k:'批評',r:'ひひょう',m:'criticism'},
  {k:'冷やす',r:'ひやす',m:'chill'},
  {k:'ひやひや',r:'ひやひや',m:'nervously'},
  {k:'評価',r:'ひょうか',m:'evaluation'},
  {k:'評判',r:'ひょうばん',m:'reputation'},
  {k:'表面化',r:'ひょうめんか',m:'surfacing'},
  {k:'評論',r:'ひょうろん',m:'criticism'},
  {k:'ヒヨコ',r:'ヒヨコ',m:'chick'},
  {k:'ひょっとしたら',r:'ひょっとしたら',m:'possibly'},
  {k:'ひょっとすると',r:'ひょっとすると',m:'possibly'},
  {k:'微量',r:'びりょう',m:'very small amount'},
  {k:'広がる',r:'ひろがる',m:'unfold'},
  {k:'広まる',r:'ひろまる',m:'spread'},
  {k:'広める',r:'ひろめる',m:'spread'},
  {k:'瓶',r:'びん',m:'bottle'},
  {k:'品種',r:'ひんしゅ',m:'variety'},
  {k:'品種改良',r:'ひんしゅかいりょう',m:'selective breeding'},
  {k:'頻繁',r:'ひんぱん',m:'frequency'},
  {k:'ひんやり',r:'ひんやり',m:'cool'},
  // ふ
  {k:'ファイル',r:'ファイル',m:'file'},
  {k:'部下',r:'ぶか',m:'subordinate'},
  {k:'深まる',r:'ふかまる',m:'deepen'},
  {k:'深み',r:'ふかみ',m:'depth'},
  {k:'深める',r:'ふかめる',m:'deepen'},
  {k:'不規則',r:'ふきそく',m:'irregular'},
  {k:'普及',r:'ふきゅう',m:'diffusion'},
  {k:'普及率',r:'ふきゅうりつ',m:'diffusion rate'},
  {k:'不器用',r:'ぶきよう',m:'clumsy'},
  {k:'ふく',r:'ふく',m:'wipe'},
  {k:'副作用',r:'ふくさよう',m:'side effect'},
  {k:'服装',r:'ふくそう',m:'clothing'},
  {k:'含む',r:'ふくむ',m:'have something in one\'s mouth'},
  {k:'膨らむ',r:'ふくらむ',m:'swell, expand'},
  {k:'不景気',r:'ふけいき',m:'recession'},
  {k:'不潔',r:'ふけつ',m:'dirty'},
  {k:'ふさがる',r:'ふさがる',m:'be closed, close up, be occupied'},
  {k:'ふざける',r:'ふざける',m:'play around'},
  {k:'ふさわしい',r:'ふさわしい',m:'suitable'},
  {k:'武士',r:'ぶし',m:'samurai'},
  {k:'不足',r:'ふそく',m:'lack, shortage'},
  {k:'舞台',r:'ぶたい',m:'stage'},
  {k:'双子',r:'ふたご',m:'twins'},
  {k:'負担',r:'ふたん',m:'burden, responsibility'},
  {k:'物価',r:'ぶっか',m:'prices'},
  {k:'ぶつかる',r:'ぶつかる',m:'hit, collide'},
  {k:'復旧',r:'ふっきゅう',m:'restoration'},
  {k:'物質',r:'ぶっしつ',m:'substance'},
  {k:'ぶつぶつ',r:'ぶつぶつ',m:'grumble'},
  {k:'物理学',r:'ぶつりがく',m:'physics'},
  {k:'不適切',r:'ふてきせつ',m:'unsuitable'},
  {k:'不適当',r:'ふてきとう',m:'inappropriate'},
  {k:'ふと',r:'ふと',m:'suddenly'},
  {k:'部品',r:'ぶひん',m:'part'},
  {k:'吹雪',r:'ふぶき',m:'snowstorm'},
  {k:'不平',r:'ふへい',m:'complaint'},
  {k:'踏み切り',r:'ふみきり',m:'railway crossing'},
  {k:'振り返る',r:'ふりかえる',m:'look back'},
  {k:'振り向く',r:'ふりむく',m:'turn about'},
  {k:'不良品',r:'ふりょうひん',m:'defective item'},
  {k:'振る',r:'ふる',m:'wag, sprinkle, shake'},
  {k:'震える',r:'ふるえる',m:'tremble'},
  {k:'古新聞',r:'ふるしんぶん',m:'old newspaper'},
  {k:'触れる',r:'ふれる',m:'touch'},
  {k:'文学',r:'ぶんがく',m:'literature'},
  {k:'分野',r:'ぶんや',m:'area'},
  // へ
  {k:'平気',r:'へいき',m:'unconcerned, insensitive'},
  {k:'平野',r:'へいや',m:'plain'},
  {k:'へこむ',r:'へこむ',m:'deflate, lose heart'},
  {k:'別荘',r:'べっそう',m:'cottage, villa'},
  {k:'別に',r:'べつに',m:'(not) particularly'},
  {k:'ベテラン',r:'ベテラン',m:'veteran'},
  {k:'へとへと',r:'へとへと',m:'completely exhausted'},
  {k:'変更',r:'へんこう',m:'change'},
  {k:'弁護士',r:'べんごし',m:'lawyer'},
  {k:'返済',r:'へんさい',m:'repayment'},
  {k:'変動',r:'へんどう',m:'fluctuation'},
  {k:'返品',r:'へんぴん',m:'returned goods'},
  // ほ
  {k:'保育所',r:'ほいくじょ',m:'nursery school'},
  {k:'ほうき',r:'ほうき',m:'broom'},
  {k:'法事',r:'ほうじ',m:'memorial service'},
  {k:'報じる',r:'ほうじる',m:'report'},
  {k:'放送',r:'ほうそう',m:'broadcast'},
  {k:'包帯',r:'ほうたい',m:'bandage'},
  {k:'法廷',r:'ほうてい',m:'court'},
  {k:'報道',r:'ほうどう',m:'news report'},
  {k:'ボーナス',r:'ボーナス',m:'bonus'},
  {k:'豊富',r:'ほうふ',m:'abundance'},
  {k:'ぽかぽか',r:'ぽかぽか',m:'warm'},
  {k:'保険',r:'ほけん',m:'insurance'},
  {k:'保険金',r:'ほけんきん',m:'insurance money/payment'},
  {k:'保護',r:'ほご',m:'protect'},
  {k:'ほこり',r:'ほこり',m:'dust'},
  {k:'保証金',r:'ほしょうきん',m:'deposit'},
  {k:'干す',r:'ほす',m:'dry'},
  {k:'保存',r:'ほぞん',m:'saving'},
  {k:'保存料',r:'ほぞんりょう',m:'food preservative'},
  {k:'墓地',r:'ぼち',m:'cemetery'},
  {k:'仏',r:'ほとけ',m:'Buddha'},
  {k:'骨が折れる',r:'ほねがおれる',m:'require a lot of effort'},
  {k:'ほぼ',r:'ほぼ',m:'more or less'},
  {k:'ほほえみかける',r:'ほほえみかける',m:'smile (at someone)'},
  {k:'ほやほや',r:'ほやほや',m:'fresh'},
  {k:'滅びる',r:'ほろびる',m:'decline'},
  {k:'ぼろぼろ',r:'ぼろぼろ',m:'tattered, ragged'},
  {k:'本格的',r:'ほんかくてき',m:'full-scale, proper'},
  {k:'盆地',r:'ぼんち',m:'basin'},
  {k:'ほんの',r:'ほんの',m:'just'},
  {k:'ぼんやり',r:'ぼんやり',m:'indistinct, absentminded'},
  // ま
  {k:'参る',r:'まいる',m:'be overwhelmed by'},
  {k:'負かす',r:'まかす',m:'beat'},
  {k:'巻く',r:'まく',m:'roll'},
  {k:'幕',r:'まく',m:'curtain'},
  {k:'まく',r:'まく',m:'sow'},
  {k:'孫',r:'まご',m:'grandchild'},
  {k:'まさか',r:'まさか',m:'no way'},
  {k:'まさに',r:'まさに',m:'exactly, exactly right now'},
  {k:'まして',r:'まして',m:'much more'},
  {k:'マスコミ',r:'マスコミ',m:'mass communication'},
  {k:'ますます',r:'ますます',m:'more and more'},
  {k:'待ち合わせる',r:'まちあわせる',m:'arrange to meet'},
  {k:'真っ暗',r:'まっくら',m:'pitch dark'},
  {k:'まったく',r:'まったく',m:'(not) at all'},
  {k:'まとめる',r:'まとめる',m:'collect'},
  {k:'マナー',r:'マナー',m:'manner'},
  {k:'招く',r:'まねく',m:'invite, cause'},
  {k:'まぶしい',r:'まぶしい',m:'bright'},
  {k:'間もなく',r:'まもなく',m:'soon'},
  {k:'守る',r:'まもる',m:'keep, protect'},
  {k:'迷う',r:'まよう',m:'get lost'},
  {k:'丸まる',r:'まるまる',m:'curl up'},
  {k:'丸み',r:'まるみ',m:'roundness'},
  {k:'丸める',r:'まるめる',m:'roll up, round'},
  {k:'まれ',r:'まれ',m:'rare'},
  {k:'回る',r:'まわる',m:'go around'},
  {k:'万一',r:'まんいち',m:'by any chance'},
  {k:'万が一',r:'まんがいち',m:'by any chance'},
  {k:'満員',r:'まんいん',m:'full, crowded, packed'},
  // み
  {k:'見上げる',r:'みあげる',m:'look up'},
  {k:'見誤る',r:'みあやまる',m:'misjudge'},
  {k:'ミーティング',r:'ミーティング',m:'meeting'},
  {k:'見送る',r:'みおくる',m:'see off'},
  {k:'見下ろす',r:'みおろす',m:'look down'},
  {k:'見かけ',r:'みかけ',m:'appearance'},
  {k:'見かける',r:'みかける',m:'happen to see'},
  {k:'味方',r:'みかた',m:'ally, friend'},
  {k:'身が入る',r:'みがはいる',m:'concentrate on'},
  {k:'未完成',r:'みかんせい',m:'unfinished'},
  {k:'見事',r:'みごと',m:'brilliant'},
  {k:'未婚者',r:'みこんしゃ',m:'unmarried'},
  {k:'岬',r:'みさき',m:'cape'},
  {k:'ミシン',r:'ミシン',m:'sewing machine'},
  {k:'ミス',r:'ミス',m:'mistake'},
  {k:'湖',r:'みずうみ',m:'lake'},
  {k:'自ら',r:'みずから',m:'personally'},
  {k:'水玉模様',r:'みずたまもよう',m:'polka dot'},
  {k:'見出し',r:'みだし',m:'headline'},
  {k:'道沿い',r:'みちぞい',m:'along the road'},
  {k:'みっともない',r:'みっともない',m:'shameful'},
  {k:'見つめ合う',r:'みつめあう',m:'look at each other'},
  {k:'見つめ直す',r:'みつめなおす',m:'reconsider'},
  {k:'見つめる',r:'みつめる',m:'look at'},
  {k:'認める',r:'みとめる',m:'acknowledge'},
  {k:'見直す',r:'みなおす',m:'review, look again'},
  {k:'見習う',r:'みならう',m:'emulate'},
  {k:'見慣れる',r:'みなれる',m:'be familiar with'},
  {k:'身につける',r:'みにつける',m:'learn, cultivate'},
  {k:'実る',r:'みのる',m:'ripen'},
  {k:'未発表',r:'みはっぴょう',m:'unpublished'},
  {k:'見回る',r:'みまわる',m:'go/look around'},
  {k:'耳が痛い',r:'みみがいたい',m:'painful to hear'},
  {k:'耳が早い',r:'みみがはやい',m:'be the first to know something'},
  {k:'耳にする',r:'みみにする',m:'hear'},
  {k:'耳を貸す',r:'みみをかす',m:'listen to'},
  {k:'魅力的',r:'みりょくてき',m:'enchanting'},
  {k:'診る',r:'みる',m:'examine (medically)'},
  {k:'見分ける',r:'みわける',m:'distinguish'},
  // む
  {k:'向かう',r:'むかう',m:'head toward'},
  {k:'むかむか',r:'むかむか',m:'feel sick'},
  {k:'無気力',r:'むきりょく',m:'lethargic'},
  {k:'無視',r:'むし',m:'ignoring'},
  {k:'蒸し暑い',r:'むしあつい',m:'hot and humid'},
  {k:'虫の居所が悪い',r:'むしのいどころがわるい',m:'be in a bad mood'},
  {k:'むしろ',r:'むしろ',m:'rather'},
  {k:'蒸す',r:'むす',m:'steam'},
  {k:'結びつける',r:'むすびつける',m:'tie, fasten'},
  {k:'胸が一杯になる',r:'むねがいっぱいになる',m:'be overwhelmed with emotion'},
  {k:'胸に納める',r:'むねにおさめる',m:'keep to oneself (a secret, etc.)'},
  {k:'胸を打つ',r:'むねをうつ',m:'be moving'},
  {k:'胸を張る',r:'むねをはる',m:'proud'},
  {k:'無反応',r:'むはんのう',m:'no response'},
  {k:'群がる',r:'むらがる',m:'gather, huddle'},
  {k:'群れ',r:'むれ',m:'flock, herd'},
  // め
  {k:'名演技',r:'めいえんぎ',m:'fine performance'},
  {k:'名曲',r:'めいきょく',m:'famous piece of music'},
  {k:'名所',r:'めいしょ',m:'famous place'},
  {k:'名勝負',r:'めいしょうぶ',m:'good match'},
  {k:'名セリフ',r:'めいセリフ',m:'famous line'},
  {k:'迷惑メール対策',r:'めいわくメールたいさく',m:'measures against spam'},
  {k:'目上',r:'めうえ',m:'superior'},
  {k:'メール',r:'メール',m:'mail, email'},
  {k:'目がない',r:'めがない',m:'having a weakness for'},
  {k:'巡る',r:'めぐる',m:'go around'},
  {k:'目指す',r:'めざす',m:'aim at'},
  {k:'めざましい',r:'めざましい',m:'remarkable'},
  {k:'飯',r:'めし',m:'food, rice'},
  {k:'雌',r:'めす',m:'female (animal)'},
  {k:'めちゃくちゃ',r:'めちゃくちゃ',m:'complete mess'},
  {k:'目つき',r:'めつき',m:'look'},
  {k:'めっきり',r:'めっきり',m:'really, remarkably'},
  {k:'メッセージ',r:'メッセージ',m:'message'},
  {k:'めったに',r:'めったに',m:'rarely'},
  {k:'メディア',r:'メディア',m:'media'},
  {k:'目に浮かぶ',r:'めにうかぶ',m:'imagine, picture in one\'s mind'},
  {k:'目に付く',r:'めにつく',m:'be conspicuous'},
  {k:'めまい',r:'めまい',m:'dizziness'},
  {k:'目を付ける',r:'めをつける',m:'fix one\'s attention on'},
  {k:'目を通す',r:'めをとおす',m:'look over'},
  {k:'免許証',r:'めんきょしょう',m:'license'},
  {k:'免税店',r:'めんぜいてん',m:'duty-free shop'},
  {k:'面積',r:'めんせき',m:'area'},
  {k:'面倒',r:'めんどう',m:'trouble'},
  {k:'メンバー',r:'メンバー',m:'member'},
  // も
  {k:'もうかる',r:'もうかる',m:'be profitable, make a profit'},
  {k:'もうける',r:'もうける',m:'make a profit'},
  {k:'申し込み',r:'もうしこみ',m:'application'},
  {k:'申し込む',r:'もうしこむ',m:'apply'},
  {k:'申し訳ない',r:'もうしわけない',m:'I\'m sorry'},
  {k:'目次',r:'もくじ',m:'table of contents'},
  {k:'もしかしたら',r:'もしかしたら',m:'maybe'},
  {k:'もしかすると',r:'もしかすると',m:'maybe'},
  {k:'もたれる',r:'もたれる',m:'lean'},
  {k:'持ち上げる',r:'もちあげる',m:'lift'},
  {k:'持ち込む',r:'もちこむ',m:'bring/carry in'},
  {k:'持ち出す',r:'もちだす',m:'take out'},
  {k:'持ち直す',r:'もちなおす',m:'recover'},
  {k:'もてる',r:'もてる',m:'be popular with'},
  {k:'元',r:'もと',m:'original'},
  {k:'モニター',r:'モニター',m:'monitor'},
  {k:'モノレール',r:'モノレール',m:'monorail'},
  {k:'もはや',r:'もはや',m:'(not) any longer/more'},
  {k:'紅葉',r:'もみじ',m:'autumn color of leaves'},
  {k:'もむ',r:'もむ',m:'massage'},
  {k:'文句',r:'もんく',m:'complaint'},
  // や
  {k:'やかましい',r:'やかましい',m:'noisy'},
  {k:'焼き上がる',r:'やきあがる',m:'be baked'},
  {k:'焼き立て',r:'やきたて',m:'freshly baked/roasted'},
  {k:'役立つ',r:'やくだつ',m:'be useful'},
  {k:'役割',r:'やくわり',m:'role, function'},
  {k:'訳す',r:'やくす',m:'translate'},
  {k:'休み明け',r:'やすみあけ',m:'just after a holiday break'},
  {k:'厄介',r:'やっかい',m:'trouble'},
  {k:'薬局',r:'やっきょく',m:'pharmacy, chemist\'s'},
  {k:'雇う',r:'やとう',m:'hire'},
  {k:'野党',r:'やとう',m:'opposition (party)'},
  {k:'破る',r:'やぶる',m:'tear, break'},
  {k:'敗れる',r:'やぶれる',m:'be beaten/defeated'},
  {k:'やむをえず',r:'やむをえず',m:'unavoidably'},
  {k:'やむをえない',r:'やむをえない',m:'unavoidable'},
  {k:'やや',r:'やや',m:'a little'},
  // ゆ
  {k:'有害',r:'ゆうがい',m:'harmful'},
  {k:'夕刊',r:'ゆうかん',m:'evening newspaper'},
  {k:'夕暮れ時',r:'ゆうぐれどき',m:'dusk'},
  {k:'有効',r:'ゆうこう',m:'effective'},
  {k:'優先度',r:'ゆうせんど',m:'priority'},
  {k:'夕立',r:'ゆうだち',m:'shower'},
  {k:'有能',r:'ゆうのう',m:'competent'},
  {k:'有望',r:'ゆうぼう',m:'promising'},
  {k:'有名人',r:'ゆうめいじん',m:'famous person'},
  {k:'ユーモア',r:'ユーモア',m:'humor'},
  {k:'有利',r:'ゆうり',m:'advantageous'},
  {k:'有力',r:'ゆうりょく',m:'influential, powerful'},
  {k:'行方',r:'ゆくえ',m:'whereabouts'},
  {k:'ゆでる',r:'ゆでる',m:'boil'},
  {k:'湯飲み',r:'ゆのみ',m:'teacup'},
  {k:'許す',r:'ゆるす',m:'forgive'},
  // よ
  {k:'夜明け',r:'よあけ',m:'dawn'},
  {k:'酔い',r:'よい',m:'drunkenness'},
  {k:'酔う',r:'よう',m:'get drunk'},
  {k:'陽気',r:'ようき',m:'cheerful'},
  {k:'要求',r:'ようきゅう',m:'demand'},
  {k:'洋食',r:'ようしょく',m:'Western food'},
  {k:'幼稚園',r:'ようちえん',m:'kindergarten'},
  {k:'用途',r:'ようと',m:'(intended) use'},
  {k:'ようやく',r:'ようやく',m:'in the end'},
  {k:'要領',r:'ようりょう',m:'point, gist'},
  {k:'預金',r:'よきん',m:'saving, deposit'},
  {k:'余計',r:'よけい',m:'extra'},
  {k:'汚す',r:'よごす',m:'get dirty'},
  {k:'予算案',r:'よさんあん',m:'budget proposal'},
  {k:'寄せる',r:'よせる',m:'bring close to, send, have'},
  {k:'予想通り',r:'よそうどおり',m:'as expected'},
  {k:'酔っ払い',r:'よっぱらい',m:'drunkard'},
  {k:'よっぽど',r:'よっぽど',m:'exceedingly'},
  {k:'予定通り',r:'よていどおり',m:'as scheduled'},
  {k:'与党',r:'よとう',m:'ruling party'},
  {k:'夜中',r:'よなか',m:'middle of the night'},
  {k:'呼び出す',r:'よびだす',m:'call, page'},
  {k:'余分',r:'よぶん',m:'extra, surplus'},
  {k:'予防',r:'よぼう',m:'prevention'},
  {k:'予防法',r:'よぼうほう',m:'how to prevent'},
  {k:'よほど',r:'よほど',m:'exceedingly'},
  {k:'読み直す',r:'よみなおす',m:'reread'},
  {k:'弱気',r:'よわき',m:'coward'},
  {k:'弱まる',r:'よわまる',m:'weaken'},
  {k:'弱み',r:'よわみ',m:'weakness'},
  {k:'弱める',r:'よわめる',m:'weaken'},
  // ら
  {k:'ラッシュアワー',r:'ラッシュアワー',m:'rush-hour'},
  {k:'乱暴',r:'らんぼう',m:'rough, violent'},
  // り
  {k:'利害',r:'りがい',m:'interests'},
  {k:'陸',r:'りく',m:'land'},
  {k:'離婚',r:'りこん',m:'divorce'},
  {k:'リサイクル',r:'リサイクル',m:'recycle'},
  {k:'利子',r:'りし',m:'interest'},
  {k:'理想',r:'りそう',m:'ideal'},
  {k:'理想的',r:'りそうてき',m:'ideal'},
  {k:'利息',r:'りそく',m:'interest'},
  {k:'立体',r:'りったい',m:'solid'},
  {k:'料金',r:'りょうきん',m:'fee, charge'},
  {k:'両ひざ',r:'りょうひざ',m:'both knees'},
  {k:'両わき',r:'りょうわき',m:'both sides'},
  {k:'リラックス',r:'リラックス',m:'relax'},
  // れ
  {k:'礼儀',r:'れいぎ',m:'courtesy'},
  {k:'礼儀正しい',r:'れいぎただしい',m:'polite'},
  {k:'冷静',r:'れいせい',m:'calm'},
  {k:'レジャー',r:'レジャー',m:'leisure'},
  // ろ
  {k:'労働組合',r:'ろうどうくみあい',m:'labor union'},
  {k:'労働条件',r:'ろうどうじょうけん',m:'working conditions'},
  {k:'ローン',r:'ローン',m:'loan'},
  {k:'論文',r:'ろんぶん',m:'dissertation, essay'},
  // わ
  {k:'わがまま',r:'わがまま',m:'selfish'},
  {k:'わく',r:'わく',m:'spring out'},
  {k:'枠',r:'わく',m:'box'},
  {k:'わざと',r:'わざと',m:'on purpose'},
  {k:'わざわざ',r:'わざわざ',m:'bother/trouble (to do)'},
  {k:'和食',r:'わしょく',m:'Japanese food'},
  {k:'わずか',r:'わずか',m:'a few, a little, only'},
  {k:'綿',r:'わた',m:'cotton (plant)'},
  {k:'話題',r:'わだい',m:'topic'},
  {k:'和風',r:'わふう',m:'Japanese style'},
  {k:'笑いかける',r:'わらいかける',m:'smile, grin'},
  {k:'割り勘',r:'わりかん',m:'split/share the costs'},
  {k:'割り算',r:'わりざん',m:'division'},
  {k:'割と',r:'わりと',m:'comparatively'},
  {k:'割る',r:'わる',m:'divide'},
  {k:'湾',r:'わん',m:'bay'},
];
