const vocabulary = [
  {k:'あいかわらず',r:'あいかわらず',m:'as ever, as usual, the same'},
  {k:'アイデア',r:'アイデア',m:'idea'},
  {k:'あいまい',r:'あいまい',m:'vague, ambiguous'},
  {k:'遭う',r:'あう',m:'to meet, to encounter (undesirable nuance)'},
  {k:'扇ぐ',r:'あおぐ',m:'to fan, to flap'},
  {k:'青白い',r:'あおじろい',m:'pale, pallid'},
  {k:'あかんぼう',r:'あかんぼう',m:'baby'},
  {k:'明き',r:'あき',m:'room, time to spare, emptiness'},
  {k:'あきれる',r:'あきれる',m:'to be amazed, to be shocked'},
  {k:'アクセント',r:'アクセント',m:'accent'},
  {k:'あくび',r:'あくび',m:'yawn'},
  {k:'飽くまで',r:'あくまで',m:'to the end, to the last, stubbornly'},
  {k:'明け方',r:'あけがた',m:'dawn'},
  {k:'揚げる',r:'あげる',m:'to lift, to fry'},
  {k:'挙げる',r:'あげる',m:'to raise, to fly'},
  {k:'あげる',r:'やる',m:'to do for'},
  {k:'憧れる',r:'あこがれる',m:'to long for, to yearn after, to admire'},
  {k:'足跡',r:'あしあと',m:'footprints'},
  {k:'味わう',r:'あじわう',m:'to taste, to savor, to relish'},
  {k:'預かる',r:'あずかる',m:'to keep in custody, to receive on deposit, to take charge of'},
  {k:'暖まる',r:'あたたまる',m:'to warm up, to get warm'},
  {k:'暖める',r:'あたためる',m:'to warm, to heat'},
  {k:'あたりまえ',r:'あたりまえ',m:'usual, common, ordinary'},
  {k:'あちら',r:'あっち',m:'over there, that way'},
  {k:'あちらこちら',r:'あちらこちら',m:'here and there'},
  {k:'厚かましい',r:'あつかましい',m:'impudent, shameless, brazen'},
  {k:'圧縮',r:'あっしゅく',m:'compression, condensation, pressure'},
  {k:'宛名',r:'あてな',m:'address, direction'},
  {k:'あてはまる',r:'あてはまる',m:'to be applicable, to come under (a category), to fulfill'},
  {k:'あてはめる',r:'あてはめる',m:'to apply, to adapt'},
  {k:'暴れる',r:'あばれる',m:'to act violently, to rage, to struggle, to be riotous'},
  {k:'脂',r:'あぶら',m:'fat, tallow, lard'},
  {k:'あぶる',r:'あぶる',m:'to scorch'},
  {k:'あふれる',r:'あふれる',m:'to flood, to overflow, to brim over'},
  {k:'雨戸',r:'あまど',m:'sliding storm door'},
  {k:'甘やかす',r:'あまやかす',m:'to pamper, to spoil'},
  {k:'余る',r:'あまる',m:'to remain, to be left over, to be in excess, to be too many'},
  {k:'編物',r:'あみもの',m:'knitting, web'},
  {k:'編む',r:'あむ',m:'to knit'},
  {k:'危うい',r:'あやうい',m:'dangerous, critical, grave'},
  {k:'怪しい',r:'あやしい',m:'suspicious, dubious, doubtful'},
  {k:'荒い',r:'あらい',m:'rough, rude, wild'},
  {k:'粗い',r:'あらい',m:'coarse, rough'},
  {k:'あらすじ',r:'あらすじ',m:'outline, summary'},
  {k:'争う',r:'あらそう',m:'to dispute, to argue, to be at variance, to compete'},
  {k:'改めて',r:'あらためて',m:'another time, again, over again, anew, formally'},
  {k:'改める',r:'あらためる',m:'to change, to alter, to reform, to revise'},
  {k:'著す',r:'あらわす',m:'to write, to publish'},
  {k:'有難い',r:'ありがたい',m:'grateful, thankful, welcome, appreciated, evoking gratitude'},
  {k:'在る',r:'ある',m:'to live, to be'},
  {k:'あれこれ',r:'あれこれ',m:'one thing or another, this and that, this or that'},
  {k:'あわただしい',r:'あわただしい',m:'busy, hurried, confused, flurried'},
  {k:'あわてる',r:'あわてる',m:'to become confused'},
  {k:'安易',r:'あんい',m:'easy-going'},
  {k:'案外',r:'あんがい',m:'unexpectedly'},
  {k:'アンテナ',r:'アンテナ',m:'antenna'},
  {k:'言い出す',r:'いいだす',m:'to start talking, to speak, to tell, to propose, to suggest, to break the ice'},
  {k:'言い付ける',r:'いいつける',m:'to tell, to tell on (someone), to order'},
  {k:'意義',r:'いぎ',m:'meaning, significance'},
  {k:'生き生き',r:'いきいき',m:'vividly, lively'},
  {k:'いきなり',r:'いきなり',m:'abruptly, suddenly, all of a sudden, without warning'},
  {k:'育児',r:'いくじ',m:'childcare, nursing, upbringing'},
  {k:'幾分',r:'いくぶん',m:'somewhat'},
  {k:'生け花',r:'いけばな',m:'flower arrangement'},
  {k:'以後',r:'いご',m:'after this, from now on, hereafter, thereafter'},
  {k:'以降',r:'いこう',m:'on and after, hereafter, thereafter'},
  {k:'イコール',r:'イコール',m:'equal'},
  {k:'勇ましい',r:'いさましい',m:'brave, valiant, gallant, courageous'},
  {k:'衣食住',r:'いしょくじゅう',m:'necessities of life (food, clothing, etc.)'},
  {k:'意地悪',r:'いじわる',m:'malicious, ill-tempered, unkind'},
  {k:'いちいち',r:'いちいち',m:'one by one, separately'},
  {k:'一応',r:'いちおう',m:'once, tentatively, in outline, for the time being'},
  {k:'一段と',r:'いちだんと',m:'greater, more, further, still more'},
  {k:'一流',r:'いちりゅう',m:'first class, top grade, foremost, top-notch'},
  {k:'佚',r:'いつ',m:'be lost, peace, hide, mistake, beautiful, in turn'},
  {k:'一昨日',r:'いっさくじつ',m:'day before yesterday'},
  {k:'一昨年',r:'いっさくねん',m:'year before last'},
  {k:'一斉',r:'いっせい',m:'simultaneous, all at once'},
  {k:'一旦',r:'いったん',m:'once, for a moment, one morning, temporarily'},
  {k:'一定',r:'いってい',m:'fixed, settled, definite'},
  {k:'いってらっしゃい',r:'いってらっしゃい',m:'have a good day, take care'},
  {k:'いってまいります',r:'いってまいります',m:'good bye, I\'m leaving'},
  {k:'いつのまにか',r:'いつのまにか',m:'before one knows, unnoticed, unawares'},
  {k:'移転',r:'いてん',m:'moving, transfer, demise'},
  {k:'井戸',r:'いど',m:'water well'},
  {k:'緯度',r:'いど',m:'latitude (nav.)'},
  {k:'従姉妹',r:'いとこ',m:'cousin (female)'},
  {k:'威張る',r:'いばる',m:'to be proud, to swagger'},
  {k:'嫌がる',r:'いやがる',m:'to hate, to dislike'},
  {k:'いよいよ',r:'いよいよ',m:'more and more, all the more, increasingly, at last, beyond doubt'},
  {k:'煎る',r:'いる',m:'to parch, to fry'},
  {k:'炒る',r:'いる',m:'to fry, to broil'},
  {k:'入れ物',r:'いれもの',m:'container, case, receptacle'},
  {k:'インキ',r:'インキ',m:'ink'},
  {k:'インタビュー',r:'インタビュー',m:'interview'},
  {k:'引力',r:'いんりょく',m:'gravity'},
  {k:'ウーマン',r:'ウーマン',m:'woman'},
  {k:'ウール',r:'ウール',m:'wool'},
  {k:'ウエートレス',r:'ウエートレス',m:'waitress'},
  {k:'植木',r:'うえき',m:'garden shrubs, trees, potted plant'},
  {k:'飢える',r:'うえる',m:'to starve'},
  {k:'浮ぶ',r:'うかぶ',m:'to float, to rise to surface, to come to mind'},
  {k:'浮かべる',r:'うかべる',m:'to float, to express, to look (sad, glad)'},
  {k:'浮く',r:'うく',m:'to float, to become merry, to become loose'},
  {k:'承る',r:'うけたまわる',m:'to hear, to be told, to know'},
  {k:'受取',r:'うけとり',m:'receipt'},
  {k:'受け持つ',r:'うけもつ',m:'to take (be in) charge of'},
  {k:'薄暗い',r:'うすぐらい',m:'dim, gloomy'},
  {k:'薄める',r:'うすめる',m:'to dilute, to water down'},
  {k:'打合せ',r:'うちあわせ',m:'business meeting, previous arrangement, appointment'},
  {k:'打ち消す',r:'うちけす',m:'to deny, to negate, to contradict'},
  {k:'討つ',r:'うつ',m:'to attack, to avenge'},
  {k:'うっかり',r:'うっかり',m:'carelessly, thoughtlessly, inadvertently'},
  {k:'映す',r:'うつす',m:'to project, to reflect, to cast (shadow)'},
  {k:'写る',r:'うつる',m:'to be photographed, to be projected'},
  {k:'映る',r:'うつる',m:'to be reflected, to harmonize with, to come out (photo)'},
  {k:'うどん',r:'うどん',m:'noodles (Japanese)'},
  {k:'有無',r:'うむ',m:'yes or no, existence, presence or absence marker'},
  {k:'埋める',r:'うめる',m:'to bury, to fill up, to fill (a seat, a vacant position)'},
  {k:'敬う',r:'うやまう',m:'to show respect, to honor'},
  {k:'裏返す',r:'うらがえす',m:'to turn inside out, to turn (something) over'},
  {k:'裏口',r:'うらぐち',m:'backdoor, rear entrance'},
  {k:'占う',r:'うらなう',m:'to forecast, to predict'},
  {k:'恨み',r:'うらみ',m:'resentment'},
  {k:'恨む',r:'うらむ',m:'to curse, to feel bitter'},
  {k:'羨ましい',r:'うらやましい',m:'envious, enviable'},
  {k:'羨む',r:'うらやむ',m:'to envy'},
  {k:'売上',r:'うりあげ',m:'amount sold, proceeds'},
  {k:'売り切れ',r:'うりきれ',m:'sold-out'},
  {k:'売り切れる',r:'うりきれる',m:'to be sold out'},
  {k:'売行き',r:'うれゆき',m:'sales'},
  {k:'うろうろ',r:'うろうろ',m:'loitering, aimless wandering'},
  {k:'運河',r:'うんが',m:'canal, waterway'},
  {k:'うんと',r:'うんと',m:'a great deal, very much'},
  {k:'英文',r:'えいぶん',m:'sentence in English'},
  {k:'英和',r:'えいわ',m:'English-Japanese (e.g. dictionary)'},
  {k:'ええと',r:'ええと',m:'let me see, well, er'},
  {k:'液体',r:'えきたい',m:'liquid, fluid'},
  {k:'エチケット',r:'エチケット',m:'etiquette'},
  {k:'絵の具',r:'えのぐ',m:'colors, paints'},
  {k:'エプロン',r:'エプロン',m:'apron'},
  {k:'偉い',r:'えらい',m:'great, celebrated, eminent, terrible, awful, famous, remarkable, excellent'},
  {k:'宴会',r:'えんかい',m:'party, banquet'},
  {k:'園芸',r:'えんげい',m:'horticulture, gardening'},
  {k:'演劇',r:'えんげき',m:'play (theatrical)'},
  {k:'円周',r:'えんしゅう',m:'circumference'},
  {k:'遠足',r:'えんそく',m:'trip, hike, picnic'},
  {k:'延長',r:'えんちょう',m:'extension, elongation, prolongation, lengthening'},
  {k:'煙突',r:'えんとつ',m:'chimney'},
  {k:'追い掛ける',r:'おいかける',m:'to chase or run after someone, to run down, to pursue'},
  {k:'追い越す',r:'おいこす',m:'to pass (e.g. car), to outdistance, to outstrip'},
  {k:'オイル',r:'オイル',m:'oil, engine oil, kerosene'},
  {k:'応援',r:'おうえん',m:'aid, assistance, help, reinforcement'},
  {k:'王女',r:'おうじょ',m:'princess'},
  {k:'応ずる',r:'おうずる',m:'to answer, to respond, to meet, to satisfy, to accept'},
  {k:'応接',r:'おうせつ',m:'reception'},
  {k:'応対',r:'おうたい',m:'receiving, dealing with'},
  {k:'往復',r:'おうふく',m:'round trip, coming and going, return ticket'},
  {k:'欧米',r:'おうべい',m:'Europe and America, the West'},
  {k:'応用',r:'おうよう',m:'application, put to practical use'},
  {k:'オーケストラ',r:'オーケストラ',m:'orchestra'},
  {k:'おおざっぱ',r:'おおざっぱ',m:'rough (not precise), broad, sketchy'},
  {k:'大通り',r:'おおどおり',m:'main street'},
  {k:'オートメーション',r:'オートメーション',m:'automation'},
  {k:'オーバーコート',r:'オーバーコート',m:'overcoat'},
  {k:'大凡',r:'おおよそ',m:'about, roughly, as a rule, approximately'},
  {k:'お帰り',r:'おかえり',m:'return, welcome'},
  {k:'おかけください',r:'おかけください',m:'please take a seat'},
  {k:'おかげさまで',r:'おかげさまで',m:'thanks to god, thanks to you'},
  {k:'おかず',r:'おかず',m:'side dish, accompaniment for rice dishes'},
  {k:'拝む',r:'おがむ',m:'to worship, to beg, to make a supplication'},
  {k:'お代わり',r:'おかわり',m:'second helping, another cup'},
  {k:'補う',r:'おぎなう',m:'to compensate for'},
  {k:'おきのどくに',r:'おきのどくに',m:'my condolences'},
  {k:'屋外',r:'おくがい',m:'outdoors'},
  {k:'おくさん',r:'おくさん',m:'wife, your wife, madam'},
  {k:'送り仮名',r:'おくりがな',m:'part of word written in kana'},
  {k:'おげんきで',r:'おげんきで',m:'take care, goodbye'},
  {k:'怠る',r:'おこたる',m:'to neglect, to be off guard, to be feeling better'},
  {k:'押える',r:'おさえる',m:'to stop, to restrain, to seize, to repress, to suppress, to press down'},
  {k:'おさきに',r:'おさきに',m:'before, ahead, previously'},
  {k:'納める',r:'おさめる',m:'to obtain, to reap, to pay, to supply, to accept'},
  {k:'治める',r:'おさめる',m:'to govern, to manage, to subdue'},
  {k:'惜しい',r:'おしい',m:'regrettable, disappointing, precious'},
  {k:'御辞儀',r:'おじぎ',m:'bow'},
  {k:'伯父さん',r:'おじさん',m:'middle-aged gentleman, uncle'},
  {k:'小父さん',r:'おじさん',m:'middle-aged gentleman, uncle'},
  {k:'叔父さん',r:'おじさん',m:'middle-aged gentleman, uncle'},
  {k:'おしゃれ',r:'おしゃれ',m:'smartly dressed, fashion-conscious'},
  {k:'おじゃまします',r:'おじゃまします',m:'excuse me for disturbing you'},
  {k:'教わる',r:'おそわる',m:'to be taught'},
  {k:'おだいじに',r:'おだいじに',m:'take care of yourself'},
  {k:'落着く',r:'おちつく',m:'to calm down, to settle down'},
  {k:'御手洗',r:'おてあらい',m:'font of purifying water placed at entrance of shrine'},
  {k:'お出掛け',r:'おでかけ',m:'a polite term for going out or leaving'},
  {k:'お手伝いさん',r:'おてつだいさん',m:'maid'},
  {k:'おどかす',r:'おどかす',m:'to threaten, to coerce'},
  {k:'落し物',r:'おとしもの',m:'lost property'},
  {k:'おととい',r:'おととい',m:'day before yesterday'},
  {k:'おととし',r:'おととし',m:'year before last'},
  {k:'おとなしい',r:'おとなしい',m:'obedient, docile, quiet'},
  {k:'驚かす',r:'おどろかす',m:'to surprise, to frighten, to create a stir'},
  {k:'おねがいします',r:'おねがいします',m:'please'},
  {k:'各々',r:'おのおの',m:'each, every, either, respectively, severally'},
  {k:'伯母さん',r:'おばさん',m:'aunt'},
  {k:'叔母さん',r:'おばさん',m:'aunt, middle-aged lady'},
  {k:'おはよう',r:'おはよう',m:'good morning'},
  {k:'お参り',r:'おまいり',m:'worship, shrine visit'},
  {k:'おまたせしました',r:'おまたせしました',m:'sorry to have kept you waiting'},
  {k:'おまちください',r:'おまちください',m:'please wait a moment'},
  {k:'おまちどおさま',r:'おまちどおさま',m:'sorry to have kept you waiting'},
  {k:'おめでたい',r:'おめでたい',m:'happy event, matter for congratulation, auspicious event, pregnancy'},
  {k:'思い掛けない',r:'おもいがけない',m:'unexpected, casual'},
  {k:'思い込む',r:'おもいこむ',m:'to be under impression that, to be convinced that'},
  {k:'思いっ切り',r:'おもいっきり',m:'with all one\'s might, to one\'s heart\'s content'},
  {k:'思い付く',r:'おもいつく',m:'to think of, to hit upon'},
  {k:'重たい',r:'おもたい',m:'heavy, massive, serious'},
  {k:'おやすみ',r:'おやすみ',m:'holiday, absence, rest, good night'},
  {k:'おやつ',r:'おやつ',m:'between meal snack, afternoon refreshment'},
  {k:'親指',r:'おやゆび',m:'thumb'},
  {k:'オルガン',r:'オルガン',m:'organ'},
  {k:'卸す',r:'おろす',m:'to sell wholesale, grated (vegetables)'},
  {k:'恩恵',r:'おんけい',m:'grace, favor, blessing, benefit'},
  {k:'温室',r:'おんしつ',m:'greenhouse'},
  {k:'温泉',r:'おんせん',m:'spa, hot spring, onsen'},
  {k:'温帯',r:'おんたい',m:'temperate zone'},
  {k:'御中',r:'おんちゅう',m:'and Company, Messrs.'},
  {k:'女の人',r:'おんなのひと',m:'woman'},
  {k:'蚊',r:'か',m:'mosquito'},
  {k:'カーブ',r:'カーブ',m:'curve, curve ball (baseball)'},
  {k:'貝',r:'かい',m:'shell, shellfish'},
  {k:'開会',r:'かいかい',m:'opening of a meeting'},
  {k:'会館',r:'かいかん',m:'meeting hall, assembly hall'},
  {k:'改札',r:'かいさつ',m:'examination of tickets'},
  {k:'解散',r:'かいさん',m:'breakup, dissolution'},
  {k:'海水浴',r:'かいすいよく',m:'sea bathing, seawater bath'},
  {k:'回数',r:'かいすう',m:'number of times, frequency'},
  {k:'回数券',r:'かいすうけん',m:'book of tickets'},
  {k:'改正',r:'かいせい',m:'revision, amendment, alteration'},
  {k:'快晴',r:'かいせい',m:'good weather'},
  {k:'解説',r:'かいせつ',m:'explanation, commentary'},
  {k:'改造',r:'かいぞう',m:'remodeling, modding'},
  {k:'開通',r:'かいつう',m:'opening, open'},
  {k:'回転',r:'かいてん',m:'rotation, revolution, turning'},
  {k:'解答',r:'かいとう',m:'answer, solution'},
  {k:'回答',r:'かいとう',m:'reply, answer'},
  {k:'外部',r:'がいぶ',m:'the outside, external'},
  {k:'解放',r:'かいほう',m:'release, liberation, emancipation'},
  {k:'開放',r:'かいほう',m:'open, throw open, liberalization'},
  {k:'海洋',r:'かいよう',m:'ocean'},
  {k:'概論',r:'がいろん',m:'intro, outline, general remarks'},
  {k:'帰す',r:'かえす',m:'to send back'},
  {k:'却って',r:'かえって',m:'on the contrary, rather, all the more, instead'},
  {k:'代える',r:'かえる',m:'to exchange, to interchange, to substitute, to replace'},
  {k:'反る',r:'かえる',m:'to warp, to be warped, to curve'},
  {k:'家屋',r:'かおく',m:'house, building'},
  {k:'係わる',r:'かかわる',m:'to concern oneself in, to have to do with, to affect, to influence'},
  {k:'書留',r:'かきとめ',m:'writing down, putting on record, recording, registration (of mail)'},
  {k:'書取',r:'かきとり',m:'dictation'},
  {k:'垣根',r:'かきね',m:'hedge'},
  {k:'掻く',r:'かく',m:'to scratch, to perspire'},
  {k:'嗅ぐ',r:'かぐ',m:'to sniff, to smell'},
  {k:'架空',r:'かくう',m:'aerial, overhead, fiction, fanciful'},
  {k:'各自',r:'かくじ',m:'individual, each'},
  {k:'拡充',r:'かくじゅう',m:'expansion'},
  {k:'学術',r:'がくじゅつ',m:'science, learning, scholarship'},
  {k:'各地',r:'かくち',m:'every place, various places'},
  {k:'拡張',r:'かくちょう',m:'expansion, extension, enlargement'},
  {k:'角度',r:'かくど',m:'angle'},
  {k:'学年',r:'がくねん',m:'year in school, grade in school'},
  {k:'学部',r:'がくぶ',m:'department of a university, undergraduate'},
  {k:'格別',r:'かくべつ',m:'exceptional'},
  {k:'確率',r:'かくりつ',m:'probability'},
  {k:'学力',r:'がくりょく',m:'scholarship, knowledge, literary ability'},
  {k:'掛け算',r:'かけざん',m:'multiplication'},
  {k:'可決',r:'かけつ',m:'approval, adoption (e.g. motion, bill), passage'},
  {k:'火口',r:'かこう',m:'a burner, origin of a fire'},
  {k:'下降',r:'かこう',m:'downward, descent, fall, drop, subsidence'},
  {k:'重なる',r:'かさなる',m:'to be piled up, lie on top of one another, overlap each other'},
  {k:'重ねる',r:'かさねる',m:'to pile up, to put something on another, to heap up, to add, to repeat'},
  {k:'飾り',r:'かざり',m:'decoration'},
  {k:'火山',r:'かざん',m:'volcano'},
  {k:'かしこまりました',r:'かしこまりました',m:'certainly!'},
  {k:'貸し出し',r:'かしだし',m:'lending, loaning'},
  {k:'過失',r:'かしつ',m:'error, blunder, accident'},
  {k:'果実',r:'かじつ',m:'fruit, nut, berry'},
  {k:'貸間',r:'かしま',m:'room to let'},
  {k:'貸家',r:'かしや',m:'house for rent'},
  {k:'個所',r:'かしょ',m:'passage, place, point, part'},
  {k:'過剰',r:'かじょう',m:'excess, over'},
  {k:'かじる',r:'かじる',m:'to chew, to bite (at), to gnaw, to nibble'},
  {k:'課税',r:'かぜい',m:'taxation'},
  {k:'下線',r:'かせん',m:'underline, underscore'},
  {k:'カセット',r:'カセット',m:'cassette (tape)'},
  {k:'加速',r:'かそく',m:'acceleration'},
  {k:'加速度',r:'かそくど',m:'acceleration'},
  {k:'固い',r:'かたい',m:'stubborn, firm (not viscous or easily moved)'},
  {k:'堅い',r:'かたい',m:'hard (esp. wood), steadfast, honorable, stuffy writing'},
  {k:'片仮名',r:'かたかな',m:'katakana'},
  {k:'片付く',r:'かたづく',m:'to put in order, to dispose of, to solve'},
  {k:'塊',r:'かたまり',m:'lump, mass, clod, cluster'},
  {k:'固まる',r:'かたまる',m:'to harden, to solidify, to become firm, to become certain'},
  {k:'片道',r:'かたみち',m:'one-way (trip)'},
  {k:'傾く',r:'かたむく',m:'to incline toward, to slant, to lurch'},
  {k:'片寄る',r:'かたよる',m:'to be one-sided, to incline, to be partial'},
  {k:'学科',r:'がっか',m:'study subject, course of study'},
  {k:'学会',r:'がっかい',m:'scientific society, academic meeting'},
  {k:'楽器',r:'がっき',m:'musical instrument'},
  {k:'学級',r:'がっきゅう',m:'grade in school'},
  {k:'担ぐ',r:'かつぐ',m:'to shoulder, to carry on shoulder'},
  {k:'括弧',r:'かっこ',m:'parenthesis, brackets'},
  {k:'活字',r:'かつじ',m:'printing type'},
  {k:'活躍',r:'かつやく',m:'activity'},
  {k:'活力',r:'かつりょく',m:'vitality, energy'},
  {k:'仮定',r:'かてい',m:'assumption, supposition, hypothesis'},
  {k:'過程',r:'かてい',m:'process'},
  {k:'課程',r:'かてい',m:'course, curriculum'},
  {k:'仮名',r:'かな',m:'alias, pseudonym, pen name'},
  {k:'仮名遣い',r:'かなづかい',m:'kana orthography, syllabary spelling'},
  {k:'鐘',r:'かね',m:'bell, chime'},
  {k:'加熱',r:'かねつ',m:'heating'},
  {k:'兼ねる',r:'かねる',m:'to hold (position), to serve, to be unable'},
  {k:'カバー',r:'カバー',m:'cover (ex. book)'},
  {k:'過半数',r:'かはんすう',m:'majority'},
  {k:'被せる',r:'かぶせる',m:'to cover (with something)'},
  {k:'佂',r:'かま',m:'iron pot, kettle'},
  {k:'紙屑',r:'かみくず',m:'wastepaper'},
  {k:'神様',r:'かみさま',m:'god'},
  {k:'剃刀',r:'かみそり',m:'razor'},
  {k:'ガム',r:'ガム',m:'chewing gum'},
  {k:'貨物',r:'かもつ',m:'cargo, freight'},
  {k:'かゆい',r:'かゆい',m:'itchy, itching'},
  {k:'歌謡',r:'かよう',m:'song, ballad'},
  {k:'殻',r:'から',m:'shell, husk, hull, chaff'},
  {k:'カラー',r:'カラー',m:'collar, color'},
  {k:'からかう',r:'からかう',m:'to ridicule, to tease, to banter with, to make fun of'},
  {k:'空っぽ',r:'からっぽ',m:'empty, vacant, hollow'},
  {k:'かるた',r:'かるた',m:'playing cards'},
  {k:'枯れる',r:'かれる',m:'to wither, to die (plant), to be blasted (plant)'},
  {k:'カロリー',r:'カロリー',m:'calorie'},
  {k:'かわいがる',r:'かわいがる',m:'to love, to be affectionate'},
  {k:'乾かす',r:'かわかす',m:'to dry (clothes, etc.), to desiccate'},
  {k:'渇く',r:'かわく',m:'to be thirsty'},
  {k:'為替',r:'かわせ',m:'money order, exchange'},
  {k:'瓦',r:'かわら',m:'roof tile'},
  {k:'代る',r:'かわる',m:'to take the place of, to relieve, to be substituted for'},
  {k:'間隔',r:'かんかく',m:'space, interval'},
  {k:'換気',r:'かんき',m:'ventilation'},
  {k:'感激',r:'かんげき',m:'deep emotion, impression, inspiration'},
  {k:'関西',r:'かんさい',m:'Kansai region (surrounding Kyoto and Osaka)'},
  {k:'鑑賞',r:'かんしょう',m:'appreciation'},
  {k:'感ずる',r:'かんずる',m:'to feel, to sense'},
  {k:'間接',r:'かんせつ',m:'indirection, indirectness'},
  {k:'乾燥',r:'かんそう',m:'dry, arid, insipid, dehydrated'},
  {k:'感想',r:'かんそう',m:'impressions, thoughts'},
  {k:'観測',r:'かんそく',m:'observation'},
  {k:'寒帯',r:'かんたい',m:'frigid zone'},
  {k:'官庁',r:'かんちょう',m:'government office, authorities'},
  {k:'勘違い',r:'かんちがい',m:'misunderstanding, wrong guess'},
  {k:'缶詰',r:'かんづめ',m:'packing (in cans), canning, canned goods, tin can'},
  {k:'乾電池',r:'かんでんち',m:'dry cell, battery'},
  {k:'関東',r:'かんとう',m:'Kanto region (surrounding Tokyo)'},
  {k:'観念',r:'かんねん',m:'idea, notion, conception, sense (e.g. of duty)'},
  {k:'乾杯',r:'かんぱい',m:'toast (drink)'},
  {k:'看板',r:'かんばん',m:'sign, signboard, doorplate, poster'},
  {k:'看病',r:'かんびょう',m:'nursing (a patient)'},
  {k:'冠',r:'かんむり',m:'crown, diadem, first, best'},
  {k:'漢和',r:'かんわ',m:'Chinese Character-Japanese (e.g. dictionary)'},
  {k:'気圧',r:'きあつ',m:'atmospheric pressure'},
  {k:'器械',r:'きかい',m:'instrument'},
  {k:'着替え',r:'きがえ',m:'changing clothes, change of clothes'},
  {k:'機関車',r:'きかんしゃ',m:'locomotive, engine'},
  {k:'飢饉',r:'ききん',m:'famine'},
  {k:'器具',r:'きぐ',m:'utensil'},
  {k:'期限',r:'きげん',m:'term, period'},
  {k:'記号',r:'きごう',m:'symbol, code'},
  {k:'刻む',r:'きざむ',m:'to mince, to carve, to engrave'},
  {k:'儀式',r:'ぎしき',m:'ceremony, rite, ritual, service'},
  {k:'基準',r:'きじゅん',m:'standard, basis, criteria, norm'},
  {k:'規準',r:'きじゅん',m:'standard, basis, criteria, norm'},
  {k:'起床',r:'きしょう',m:'rising, getting out of bed'},
  {k:'着せる',r:'きせる',m:'to put on clothes'},
  {k:'基礎',r:'きそ',m:'foundation, basis'},
  {k:'気体',r:'きたい',m:'vapor, gas'},
  {k:'基地',r:'きち',m:'base'},
  {k:'きっかけ',r:'きっかけ',m:'chance, start, cue, excuse'},
  {k:'ぎっしり',r:'ぎっしり',m:'tightly, fully'},
  {k:'基盤',r:'きばん',m:'foundation, basis'},
  {k:'客席',r:'きゃくせき',m:'guest seating'},
  {k:'客間',r:'きゃくま',m:'parlor, guest room'},
  {k:'ギャング',r:'ギャング',m:'gang'},
  {k:'キャンパス',r:'キャンパス',m:'campus'},
  {k:'休業',r:'きゅうぎょう',m:'closed (e.g. store), business suspended, shutdown, holiday'},
  {k:'休講',r:'きゅうこう',m:'lecture cancelled'},
  {k:'休息',r:'きゅうそく',m:'rest, relief, relaxation'},
  {k:'給与',r:'きゅうよ',m:'allowance, grant, supply'},
  {k:'休養',r:'きゅうよう',m:'rest, break, recreation'},
  {k:'清い',r:'きよい',m:'clear, pure, noble'},
  {k:'強化',r:'きょうか',m:'strengthen, intensify, reinforce, solidify'},
  {k:'境界',r:'きょうかい',m:'boundary'},
  {k:'行事',r:'ぎょうじ',m:'event, function'},
  {k:'恐縮',r:'きょうしゅく',m:'shame, very kind of you, sorry to trouble'},
  {k:'教養',r:'きょうよう',m:'culture, education, refinement, cultivation'},
  {k:'行列',r:'ぎょうれつ',m:'line, procession, matrix (math)'},
  {k:'漁業',r:'ぎょぎょう',m:'fishing (industry)'},
  {k:'曲線',r:'きょくせん',m:'curve'},
  {k:'規律',r:'きりつ',m:'order, rules, law'},
  {k:'斬る',r:'きる',m:'to behead, to murder'},
  {k:'気を付ける',r:'きをつける',m:'to be careful, to pay attention, to take care'},
  {k:'金魚',r:'きんぎょ',m:'goldfish'},
  {k:'区域',r:'くいき',m:'limits, boundary, domain, zone, sphere, territory'},
  {k:'偶数',r:'ぐうすう',m:'even number'},
  {k:'空想',r:'くうそう',m:'daydream, fantasy, fancy, vision'},
  {k:'空中',r:'くうちゅう',m:'sky, air'},
  {k:'クーラー',r:'クーラー',m:'cooler, air conditioner'},
  {k:'釘',r:'くぎ',m:'nail'},
  {k:'区切る',r:'くぎる',m:'to punctuate, to cut off, to mark off, to stop, to put an end to'},
  {k:'櫛',r:'くし',m:'comb'},
  {k:'くしゃみ',r:'くしゃみ',m:'sneeze'},
  {k:'苦情',r:'くじょう',m:'complaint, troubles, objection'},
  {k:'苦心',r:'くしん',m:'pain, trouble'},
  {k:'屑',r:'くず',m:'waste, scrap'},
  {k:'崩す',r:'くずす',m:'to destroy, to pull down, to make change (money)'},
  {k:'薬指',r:'くすりゆび',m:'ring finger'},
  {k:'崩れる',r:'くずれる',m:'to collapse, to crumble'},
  {k:'砕く',r:'くだく',m:'to break, to smash'},
  {k:'砕ける',r:'くだける',m:'to break, to be broken'},
  {k:'くたびれる',r:'くたびれる',m:'to get tired, to wear out'},
  {k:'くだらない',r:'くだらない',m:'good-for-nothing, stupid, trivial, worthless'},
  {k:'下る',r:'くだる',m:'to get down, to descend'},
  {k:'唇',r:'くちびる',m:'lips'},
  {k:'口紅',r:'くちべに',m:'lipstick'},
  {k:'くっつく',r:'くっつく',m:'to adhere to, to keep close to'},
  {k:'くっつける',r:'くっつける',m:'to attach'},
  {k:'くどい',r:'くどい',m:'verbose, importunate, heavy (taste)'},
  {k:'句読点',r:'くとうてん',m:'punctuation marks'},
  {k:'配る',r:'くばる',m:'to distribute, to deliver'},
  {k:'工夫',r:'くふう',m:'laborer, worker'},
  {k:'区分',r:'くぶん',m:'division, section, classification'},
  {k:'組合せ',r:'くみあわせ',m:'combination'},
  {k:'組み立てる',r:'くみたてる',m:'to assemble, to set up, to construct'},
  {k:'汲む',r:'くむ',m:'to draw (water), to dip, to scoop, to pump'},
  {k:'酌む',r:'くむ',m:'to serve sake'},
  {k:'悔しい',r:'くやしい',m:'regrettable, mortifying, vexing'},
  {k:'悔やむ',r:'くやむ',m:'to mourn'},
  {k:'クリーニング',r:'クリーニング',m:'cleaning, dry cleaning, laundry service'},
  {k:'くるむ',r:'くるむ',m:'to be engulfed in, to be enveloped by, to wrap up'},
  {k:'くれぐれも',r:'くれぐれも',m:'repeatedly, sincerely, earnestly'},
  {k:'咥える',r:'くわえる',m:'hold between one\'s teeth (e.g. a cigarette)'},
  {k:'郡',r:'ぐん',m:'country, district'},
  {k:'稽古',r:'けいこ',m:'practice, training, study'},
  {k:'敬語',r:'けいご',m:'honorific, term of respect'},
  {k:'蛍光灯',r:'けいこうとう',m:'fluorescent lamp, person who is slow to react'},
  {k:'形式',r:'けいしき',m:'form, formality, format, math expression'},
  {k:'継続',r:'けいぞく',m:'continuation'},
  {k:'毛糸',r:'けいと',m:'knitting wool'},
  {k:'経度',r:'けいど',m:'longitude'},
  {k:'系統',r:'けいとう',m:'system, family line, geological formation'},
  {k:'芸能',r:'げいのう',m:'public entertainment, accomplishments, attainments'},
  {k:'競馬',r:'けいば',m:'horse racing'},
  {k:'警備',r:'けいび',m:'defense, guard, policing, security'},
  {k:'形容詞',r:'けいようし',m:'true adjective'},
  {k:'形容動詞',r:'けいようどうし',m:'adjectival noun, quasi-adjective'},
  {k:'外科',r:'げか',m:'surgical department'},
  {k:'毛皮',r:'けがわ',m:'fur, skin, pelt'},
  {k:'激増',r:'げきぞう',m:'sudden increase'},
  {k:'下車',r:'げしゃ',m:'alighting, getting off'},
  {k:'下旬',r:'げじゅん',m:'last third of month'},
  {k:'下水',r:'げすい',m:'drainage, sewage, ditch, gutter, sewerage'},
  {k:'削る',r:'けずる',m:'to cut down little by little, to take a percentage'},
  {k:'桁',r:'けた',m:'column, beam, digit'},
  {k:'下駄',r:'げた',m:'geta (Japanese footwear), wooden clogs'},
  {k:'血圧',r:'けつあつ',m:'blood pressure'},
  {k:'血液',r:'けつえき',m:'blood'},
  {k:'月給',r:'げっきゅう',m:'monthly salary'},
  {k:'傑作',r:'けっさく',m:'masterpiece, best work, boner, blunder'},
  {k:'月末',r:'げつまつ',m:'end of the month'},
  {k:'気配',r:'けはい',m:'indication, market trend, worry'},
  {k:'下品',r:'げひん',m:'vulgarity, meanness, indecency, coarseness'},
  {k:'煙い',r:'けむい',m:'smoky'},
  {k:'蹴る',r:'ける',m:'to kick'},
  {k:'けれど',r:'けれど',m:'but, however'},
  {k:'険しい',r:'けわしい',m:'inaccessible place, sharp eyes'},
  {k:'見学',r:'けんがく',m:'inspection, study by observation, field trip'},
  {k:'謙虚',r:'けんきょ',m:'modesty, humility'},
  {k:'原稿',r:'げんこう',m:'manuscript, copy'},
  {k:'原産',r:'げんさん',m:'place of origin, habitat'},
  {k:'原始',r:'げんし',m:'origin, primeval'},
  {k:'研修',r:'けんしゅう',m:'training'},
  {k:'厳重',r:'げんじゅう',m:'strict, rigor, severe, firm'},
  {k:'謙遜',r:'けんそん',m:'humble, humility, modesty'},
  {k:'県庁',r:'けんちょう',m:'prefectural office'},
  {k:'限度',r:'げんど',m:'limit, bounds'},
  {k:'現に',r:'げんに',m:'actually, really'},
  {k:'顕微鏡',r:'けんびきょう',m:'microscope'},
  {k:'原理',r:'げんり',m:'principle, theory, fundamental truth'},
  {k:'原料',r:'げんりょう',m:'raw materials'},
  {k:'碁',r:'ご',m:'Go (board game of capturing territory)'},
  {k:'恋しい',r:'こいしい',m:'dear, beloved, darling, yearned for'},
  {k:'請う',r:'こう',m:'to ask, to request'},
  {k:'工員',r:'こういん',m:'factory worker'},
  {k:'強引',r:'ごういん',m:'overbearing, coercive, pushy, forcible, high-handed'},
  {k:'公害',r:'こうがい',m:'public nuisance, pollution'},
  {k:'高級',r:'こうきゅう',m:'high class, high grade'},
  {k:'公共',r:'こうきょう',m:'public, community, public service, society, communal'},
  {k:'工芸',r:'こうげい',m:'industrial arts'},
  {k:'孝行',r:'こうこう',m:'filial piety'},
  {k:'交差',r:'こうさ',m:'cross'},
  {k:'講師',r:'こうし',m:'lecturer'},
  {k:'工事',r:'こうじ',m:'construction work'},
  {k:'公式',r:'こうしき',m:'formula, formality, official'},
  {k:'口実',r:'こうじつ',m:'excuse'},
  {k:'こうして',r:'こうして',m:'thus'},
  {k:'校舎',r:'こうしゃ',m:'school building'},
  {k:'公衆',r:'こうしゅう',m:'the public'},
  {k:'香水',r:'こうすい',m:'perfume'},
  {k:'公正',r:'こうせい',m:'justice, fairness, impartiality'},
  {k:'功績',r:'こうせき',m:'achievements, merit, meritorious service, meritorious deed'},
  {k:'光線',r:'こうせん',m:'beam, light ray'},
  {k:'高層',r:'こうそう',m:'upper'},
  {k:'構造',r:'こうぞう',m:'structure, construction'},
  {k:'交替',r:'こうたい',m:'alternation, change, relief, relay, shift'},
  {k:'耕地',r:'こうち',m:'arable land'},
  {k:'交通機関',r:'こうつうきかん',m:'transportation facilities'},
  {k:'校庭',r:'こうてい',m:'campus'},
  {k:'肯定',r:'こうてい',m:'positive, affirmation'},
  {k:'高度',r:'こうど',m:'altitude, height, advanced'},
  {k:'高等',r:'こうとう',m:'high class, high grade'},
  {k:'合同',r:'ごうどう',m:'combination, incorporation, union, amalgamation'},
  {k:'後輩',r:'こうはい',m:'junior (at work or school)'},
  {k:'公表',r:'こうひょう',m:'official announcement, proclamation'},
  {k:'鉱物',r:'こうぶつ',m:'mineral'},
  {k:'公務',r:'こうむ',m:'official business, public business'},
  {k:'項目',r:'こうもく',m:'item'},
  {k:'紅葉',r:'こうよう',m:'Japanese maple'},
  {k:'合理',r:'ごうり',m:'rational'},
  {k:'交流',r:'こうりゅう',m:'alternating current, intercourse, (cultural) exchange, intermingling'},
  {k:'合流',r:'ごうりゅう',m:'confluence, union, linking up, merge'},
  {k:'効力',r:'こうりょく',m:'effect, efficacy, validity, potency'},
  {k:'超える',r:'こえる',m:'to exceed, to cross over, to cross'},
  {k:'コース',r:'コース',m:'course'},
  {k:'コーラス',r:'コーラス',m:'chorus'},
  {k:'焦がす',r:'こがす',m:'to burn, to scorch, to singe, to char'},
  {k:'国王',r:'こくおう',m:'king'},
  {k:'国籍',r:'こくせき',m:'nationality'},
  {k:'国立',r:'こくりつ',m:'national'},
  {k:'ごくろうさま',r:'ごくろうさま',m:'thank you very much for your...'},
  {k:'焦げる',r:'こげる',m:'to burn, to be burned'},
  {k:'凍える',r:'こごえる',m:'to freeze, to be chilled, to be frozen'},
  {k:'心当たり',r:'こころあたり',m:'having some knowledge of, happening to know'},
  {k:'心得る',r:'こころえる',m:'to be informed, to have thorough knowledge'},
  {k:'腰掛け',r:'こしかけ',m:'seat, bench'},
  {k:'腰掛ける',r:'こしかける',m:'to sit (down)'},
  {k:'五十音',r:'ごじゅうおん',m:'the Japanese syllabary'},
  {k:'胡椒',r:'こしょう',m:'pepper'},
  {k:'こしらえる',r:'こしらえる',m:'to make, to manufacture'},
  {k:'超す',r:'こす',m:'to cross, to pass, to tide over'},
  {k:'擦る',r:'こする',m:'to rub, to chafe, to file, to frost (glass), to strike (match)'},
  {k:'ごぞんじですか',r:'ごぞんじですか',m:'do you know?'},
  {k:'個体',r:'こたい',m:'an individual'},
  {k:'御馳走',r:'ごちそう',m:'feast, treating (someone)'},
  {k:'ごちそうさま',r:'ごちそうさま',m:'feast'},
  {k:'こちらこそ',r:'こちらこそ',m:'it is I who should say so'},
  {k:'小遣い',r:'こづかい',m:'personal expenses, pocket money, spending money, allowance'},
  {k:'コック',r:'コック',m:'cook, tap, spigot, faucet, cock'},
  {k:'こっそり',r:'こっそり',m:'stealthily, secretly'},
  {k:'古典',r:'こてん',m:'old book, classics, classic'},
  {k:'琴',r:'こと',m:'Koto (Japanese harp)'},
  {k:'言付ける',r:'ことづける',m:'to send word, to send a message'},
  {k:'言葉遣い',r:'ことばづかい',m:'speech, expression, wording'},
  {k:'こないだ',r:'こないだ',m:'the other day, lately, recently'},
  {k:'御無沙汰',r:'ごぶさた',m:'not writing or contacting for a while'},
  {k:'こぼす',r:'こぼす',m:'to spill'},
  {k:'こぼれる',r:'こぼれる',m:'to overflow, to spill'},
  {k:'塵芥',r:'ごみ',m:'trash, rubbish'},
  {k:'ゴム',r:'ゴム',m:'gum, rubber, eraser'},
  {k:'御免',r:'ごめん',m:'your pardon, declining (something), dismissal, permission'},
  {k:'ごめんください',r:'ごめんください',m:'may I come in?'},
  {k:'小指',r:'こゆび',m:'little finger'},
  {k:'こらえる',r:'こらえる',m:'to bear, to stand, to endure, to put up with'},
  {k:'娯楽',r:'ごらく',m:'pleasure, amusement'},
  {k:'御覧',r:'ごらん',m:'look, inspection, try'},
  {k:'コレクション',r:'コレクション',m:'collection, correction'},
  {k:'転がす',r:'ころがす',m:'to roll'},
  {k:'転がる',r:'ころがる',m:'to roll, to tumble'},
  {k:'紺',r:'こん',m:'navy blue, deep blue'},
  {k:'コンクール',r:'コンクール',m:'contest'},
  {k:'コンクリート',r:'コンクリート',m:'concrete'},
  {k:'混合',r:'こんごう',m:'mixing, mixture'},
  {k:'コンセント',r:'コンセント',m:'consent, concentric'},
  {k:'献立',r:'こんだて',m:'menu, program, schedule'},
  {k:'こんばんは',r:'こんばんは',m:'good evening'},
  {k:'サークル',r:'サークル',m:'circle, sports club'},
  {k:'在学',r:'ざいがく',m:'(enrolled) in school'},
  {k:'再三',r:'さいさん',m:'again and again, repeatedly'},
  {k:'祭日',r:'さいじつ',m:'national holiday, festival day'},
  {k:'催促',r:'さいそく',m:'request, demand, claim, urge (action), press for'},
  {k:'採点',r:'さいてん',m:'marking, grading, looking over'},
  {k:'災難',r:'さいなん',m:'calamity, misfortune'},
  {k:'裁縫',r:'さいほう',m:'sewing'},
  {k:'材木',r:'ざいもく',m:'lumber, timber'},
  {k:'サイレン',r:'サイレン',m:'siren'},
  {k:'逆さ',r:'さかさ',m:'reverse, inversion, upside down'},
  {k:'逆様',r:'さかさま',m:'inversion, upside down'},
  {k:'捜す',r:'さがす',m:'to search, to seek, to look for'},
  {k:'遡る',r:'さかのぼる',m:'to go back, to go upstream, to make retroactive'},
  {k:'酒場',r:'さかば',m:'bar, bar-room'},
  {k:'さきおととい',r:'さきおととい',m:'two days before yesterday'},
  {k:'先程',r:'さきほど',m:'some time ago'},
  {k:'裂く',r:'さく',m:'to tear, to split'},
  {k:'索引',r:'さくいん',m:'index, indices'},
  {k:'作者',r:'さくしゃ',m:'author, authoress'},
  {k:'削除',r:'さくじょ',m:'elimination, cancellation, deletion, erasure'},
  {k:'作成',r:'さくせい',m:'frame, draw up, make, producing'},
  {k:'作製',r:'さくせい',m:'manufacture'},
  {k:'探る',r:'さぐる',m:'to search, to look for, to sound out'},
  {k:'囁く',r:'ささやく',m:'to whisper, to murmur'},
  {k:'刺さる',r:'ささる',m:'to stick, to be stuck'},
  {k:'匙',r:'さじ',m:'spoon'},
  {k:'座敷',r:'ざしき',m:'tatami room'},
  {k:'差し支え',r:'さしつかえ',m:'hindrance, impediment'},
  {k:'差し引き',r:'さしひき',m:'deduction, subtraction, balance, ebb and flow, rise and fall'},
  {k:'刺身',r:'さしみ',m:'sliced raw fish'},
  {k:'刺す',r:'さす',m:'to pierce, to stab, to prick, to thrust'},
  {k:'挿す',r:'さす',m:'to insert, to put in, to graft, to wear in belt'},
  {k:'注す',r:'さす',m:'to pour (drink), to serve (drinks)'},
  {k:'射す',r:'さす',m:'to shine, to strike'},
  {k:'流石',r:'さすが',m:'clever, adept, good, expectations, as one would expect'},
  {k:'撮影',r:'さつえい',m:'photographing'},
  {k:'雑音',r:'ざつおん',m:'noise (jarring, grating)'},
  {k:'さっさと',r:'さっさと',m:'quickly'},
  {k:'早速',r:'さっそく',m:'at once, immediately, without delay, promptly'},
  {k:'錆',r:'さび',m:'rust (color)'},
  {k:'錆びる',r:'さびる',m:'to rust, to become rusty'},
  {k:'座布団',r:'ざぶとん',m:'cushion (Japanese)'},
  {k:'冷ます',r:'さます',m:'to cool, to dampen, to let cool'},
  {k:'妨げる',r:'さまたげる',m:'to disturb, to prevent'},
  {k:'冷める',r:'さめる',m:'to become cool, to wear off, to abate, to subside'},
  {k:'さようなら',r:'さようなら',m:'good-bye'},
  {k:'再来月',r:'さらいげつ',m:'month after next'},
  {k:'再来週',r:'さらいしゅう',m:'week after next'},
  {k:'再来年',r:'さらいねん',m:'year after next'},
  {k:'サラリーマン',r:'サラリーマン',m:'salary man, company employee'},
  {k:'騒がしい',r:'さわがしい',m:'noisy'},
  {k:'さわやか',r:'さわやか',m:'fresh, refreshing, invigorating'},
  {k:'三角',r:'さんかく',m:'triangle, triangular'},
  {k:'算数',r:'さんすう',m:'arithmetic'},
  {k:'酸性',r:'さんせい',m:'acidity'},
  {k:'産地',r:'さんち',m:'producing area'},
  {k:'サンプル',r:'サンプル',m:'sample'},
  {k:'山林',r:'さんりん',m:'mountain forest, mountains and forest'},
  {k:'仕上がる',r:'しあがる',m:'to be finished'},
  {k:'しあさって',r:'しあさって',m:'two days after tomorrow'},
  {k:'シーズン',r:'シーズン',m:'season (sporting)'},
  {k:'シーツ',r:'シーツ',m:'sheet'},
  {k:'寺院',r:'じいん',m:'temple'},
  {k:'しいんと',r:'しいんと',m:'silent (as the grave), (deathly) quiet'},
  {k:'自衛',r:'じえい',m:'self-defense'},
  {k:'塩辛い',r:'しおからい',m:'salty (taste)'},
  {k:'司会',r:'しかい',m:'chairmanship'},
  {k:'四角',r:'しかく',m:'square'},
  {k:'四角い',r:'しかくい',m:'square'},
  {k:'時間割',r:'じかんわり',m:'timetable, schedule'},
  {k:'四季',r:'しき',m:'four seasons'},
  {k:'敷地',r:'しきち',m:'site'},
  {k:'至急',r:'しきゅう',m:'urgent, pressing'},
  {k:'敷く',r:'しく',m:'to spread out, to lay out'},
  {k:'茂る',r:'しげる',m:'to grow thick, to luxuriate, to be luxurious'},
  {k:'持参',r:'じさん',m:'bringing, taking, carrying'},
  {k:'磁石',r:'じしゃく',m:'magnet'},
  {k:'四捨五入',r:'ししゃごにゅう',m:'rounding up (fractions)'},
  {k:'始終',r:'しじゅう',m:'continuously, from beginning to end'},
  {k:'自習',r:'じしゅう',m:'self-study'},
  {k:'静まる',r:'しずまる',m:'to quieten down, to calm down, to subside'},
  {k:'姿勢',r:'しせい',m:'attitude, posture'},
  {k:'自然科学',r:'しぜんかがく',m:'natural science'},
  {k:'時速',r:'じそく',m:'speed (per hour)'},
  {k:'子孫',r:'しそん',m:'descendants, posterity, offspring'},
  {k:'死体',r:'したい',m:'corpse'},
  {k:'下書き',r:'したがき',m:'rough copy, draft'},
  {k:'下町',r:'したまち',m:'downtown, lower parts of town'},
  {k:'自治',r:'じち',m:'self-government, autonomy'},
  {k:'実感',r:'じっかん',m:'feelings (actual, true)'},
  {k:'湿気',r:'しっけ',m:'moisture, humidity, dampness'},
  {k:'湿気',r:'しっき',m:'moisture, humidity, dampness'},
  {k:'しつこい',r:'しつこい',m:'insistent, obstinate'},
  {k:'実習',r:'じっしゅう',m:'practice, training'},
  {k:'実績',r:'じっせき',m:'achievements, actual results'},
  {k:'湿度',r:'しつど',m:'level of humidity'},
  {k:'執筆',r:'しっぴつ',m:'writing'},
  {k:'実物',r:'じつぶつ',m:'real thing, original'},
  {k:'しっぽ',r:'しっぽ',m:'tail (animal)'},
  {k:'実用',r:'じつよう',m:'practical use, utility'},
  {k:'実力',r:'じつりょく',m:'merit, efficiency, arms, force'},
  {k:'実例',r:'じつれい',m:'example, illustration'},
  {k:'失恋',r:'しつれん',m:'disappointed love, broken heart, unrequited love, be lovelorn'},
  {k:'指定',r:'してい',m:'designation, specification, assignment, pointing at'},
  {k:'私鉄',r:'してつ',m:'private railway'},
  {k:'児童',r:'じどう',m:'children, juvenile'},
  {k:'縛る',r:'しばる',m:'to tie, to bind'},
  {k:'地盤',r:'じばん',m:'the ground'},
  {k:'しびれる',r:'しびれる',m:'to become numb, to go to sleep (i.e., a limb)'},
  {k:'紙幣',r:'しへい',m:'paper money, notes, bills'},
  {k:'しぼむ',r:'しぼむ',m:'to wither, to fade (away), to shrivel, to wilt'},
  {k:'絞る',r:'しぼる',m:'to press, to wring, to squeeze'},
  {k:'縞',r:'しま',m:'stripe'},
  {k:'地味',r:'じみ',m:'plain, simple'},
  {k:'しみじみ',r:'しみじみ',m:'keenly, deeply, heartily'},
  {k:'氏名',r:'しめい',m:'full name, identity'},
  {k:'締切',r:'しめきり',m:'closing, cut-off, end, deadline, Closed, No Entrance'},
  {k:'締め切る',r:'しめきる',m:'to shut up'},
  {k:'湿る',r:'しめる',m:'to be wet, to become wet, to be damp'},
  {k:'ジャーナリスト',r:'ジャーナリスト',m:'journalist'},
  {k:'社会科学',r:'しゃかいかがく',m:'social science'},
  {k:'しゃがむ',r:'しゃがむ',m:'to squat'},
  {k:'蛇口',r:'じゃぐち',m:'faucet, tap'},
  {k:'弱点',r:'じゃくてん',m:'weak point, weakness'},
  {k:'車庫',r:'しゃこ',m:'garage, car shed'},
  {k:'車掌',r:'しゃしょう',m:'(train) conductor'},
  {k:'写生',r:'しゃせい',m:'sketching, drawing from nature'},
  {k:'社説',r:'しゃせつ',m:'editorial, leading article'},
  {k:'しゃっくり',r:'しゃっくり',m:'hiccough, hiccup'},
  {k:'シャッター',r:'シャッター',m:'shutter'},
  {k:'しゃぶる',r:'しゃぶる',m:'to suck, to chew'},
  {k:'車輪',r:'しゃりん',m:'(car) wheel'},
  {k:'洒落',r:'しゃれ',m:'joke, pun, witticism'},
  {k:'じゃんけん',r:'じゃんけん',m:'rock-scissors-paper game'},
  {k:'集会',r:'しゅうかい',m:'meeting, assembly'},
  {k:'住居',r:'じゅうきょ',m:'dwelling, house, residence, address'},
  {k:'集金',r:'しゅうきん',m:'money collection'},
  {k:'集合',r:'しゅうごう',m:'gathering, assembly, meeting, set (math)'},
  {k:'習字',r:'しゅうじ',m:'penmanship'},
  {k:'修繕',r:'しゅうぜん',m:'repair, mending'},
  {k:'重体',r:'じゅうたい',m:'seriously ill, serious condition, critical state'},
  {k:'じゅうたん',r:'じゅうたん',m:'carpet'},
  {k:'終点',r:'しゅうてん',m:'terminus, last stop (e.g train)'},
  {k:'重点',r:'じゅうてん',m:'important point, lay stress on, colon, emphasis'},
  {k:'就任',r:'しゅうにん',m:'inauguration, assumption of office'},
  {k:'周辺',r:'しゅうへん',m:'circumference, outskirts, environs, (computer) peripheral'},
  {k:'重役',r:'じゅうやく',m:'director, high executive'},
  {k:'終了',r:'しゅうりょう',m:'end, close, termination'},
  {k:'重量',r:'じゅうりょう',m:'weight, heavyweight boxer'},
  {k:'重力',r:'じゅうりょく',m:'gravity'},
  {k:'熟語',r:'じゅくご',m:'idiom, idiomatic phrase, kanji compound'},
  {k:'祝日',r:'しゅくじつ',m:'national holiday'},
  {k:'縮小',r:'しゅくしょう',m:'reduction, curtailment'},
  {k:'受験',r:'じゅけん',m:'taking an examination'},
  {k:'主語',r:'しゅご',m:'subject (gram.)'},
  {k:'出勤',r:'しゅっきん',m:'going to work, at work'},
  {k:'述語',r:'じゅつご',m:'predicate'},
  {k:'出張',r:'しゅっちょう',m:'official tour, business trip'},
  {k:'寿命',r:'じゅみょう',m:'life span'},
  {k:'主役',r:'しゅやく',m:'leading part, leading actor (actress)'},
  {k:'受話器',r:'じゅわき',m:'(telephone) receiver'},
  {k:'循環',r:'じゅんかん',m:'circulation, rotation, cycle'},
  {k:'巡査',r:'じゅんさ',m:'police, policeman'},
  {k:'順々',r:'じゅんじゅん',m:'in order, in turn'},
  {k:'順序',r:'じゅんじょ',m:'order, sequence, procedure'},
  {k:'純情',r:'じゅんじょう',m:'pure heart, naivete, self-sacrificing devotion'},
  {k:'純粋',r:'じゅんすい',m:'pure, true, genuine, unmixed'},
  {k:'消化',r:'しょうか',m:'digestion'},
  {k:'小学生',r:'しょうがくせい',m:'grade school student'},
  {k:'しょうがない',r:'しょうがない',m:'it\'s no use, impossible, inevitable'},
  {k:'将棋',r:'しょうぎ',m:'shogi (Japanese chess)'},
  {k:'蒸気',r:'じょうき',m:'steam, vapor'},
  {k:'定規',r:'じょうぎ',m:'(measuring) ruler'},
  {k:'上級',r:'じょうきゅう',m:'advanced level, high grade, senior'},
  {k:'商業',r:'しょうぎょう',m:'commerce, trade, business'},
  {k:'消極的',r:'しょうきょくてき',m:'passive'},
  {k:'賞金',r:'しょうきん',m:'prize, monetary award'},
  {k:'上下',r:'じょうげ',m:'high and low, up and down, unloading and loading, praising and blaming'},
  {k:'障子',r:'しょうじ',m:'paper sliding door'},
  {k:'商社',r:'しょうしゃ',m:'trading company, firm'},
  {k:'乗車',r:'じょうしゃ',m:'taking a train, entraining'},
  {k:'上旬',r:'じょうじゅん',m:'first 10 days of month'},
  {k:'生ずる',r:'しょうずる',m:'to cause, to arise, to be generated'},
  {k:'小数',r:'しょうすう',m:'fraction (part of), decimal'},
  {k:'商店',r:'しょうてん',m:'shop, business firm'},
  {k:'焦点',r:'しょうてん',m:'focus, point'},
  {k:'消毒',r:'しょうどく',m:'disinfection, sterilization'},
  {k:'勝敗',r:'しょうはい',m:'victory or defeat, issue (of battle)'},
  {k:'蒸発',r:'じょうはつ',m:'evaporation, unexplained disappearance'},
  {k:'賞品',r:'しょうひん',m:'prize, trophy'},
  {k:'勝負',r:'しょうぶ',m:'victory or defeat, match, contest, game, bout'},
  {k:'小便',r:'しょうべん',m:'urine, piss'},
  {k:'消防署',r:'しょうぼうしょ',m:'fire station'},
  {k:'正味',r:'しょうみ',m:'net (weight)'},
  {k:'正面',r:'しょうめん',m:'the front, honesty'},
  {k:'消耗',r:'しょうもう',m:'exhaustion, consumption'},
  {k:'醤油',r:'しょうゆ',m:'soy sauce'},
  {k:'省略',r:'しょうりゃく',m:'omission, abbreviation, abridgment'},
  {k:'初級',r:'しょきゅう',m:'elementary level'},
  {k:'助教授',r:'じょきょうじゅ',m:'assistant professor'},
  {k:'食塩',r:'しょくえん',m:'table salt'},
  {k:'職人',r:'しょくにん',m:'worker, mechanic, artisan, craftsman'},
  {k:'初旬',r:'しょじゅん',m:'first 10 days of the month'},
  {k:'書籍',r:'しょせき',m:'book, publication'},
  {k:'食器',r:'しょっき',m:'tableware'},
  {k:'ショップ',r:'ショップ',m:'a shop'},
  {k:'書店',r:'しょてん',m:'bookshop'},
  {k:'書道',r:'しょどう',m:'calligraphy'},
  {k:'白髪',r:'しらが',m:'white or grey hair, trendy hair bleaching'},
  {k:'知合い',r:'しりあい',m:'acquaintance'},
  {k:'シリーズ',r:'シリーズ',m:'series'},
  {k:'私立',r:'しりつ',m:'private (establishment)'},
  {k:'資料',r:'しりょう',m:'materials, data'},
  {k:'汁',r:'しる',m:'juice, sap, soup, broth'},
  {k:'素人',r:'しろうと',m:'amateur, novice'},
  {k:'芯',r:'しん',m:'core, heart, wick, marrow'},
  {k:'新幹線',r:'しんかんせん',m:'bullet train (very high speed), Shinkansen'},
  {k:'真空',r:'しんくう',m:'vacuum, hollow, empty'},
  {k:'信ずる',r:'しんずる',m:'to believe, to believe in, to place trust in'},
  {k:'心身',r:'しんしん',m:'mind and body'},
  {k:'申請',r:'しんせい',m:'application, request, petition'},
  {k:'人造',r:'じんぞう',m:'man-made, synthetic, artificial'},
  {k:'寝台',r:'しんだい',m:'bed, couch'},
  {k:'診断',r:'しんだん',m:'diagnosis'},
  {k:'侵入',r:'しんにゅう',m:'penetration, invasion, raid, aggression, trespass'},
  {k:'人文科学',r:'じんぶんかがく',m:'social sciences, humanities'},
  {k:'人命',r:'じんめい',m:'(human) life'},
  {k:'深夜',r:'しんや',m:'late at night'},
  {k:'森林',r:'しんりん',m:'forest, woods'},
  {k:'親類',r:'しんるい',m:'relation, kin'},
  {k:'針路',r:'しんろ',m:'course, direction, compass bearing'},
  {k:'神話',r:'しんわ',m:'myth, legend'},
  {k:'酢',r:'す',m:'vinegar'},
  {k:'水産',r:'すいさん',m:'marine products, fisheries'},
  {k:'炊事',r:'すいじ',m:'cooking, culinary arts'},
  {k:'水蒸気',r:'すいじょうき',m:'water vapor, steam'},
  {k:'水素',r:'すいそ',m:'hydrogen'},
  {k:'垂直',r:'すいちょく',m:'vertical, perpendicular'},
  {k:'推定',r:'すいてい',m:'presumption, assumption, estimation'},
  {k:'水滴',r:'すいてき',m:'drop of water'},
  {k:'水筒',r:'すいとう',m:'canteen, flask, water bottle'},
  {k:'随筆',r:'ずいひつ',m:'essays, miscellaneous writings'},
  {k:'水分',r:'すいぶん',m:'moisture'},
  {k:'水平',r:'すいへい',m:'water level, horizon'},
  {k:'水平線',r:'すいへいせん',m:'horizon'},
  {k:'水曜',r:'すいよう',m:'Wednesday'},
  {k:'ずうずうしい',r:'ずうずうしい',m:'impudent, shameless'},
  {k:'ずうっと',r:'ずうっと',m:'consecutively, throughout, a lot'},
  {k:'末っ子',r:'すえっこ',m:'youngest child'},
  {k:'スカーフ',r:'スカーフ',m:'scarf'},
  {k:'図鑑',r:'ずかん',m:'picture book'},
  {k:'杉',r:'すぎ',m:'Japanese cedar'},
  {k:'好き嫌い',r:'すききらい',m:'likes and dislikes, taste'},
  {k:'好き好き',r:'すきずき',m:'matter of taste'},
  {k:'透き通る',r:'すきとおる',m:'to be(come) transparent'},
  {k:'伱間',r:'すきま',m:'crevice, crack, gap, opening'},
  {k:'スクール',r:'スクール',m:'school'},
  {k:'すくなくとも',r:'すくなくとも',m:'at least'},
  {k:'図形',r:'ずけい',m:'figure'},
  {k:'スケジュール',r:'スケジュール',m:'schedule'},
  {k:'鈴',r:'すず',m:'bell'},
  {k:'涼む',r:'すずむ',m:'to cool oneself, to cool off, to enjoy evening cool'},
  {k:'スタート',r:'スタート',m:'start'},
  {k:'スチュワーデス',r:'スチュワーデス',m:'stewardess'},
  {k:'すっきり',r:'すっきり',m:'shapely, clear, neat'},
  {k:'すっぱい',r:'すっぱい',m:'sour, acid'},
  {k:'ステージ',r:'ステージ',m:'stage, performance'},
  {k:'棄てる',r:'すてる',m:'to throw away, to abandon, to give up'},
  {k:'ストッキング',r:'ストッキング',m:'stockings'},
  {k:'ストップ',r:'ストップ',m:'stop'},
  {k:'素直',r:'すなお',m:'obedient, meek, docile, unaffected'},
  {k:'頭脳',r:'ずのう',m:'head, brains, intellect'},
  {k:'スピーカー',r:'スピーカー',m:'speaker'},
  {k:'図表',r:'ずひょう',m:'chart, diagram, graph'},
  {k:'スマート',r:'スマート',m:'smart, stylish, slim'},
  {k:'住まい',r:'すまい',m:'dwelling, house, residence, address'},
  {k:'すまない',r:'すまない',m:'sorry (phrase)'},
  {k:'墨',r:'すみ',m:'ink'},
  {k:'澄む',r:'すむ',m:'to clear (e.g. weather), to become transparent'},
  {k:'清む',r:'すむ',m:'to become clear, to become at peace'},
  {k:'相撲',r:'すもう',m:'sumo wrestling'},
  {k:'スライド',r:'スライド',m:'slide'},
  {k:'ずらす',r:'ずらす',m:'to put off, to delay'},
  {k:'ずらり',r:'ずらり',m:'in a row'},
  {k:'掏摸',r:'すり',m:'pickpocket'},
  {k:'刷る',r:'する',m:'to print'},
  {k:'伶い',r:'ずるい',m:'sly, cunning'},
  {k:'すれちがう',r:'すれちがう',m:'to pass by one another, to disagree'},
  {k:'ずれる',r:'ずれる',m:'to slip, to get out of alignment'},
  {k:'寸法',r:'すんぽう',m:'measurement, size, dimension'},
  {k:'姓',r:'せい',m:'surname, family name'},
  {k:'税関',r:'ぜいかん',m:'customs house'},
  {k:'製作',r:'せいさく',m:'manufacture, production'},
  {k:'制作',r:'せいさく',m:'work (film, book)'},
  {k:'性質',r:'せいしつ',m:'nature, property, disposition'},
  {k:'清書',r:'せいしょ',m:'clean copy'},
  {k:'青少年',r:'せいしょうねん',m:'youth, young person'},
  {k:'整数',r:'せいすう',m:'integer'},
  {k:'清掃',r:'せいそう',m:'cleaning'},
  {k:'生存',r:'せいぞん',m:'existence, being, survival'},
  {k:'生長',r:'せいちょう',m:'growth, increment'},
  {k:'政党',r:'せいとう',m:'(member of) political party'},
  {k:'生年月日',r:'せいねんがっぴ',m:'birth date'},
  {k:'性能',r:'せいのう',m:'ability, efficiency'},
  {k:'整備',r:'せいび',m:'adjustment, completion, consolidation'},
  {k:'成分',r:'せいぶん',m:'ingredient, component, composition'},
  {k:'性別',r:'せいべつ',m:'distinction by sex, sex, gender'},
  {k:'正方形',r:'せいほうけい',m:'square'},
  {k:'正門',r:'せいもん',m:'main gate, main entrance'},
  {k:'成立',r:'せいりつ',m:'coming into existence, arrangements, establishment, completion'},
  {k:'西暦',r:'せいれき',m:'Christian Era, anno domini (A.D.)'},
  {k:'背負う',r:'せおう',m:'to be burdened with, to carry on back or shoulder'},
  {k:'赤道',r:'せきどう',m:'equator'},
  {k:'折角',r:'せっかく',m:'with trouble, at great pains, long-awaited'},
  {k:'接近',r:'せっきん',m:'getting closer, drawing nearer, approaching'},
  {k:'石鹸',r:'せっけん',m:'soap'},
  {k:'接する',r:'せっする',m:'to come in contact with, to connect, to attend, to receive'},
  {k:'せっせと',r:'せっせと',m:'diligently, persistently'},
  {k:'接続',r:'せつぞく',m:'connection, union, join, link, changing trains'},
  {k:'瀬戸物',r:'せともの',m:'earthenware, crockery, china'},
  {k:'ぜひとも',r:'ぜひとも',m:'by all means (with sense of not taking no for an answer)'},
  {k:'迫る',r:'せまる',m:'to draw near, to press'},
  {k:'ゼミ',r:'ゼミ',m:'seminar'},
  {k:'せめて',r:'せめて',m:'offense, method of attack'},
  {k:'攻める',r:'せめる',m:'to attack, to assault'},
  {k:'セメント',r:'セメント',m:'cement'},
  {k:'栓',r:'せん',m:'stopper, cork, stopcock'},
  {k:'前後',r:'ぜんご',m:'around, throughout, front and back, before and behind, before and after'},
  {k:'洗剤',r:'せんざい',m:'detergent, washing material'},
  {k:'全集',r:'ぜんしゅう',m:'complete works'},
  {k:'全身',r:'ぜんしん',m:'the whole body, full-length (portrait)'},
  {k:'扇子',r:'せんす',m:'folding fan'},
  {k:'専制',r:'せんせい',m:'despotism, autocracy'},
  {k:'先々月',r:'せんせんげつ',m:'month before last'},
  {k:'先々週',r:'せんせんしゅう',m:'week before last'},
  {k:'先祖',r:'せんぞ',m:'ancestor'},
  {k:'先端',r:'せんたん',m:'pointed end, tip, fine point'},
  {k:'センチ',r:'センチ',m:'centimeter'},
  {k:'宣伝',r:'せんでん',m:'propaganda, publicity'},
  {k:'先頭',r:'せんとう',m:'head, lead, vanguard, first'},
  {k:'全般',r:'ぜんぱん',m:'the whole, universal, wholly, general'},
  {k:'扇風機',r:'せんぷうき',m:'electric fan'},
  {k:'線路',r:'せんろ',m:'line, track, roadbed'},
  {k:'相違',r:'そうい',m:'difference, discrepancy, variation'},
  {k:'そういえば',r:'そういえば',m:'which reminds me...'},
  {k:'雑巾',r:'ぞうきん',m:'house-cloth, dust cloth'},
  {k:'増減',r:'ぞうげん',m:'increase and decrease, fluctuation'},
  {k:'倉庫',r:'そうこ',m:'storehouse, warehouse, godown'},
  {k:'相互',r:'そうご',m:'mutual, reciprocal'},
  {k:'創作',r:'そうさく',m:'production, literary creation, work'},
  {k:'葬式',r:'そうしき',m:'funeral'},
  {k:'そうして',r:'そうして',m:'and, like that'},
  {k:'造船',r:'ぞうせん',m:'shipbuilding'},
  {k:'騒々しい',r:'そうぞうしい',m:'noisy, boisterous'},
  {k:'増大',r:'ぞうだい',m:'enlargement'},
  {k:'そうっと',r:'そうっと',m:'softly, gently, stealthily'},
  {k:'送別',r:'そうべつ',m:'farewell, send-off'},
  {k:'草履',r:'ぞうり',m:'zoori (Japanese footwear), sandals'},
  {k:'総理大臣',r:'そうりだいじん',m:'Prime Minister'},
  {k:'送料',r:'そうりょう',m:'postage, carriage'},
  {k:'属する',r:'ぞくする',m:'to belong to, to come under, to be affiliated with, to be subject to'},
  {k:'続々',r:'ぞくぞく',m:'successively, one after another'},
  {k:'速達',r:'そくたつ',m:'express, special delivery'},
  {k:'測定',r:'そくてい',m:'measurement'},
  {k:'測量',r:'そくりょう',m:'measurement, surveying'},
  {k:'速力',r:'そくりょく',m:'speed'},
  {k:'素質',r:'そしつ',m:'character, qualities, genius'},
  {k:'祖先',r:'そせん',m:'ancestor'},
  {k:'そそっかしい',r:'そそっかしい',m:'careless, thoughtless'},
  {k:'卒直',r:'そっちょく',m:'frankness, candor, openheartedness'},
  {k:'具える',r:'そなえる',m:'to be furnished with'},
  {k:'そのうえ',r:'そのうえ',m:'in addition, furthermore'},
  {k:'その頃',r:'そのころ',m:'at that time, then'},
  {k:'そのため',r:'そのため',m:'hence, for that reason'},
  {k:'そのほか',r:'そのほか',m:'otherwise'},
  {k:'蕎麦',r:'そば',m:'soba (buckwheat noodles)'},
  {k:'剃る',r:'そる',m:'to shave'},
  {k:'それなのに',r:'それなのに',m:'nevertheless, however'},
  {k:'逸れる',r:'それる',m:'to stray (turn) from subject, to get lost, to go astray'},
  {k:'揃う',r:'そろう',m:'to become complete, to be equal, to be all present, to gather'},
  {k:'揃える',r:'そろえる',m:'to put things in order, to arrange, to make uniform, to get something ready'},
  {k:'算盤',r:'そろばん',m:'abacus'},
  {k:'存じる',r:'ぞんじる',m:'to know'},
  {k:'存ずる',r:'ぞんずる',m:'to think, to consider'},
  {k:'損得',r:'そんとく',m:'loss and gain, advantage and disadvantage'},
  {k:'田ぼ',r:'たんぼ',m:'paddy field, farm'},
  {k:'第一',r:'だいいち',m:'first, foremost, #1'},
  {k:'退院',r:'たいいん',m:'leaving hospital'},
  {k:'大学院',r:'だいがくいん',m:'graduate school'},
  {k:'大工',r:'だいく',m:'carpenter'},
  {k:'体系',r:'たいけい',m:'system, organization'},
  {k:'太鼓',r:'たいこ',m:'drum, tambourine'},
  {k:'対策',r:'たいさく',m:'counter-plan, counter-measure'},
  {k:'大して',r:'たいして',m:'(not so) much, (not) very'},
  {k:'対照',r:'たいしょう',m:'contrast, antithesis, comparison'},
  {k:'大小',r:'だいしょう',m:'size'},
  {k:'体制',r:'たいせい',m:'order, system, structure, set-up, organization'},
  {k:'体積',r:'たいせき',m:'capacity, volume'},
  {k:'大層',r:'たいそう',m:'very much, exaggerated, very fine'},
  {k:'体操',r:'たいそう',m:'gymnastics, physical exercises, calisthenics'},
  {k:'大分',r:'だいぶん',m:'considerably, greatly, a lot'},
  {k:'大木',r:'たいぼく',m:'large tree'},
  {k:'題名',r:'だいめい',m:'title'},
  {k:'代名詞',r:'だいめいし',m:'pronoun'},
  {k:'タイア',r:'タイア',m:'tire, tyre'},
  {k:'ダイヤグラム',r:'ダイヤグラム',m:'diagram'},
  {k:'ダイヤモンド',r:'ダイヤモンド',m:'diamond'},
  {k:'ダイヤル',r:'ダイヤル',m:'dial'},
  {k:'対立',r:'たいりつ',m:'confrontation, opposition, antagonism'},
  {k:'田植え',r:'たうえ',m:'rice planting'},
  {k:'絶えず',r:'たえず',m:'constantly'},
  {k:'楕円',r:'だえん',m:'ellipse'},
  {k:'高める',r:'たかめる',m:'to raise, to lift, to boost'},
  {k:'耕す',r:'たがやす',m:'to till, to plow, to cultivate'},
  {k:'滝',r:'たき',m:'waterfall'},
  {k:'炊く',r:'たく',m:'to boil, to cook'},
  {k:'焚く',r:'たく',m:'to burn, to kindle, to build a fire'},
  {k:'蓄える',r:'たくわえる',m:'to store, to lay in stock'},
  {k:'竹',r:'たけ',m:'bamboo, middle (of a three-tier ranking system)'},
  {k:'助かる',r:'たすかる',m:'to be saved, to be rescued, to survive, to be helpful'},
  {k:'只',r:'ただ',m:'free of charge, mere, sole, only, usual, common'},
  {k:'但し',r:'ただし',m:'but, however, provided that'},
  {k:'畳む',r:'たたむ',m:'to fold (clothes)'},
  {k:'立ち止まる',r:'たちどまる',m:'to stop, to halt, to stand still'},
  {k:'たちまち',r:'たちまち',m:'at once, in a moment, suddenly, all at once'},
  {k:'建つ',r:'たつ',m:'to erect, to be erected, to be built'},
  {k:'発つ',r:'たつ',m:'to depart (on a plane, train, etc.)'},
  {k:'脱線',r:'だっせん',m:'derailment, digression'},
  {k:'妥当',r:'だとう',m:'valid, proper, right, appropriate'},
  {k:'例える',r:'たとえる',m:'to compare, to liken, to speak figuratively, to illustrate, to use a simile'},
  {k:'頼もしい',r:'たのもしい',m:'reliable, trustworthy, hopeful, promising'},
  {k:'足袋',r:'たび',m:'tabi, Japanese socks (with split toe)'},
  {k:'ダブル',r:'ダブル',m:'double'},
  {k:'だます',r:'だます',m:'to trick, to cheat, to deceive'},
  {k:'溜まる',r:'たまる',m:'to collect, to gather, to save'},
  {k:'ダム',r:'ダム',m:'dam'},
  {k:'溜息',r:'ためいき',m:'a sigh'},
  {k:'ためらう',r:'ためらう',m:'to hesitate'},
  {k:'溜める',r:'ためる',m:'to amass, to accumulate'},
  {k:'だらしない',r:'だらしない',m:'slovenly, loose'},
  {k:'足る',r:'たる',m:'to be sufficient, to be enough'},
  {k:'段階',r:'だんかい',m:'gradation, grade, stage'},
  {k:'短期',r:'たんき',m:'short term'},
  {k:'炭鉱',r:'たんこう',m:'coal mine, coal pit'},
  {k:'短所',r:'たんしょ',m:'defect, demerit, weak point, disadvantage'},
  {k:'たんす',r:'たんす',m:'chest of drawers'},
  {k:'淡水',r:'たんすい',m:'fresh water'},
  {k:'断水',r:'だんすい',m:'water outage'},
  {k:'単数',r:'たんすう',m:'singular (number)'},
  {k:'団地',r:'だんち',m:'multi-unit apartments'},
  {k:'断定',r:'だんてい',m:'conclusion, decision'},
  {k:'短編',r:'たんぺん',m:'short (e.g. story, film)'},
  {k:'誓う',r:'ちかう',m:'to swear, to vow, to take an oath, to pledge'},
  {k:'地下水',r:'ちかすい',m:'underground water'},
  {k:'近々',r:'ちかぢか',m:'nearness, before long'},
  {k:'近付ける',r:'ちかづける',m:'to bring near, to put close, to let come near, to associate with'},
  {k:'近寄る',r:'ちかよる',m:'to approach, to draw near'},
  {k:'力強い',r:'ちからづよい',m:'reassuring, emboldened'},
  {k:'ちぎる',r:'ちぎる',m:'to cut up fine, to pick (fruit)'},
  {k:'地質',r:'ちしつ',m:'geological features'},
  {k:'知人',r:'ちじん',m:'friend, acquaintance'},
  {k:'地帯',r:'ちたい',m:'area, zone'},
  {k:'縮む',r:'ちぢむ',m:'to shrink, to be contracted'},
  {k:'縮める',r:'ちぢめる',m:'to shorten, to reduce, to boil down, to shrink'},
  {k:'縮れる',r:'ちぢれる',m:'to be wavy, to be curled'},
  {k:'チップ',r:'チップ',m:'gratuity, tip, chip'},
  {k:'地点',r:'ちてん',m:'site, point on a map'},
  {k:'地名',r:'ちめい',m:'place name'},
  {k:'茶色い',r:'ちゃいろい',m:'brown'},
  {k:'着々',r:'ちゃくちゃく',m:'steadily'},
  {k:'茶碗',r:'ちゃわん',m:'rice bowl, tea cup, teacup'},
  {k:'中間',r:'ちゅうかん',m:'middle, midway, interim'},
  {k:'中旬',r:'ちゅうじゅん',m:'second third of a month'},
  {k:'抽象',r:'ちゅうしょう',m:'abstract'},
  {k:'中世',r:'ちゅうせい',m:'Middle Ages, mediaeval times'},
  {k:'中性',r:'ちゅうせい',m:'neuter gender, neutral (chem.), indifference, sterility'},
  {k:'中途',r:'ちゅうと',m:'in the middle, half-way'},
  {k:'中年',r:'ちゅうねん',m:'middle-aged'},
  {k:'超過',r:'ちょうか',m:'excess, being more than'},
  {k:'彫刻',r:'ちょうこく',m:'carving, engraving, sculpture'},
  {k:'長所',r:'ちょうしょ',m:'strong point, merit, advantage'},
  {k:'長女',r:'ちょうじょ',m:'eldest daughter'},
  {k:'調整',r:'ちょうせい',m:'regulation, adjustment, tuning'},
  {k:'調節',r:'ちょうせつ',m:'regulation, adjustment, control'},
  {k:'長短',r:'ちょうたん',m:'length, long and short'},
  {k:'頂点',r:'ちょうてん',m:'top, summit'},
  {k:'長男',r:'ちょうなん',m:'eldest son'},
  {k:'長方形',r:'ちょうほうけい',m:'rectangle, oblong'},
  {k:'調味料',r:'ちょうみりょう',m:'condiment, seasoning'},
  {k:'チョーク',r:'チョーク',m:'chock, chalk'},
  {k:'直後',r:'ちょくご',m:'immediately following'},
  {k:'直線',r:'ちょくせん',m:'straight line'},
  {k:'直前',r:'ちょくぜん',m:'just before'},
  {k:'直通',r:'ちょくつう',m:'direct communication'},
  {k:'直流',r:'ちょくりゅう',m:'direct current'},
  {k:'貯蔵',r:'ちょぞう',m:'storage, preservation'},
  {k:'直角',r:'ちょっかく',m:'right angle'},
  {k:'直径',r:'ちょっけい',m:'diameter'},
  {k:'散らかす',r:'ちらかす',m:'to scatter around, to leave untidy'},
  {k:'散らかる',r:'ちらかる',m:'to be in disorder, to lie scattered around'},
  {k:'散らす',r:'ちらす',m:'to scatter, to disperse, to distribute'},
  {k:'塵紙',r:'ちりがみ',m:'tissue paper, toilet paper'},
  {k:'散る',r:'ちる',m:'to fall, to scatter (e.g. blossoms)'},
  {k:'追加',r:'ついか',m:'addition, supplement, appendix'},
  {k:'ついで',r:'ついで',m:'opportunity, occasion'},
  {k:'通貨',r:'つうか',m:'currency'},
  {k:'通勤',r:'つうきん',m:'commuting to work'},
  {k:'通ずる',r:'つうずる',m:'to lead to, to reach'},
  {k:'通知',r:'つうち',m:'notice, notification'},
  {k:'通帳',r:'つうちょう',m:'passbook'},
  {k:'通訳',r:'つうやく',m:'interpretation'},
  {k:'通用',r:'つうよう',m:'popular use, circulation'},
  {k:'通路',r:'つうろ',m:'passage, pathway'},
  {k:'付合う',r:'つきあう',m:'to associate with, to keep company with, to get on with'},
  {k:'突き当たり',r:'つきあたり',m:'end (e.g. of street)'},
  {k:'突き当たる',r:'つきあたる',m:'to run into, to collide with'},
  {k:'月日',r:'つきひ',m:'time, years, days'},
  {k:'点く',r:'つく',m:'to catch fire, (electricity) comes on'},
  {k:'突く',r:'つく',m:'to thrust, to strike, to poke'},
  {k:'次ぐ',r:'つぐ',m:'to rank next to, to come after'},
  {k:'作る/造る',r:'つくる',m:'to make, to create'},
  {k:'着ける',r:'つける',m:'to attach, to join, to add, to append'},
  {k:'点ける',r:'つける',m:'to turn on, to switch on, to light up'},
  {k:'浸ける',r:'つける',m:'to dip in, to soak'},
  {k:'伝わる',r:'つたわる',m:'to be handed down, to be introduced, to be transmitted'},
  {k:'突っ込む',r:'つっこむ',m:'to plunge into, to go into deeply'},
  {k:'務める',r:'つとめる',m:'to serve, to fill a post, to serve under, to work (for)'},
  {k:'努める',r:'つとめる',m:'to serve, to fill a post, to serve under, to work (for)'},
  {k:'綱',r:'つな',m:'rope'},
  {k:'繋がり',r:'つながり',m:'connection, link, relationship'},
  {k:'繋がる',r:'つながる',m:'to be tied together, to be connected to, to be related to'},
  {k:'繋げる',r:'つなげる',m:'to connect'},
  {k:'粒',r:'つぶ',m:'grain'},
  {k:'潰す',r:'つぶす',m:'to smash, to waste'},
  {k:'潰れる',r:'つぶれる',m:'to be smashed, to go bankrupt'},
  {k:'つまずく',r:'つまずく',m:'to stumble, to trip'},
  {k:'詰まる',r:'つまる',m:'to be blocked, to be packed'},
  {k:'積む',r:'つむ',m:'to pile up, to stack'},
  {k:'爪',r:'つめ',m:'fingernail or toenail, claw, talon, hoof'},
  {k:'艶',r:'つや',m:'gloss, glaze'},
  {k:'強気',r:'つよき',m:'firm, strong'},
  {k:'釣り合う',r:'つりあう',m:'to balance, to be in harmony, to suit'},
  {k:'吊る',r:'つる',m:'to hang'},
  {k:'吊す',r:'つるす',m:'to hang'},
  {k:'出合い',r:'であい',m:'an encounter'},
  {k:'手洗い',r:'てあらい',m:'restroom, lavatory, hand-washing'},
  {k:'定員',r:'ていいん',m:'fixed number of regular personnel, capacity (of boat, etc.)'},
  {k:'定価',r:'ていか',m:'established price'},
  {k:'低下',r:'ていか',m:'fall, decline, lowering, deterioration'},
  {k:'定期券',r:'ていきけん',m:'commuter pass, season ticket'},
  {k:'定休日',r:'ていきゅうび',m:'regular holiday'},
  {k:'停止',r:'ていし',m:'suspension, interruption, stoppage, ban'},
  {k:'停車',r:'ていしゃ',m:'stopping (e.g. train)'},
  {k:'停電',r:'ていでん',m:'failure of electricity'},
  {k:'出入り',r:'でいり',m:'in and out, coming and going, free association, income and expenditure, debits and credit'},
  {k:'出入口',r:'でいりぐち',m:'exit and entrance'},
  {k:'手入れ',r:'ていれ',m:'repairs, maintenance'},
  {k:'テーマ',r:'テーマ',m:'theme, project, topic'},
  {k:'出掛ける',r:'でかける',m:'to depart, to set out, to start, to be going out'},
  {k:'出来上がり',r:'できあがり',m:'be finished, ready, made for, cut out'},
  {k:'出来上がる',r:'できあがる',m:'to be finished, to be ready, by definition, to be very drunk'},
  {k:'的確',r:'てきかく',m:'precise, accurate'},
  {k:'適確',r:'てきかく',m:'precise, accurate'},
  {k:'手首',r:'てくび',m:'wrist'},
  {k:'凸凹',r:'でこぼこ',m:'unevenness, roughness, ruggedness'},
  {k:'手頃',r:'てごろ',m:'moderate, handy'},
  {k:'でたらめ',r:'でたらめ',m:'irresponsible utterance, nonsense, nonsensical, random'},
  {k:'手帳',r:'てちょう',m:'notebook'},
  {k:'鉄橋',r:'てっきょう',m:'railway bridge, iron bridge'},
  {k:'手続き',r:'てつづき',m:'procedure, (legal) process, formalities'},
  {k:'鉄砲',r:'てっぽう',m:'gun'},
  {k:'テニスコート',r:'テニスコート',m:'tennis court'},
  {k:'手拭い',r:'てぬぐい',m:'(hand) towel'},
  {k:'手前',r:'てまえ',m:'before, this side, we, you'},
  {k:'出迎え',r:'でむかえ',m:'meeting, reception'},
  {k:'出迎える',r:'でむかえる',m:'to meet, to greet'},
  {k:'照らす',r:'てらす',m:'to shine on, to illuminate'},
  {k:'照る',r:'てる',m:'to shine'},
  {k:'展開',r:'てんかい',m:'develop, expansion (opposite of compression)'},
  {k:'伝記',r:'でんき',m:'biography, life story'},
  {k:'電球',r:'でんきゅう',m:'light bulb'},
  {k:'点数',r:'てんすう',m:'marks, points, score, runs'},
  {k:'伝染',r:'でんせん',m:'contagion'},
  {k:'電池',r:'でんち',m:'battery'},
  {k:'点々',r:'てんてん',m:'here and there, little by little'},
  {k:'転々',r:'てんてん',m:'wandering, ever changing'},
  {k:'電柱',r:'でんちゅう',m:'telephone pole, telegraph pole, light pole'},
  {k:'天皇',r:'てんのう',m:'Emperor of Japan'},
  {k:'電波',r:'でんぱ',m:'electro-magnetic wave'},
  {k:'テンポ',r:'テンポ',m:'tempo'},
  {k:'電流',r:'でんりゅう',m:'electric current'},
  {k:'電力',r:'でんりょく',m:'electric power'},
  {k:'問い合わせ',r:'といあわせ',m:'enquiry, ENQ'},
  {k:'銅',r:'どう',m:'copper'},
  {k:'統一',r:'とういつ',m:'unity, consolidation, uniformity'},
  {k:'同格',r:'どうかく',m:'the same rank, equality, apposition'},
  {k:'峠',r:'とうげ',m:'ridge, (mountain) pass, difficult part'},
  {k:'統計',r:'とうけい',m:'scattering, a scatter, dispersion'},
  {k:'動作',r:'どうさ',m:'action, movements, motions, bearing, behavior, manners'},
  {k:'東西',r:'とうざい',m:'East and West, whole country'},
  {k:'当日',r:'とうじつ',m:'appointed day, very day'},
  {k:'投書',r:'とうしょ',m:'letter to the editor, letter from a reader, contribution'},
  {k:'登場',r:'とうじょう',m:'entry (on stage)'},
  {k:'どうせ',r:'どうせ',m:'anyhow, in any case, at any rate'},
  {k:'どうぞよろしく',r:'どうぞよろしく',m:'pleased to meet you'},
  {k:'灯台',r:'とうだい',m:'lighthouse'},
  {k:'盗難',r:'とうなん',m:'theft, robbery'},
  {k:'当番',r:'とうばん',m:'being on duty'},
  {k:'等分',r:'とうぶん',m:'division into equal parts'},
  {k:'透明',r:'とうめい',m:'transparency, cleanness'},
  {k:'灯油',r:'とうゆ',m:'lamp oil, kerosene'},
  {k:'東洋',r:'とうよう',m:'Orient'},
  {k:'童話',r:'どうわ',m:'fairy tale'},
  {k:'通り掛かる',r:'とおりかかる',m:'to happen to pass by'},
  {k:'溶かす',r:'とかす',m:'to melt, to dissolve'},
  {k:'尖る',r:'とがる',m:'to taper to a point, to become sharp, to be sour, to look displeased'},
  {k:'どきどき',r:'どきどき',m:'throb, beat (fast)'},
  {k:'溶く',r:'とく',m:'to dissolve (paint)'},
  {k:'退く',r:'どく',m:'to retreat, to recede, to withdraw'},
  {k:'特殊',r:'とくしゅ',m:'special, unique'},
  {k:'特色',r:'とくしょく',m:'characteristic, feature'},
  {k:'特長',r:'とくちょう',m:'forte, merit'},
  {k:'特定',r:'とくてい',m:'specific, special, particular'},
  {k:'特売',r:'とくばい',m:'special sale'},
  {k:'溶け込む',r:'とけこむ',m:'to melt into'},
  {k:'溶ける',r:'とける',m:'to melt, to thaw, to fuse, to dissolve'},
  {k:'退ける',r:'どける',m:'to remove, to take away, to dislodge, to put something out of the way'},
  {k:'床の間',r:'とこのま',m:'alcove'},
  {k:'床屋',r:'とこや',m:'barber'},
  {k:'所々',r:'ところどころ',m:'here and there, some parts (of something)'},
  {k:'都心',r:'としん',m:'heart (of city)'},
  {k:'戸棚',r:'とだな',m:'cupboard, locker, closet, wardrobe'},
  {k:'とっくに',r:'とっくに',m:'long ago, already, a long time ago'},
  {k:'どっと',r:'どっと',m:'suddenly'},
  {k:'整う',r:'ととのう',m:'to be prepared, to be in order, to be put in order, to be arranged'},
  {k:'留まる',r:'とどまる',m:'to be fixed, to abide, to stay (in the one place)'},
  {k:'どなる',r:'どなる',m:'to shout, to yell'},
  {k:'飛び込む',r:'とびこむ',m:'to jump in, to leap in, to plunge into, to dive'},
  {k:'跳ぶ',r:'とぶ',m:'to jump, to fly, to leap'},
  {k:'泊める',r:'とめる',m:'to give shelter to, to lodge'},
  {k:'ともかく',r:'ともかく',m:'anyhow, anyway, somehow or other, generally speaking, in any case'},
  {k:'捕える',r:'とらえる',m:'to seize, to grasp, to capture, to arrest'},
  {k:'取り入れる',r:'とりいれる',m:'to harvest, to take in, to adopt'},
  {k:'取り消す',r:'とりけす',m:'to cancel'},
  {k:'取り出す',r:'とりだす',m:'to take out, to produce, to pick out'},
  {k:'採る',r:'とる',m:'to adopt (measure, proposal), to pick (fruit)'},
  {k:'捕る',r:'とる',m:'to take, to catch (fish), to capture'},
  {k:'トレーニング',r:'トレーニング',m:'training'},
  {k:'丼',r:'どんぶり',m:'porcelain bowl, bowl of rice with food on top'},
  {k:'内科',r:'ないか',m:'internist clinic, internal medicine'},
  {k:'内線',r:'ないせん',m:'phone extension, indoor wiring, inner line'},
  {k:'ナイロン',r:'ナイロン',m:'nylon'},
  {k:'治す',r:'なおす',m:'to cure, to heal, to fix, to correct, to repair'},
  {k:'永い',r:'ながい',m:'long, lengthy'},
  {k:'仲直り',r:'なかなおり',m:'reconciliation, make peace with'},
  {k:'長引く',r:'ながびく',m:'to be prolonged, to drag on'},
  {k:'中身',r:'なかみ',m:'contents, interior, substance, filling, (sword) blade'},
  {k:'中味',r:'なかみ',m:'contents, interior, substance, filling, (sword) blade'},
  {k:'中指',r:'なかゆび',m:'middle finger'},
  {k:'仲良し',r:'なかよし',m:'intimate friend, bosom buddy, chum'},
  {k:'慰める',r:'なぐさめる',m:'to comfort, to console'},
  {k:'亡くす',r:'なくす',m:'to lose someone, wife, child, etc'},
  {k:'なぐる',r:'なぐる',m:'to strike, to hit'},
  {k:'為す',r:'なす',m:'to accomplish, to do'},
  {k:'謎謎',r:'なぞなぞ',m:'riddle, puzzle, enigma'},
  {k:'懐かしい',r:'なつかしい',m:'dear, desired, missed'},
  {k:'撫でる',r:'なでる',m:'to brush gently, to stroke'},
  {k:'斜め',r:'ななめ',m:'obliqueness'},
  {k:'なにしろ',r:'なにしろ',m:'at any rate, anyhow, anyway, in any case'},
  {k:'何々',r:'なになに',m:'such and such, What?'},
  {k:'何分',r:'なにぶん',m:'what minute?, how many minutes?'},
  {k:'生意気',r:'なまいき',m:'impertinent, saucy, cheeky, conceit, audacious, brazen'},
  {k:'並木',r:'なみき',m:'roadside tree, row of trees'},
  {k:'倣う',r:'ならう',m:'to imitate, to follow, to emulate'},
  {k:'鳴らす',r:'ならす',m:'to ring, to sound, to chime, to beat, to snort (nose)'},
  {k:'生る',r:'なる',m:'to bear fruit'},
  {k:'馴れる',r:'なれる',m:'to become domesticated, to become tame'},
  {k:'南極',r:'なんきょく',m:'south pole, Antarctic'},
  {k:'なんとなく',r:'なんとなく',m:'somehow or other, for some reason or another'},
  {k:'なんとも',r:'なんとも',m:'nothing (with neg. verb), quite, not a bit'},
  {k:'ナンバー',r:'ナンバー',m:'number'},
  {k:'南米',r:'なんべい',m:'South America'},
  {k:'南北',r:'なんぼく',m:'south and north'},
  {k:'煮える',r:'にえる',m:'to boil, to cook, to be cooked'},
  {k:'匂う',r:'におう',m:'to be fragrant, to smell, to stink'},
  {k:'逃がす',r:'にがす',m:'to let loose, to set free, to let escape'},
  {k:'憎い',r:'にくい',m:'hateful, abominable, poor-looking, detestable'},
  {k:'憎む',r:'にくむ',m:'to hate, to detest'},
  {k:'憎らしい',r:'にくらしい',m:'odious, hateful'},
  {k:'にこにこ',r:'にこにこ',m:'smile'},
  {k:'濁る',r:'にごる',m:'to become muddy, to get impure'},
  {k:'虹',r:'にじ',m:'rainbow'},
  {k:'日時',r:'にちじ',m:'date and time'},
  {k:'日用品',r:'にちようひん',m:'daily necessities'},
  {k:'日課',r:'にっか',m:'daily lesson, daily work, daily routine'},
  {k:'日程',r:'にってい',m:'agenda'},
  {k:'鈍い',r:'にぶい',m:'dull (e.g. a knife), thickheaded, slow (opposite of fast), stupid'},
  {k:'入社',r:'にゅうしゃ',m:'entry to a company'},
  {k:'女房',r:'にょうぼう',m:'wife'},
  {k:'睨む',r:'にらむ',m:'to glare at, to scowl at, to keep an eye on'},
  {k:'煮る',r:'にる',m:'to boil, to cook'},
  {k:'縫う',r:'ぬう',m:'to sew'},
  {k:'濡らす',r:'ぬらす',m:'to wet, to soak, to dip'},
  {k:'ねじ',r:'ねじ',m:'(a) screw'},
  {k:'捩る',r:'ねじる',m:'to twist'},
  {k:'ネックレス',r:'ネックレス',m:'necklace'},
  {k:'熱する',r:'ねっする',m:'to heat'},
  {k:'寝間着',r:'ねまき',m:'sleep-wear, nightclothes, pajamas, nightgown, nightdress'},
  {k:'狙い',r:'ねらい',m:'aim'},
  {k:'狙う',r:'ねらう',m:'to aim at'},
  {k:'年度',r:'ねんど',m:'year, fiscal year, school year, term'},
  {k:'農産物',r:'のうさんぶつ',m:'agricultural produce'},
  {k:'農村',r:'のうそん',m:'agricultural community, farm village, rural'},
  {k:'濃度',r:'のうど',m:'concentration, brightness'},
  {k:'農薬',r:'のうやく',m:'agricultural chemicals'},
  {k:'能率',r:'のうりつ',m:'efficiency'},
  {k:'のこぎり',r:'のこぎり',m:'saw'},
  {k:'残らず',r:'のこらず',m:'all, entirely, completely, without exception'},
  {k:'載せる',r:'のせる',m:'to place on (something), to take on board, to give a ride'},
  {k:'覗く',r:'のぞく',m:'to peep in, to look in, to peek in, to stick out'},
  {k:'延ばす',r:'のばす',m:'to lengthen, to stretch, to reach out, to grow (beard)'},
  {k:'延びる',r:'のびる',m:'to be prolonged'},
  {k:'上り',r:'のぼり',m:'up-train (going to Tokyo), ascent'},
  {k:'上る',r:'のぼる',m:'to ascend, to go up, to climb'},
  {k:'糊',r:'のり',m:'paste, starch'},
  {k:'乗換',r:'のりかえ',m:'transfer (trains, buses, etc.)'},
  {k:'載る',r:'のる',m:'to appear (in print), to be recorded'},
  {k:'鈍い',r:'のろい',m:'dull (e.g. a knife), thickheaded, slow (opposite of fast), stupid'},
  {k:'のろのろ',r:'のろのろ',m:'slowly, sluggishly'},
  {k:'呑気',r:'のんき',m:'carefree, optimistic, careless, reckless, heedless'},
  {k:'灰色',r:'はいいろ',m:'grey, gray, ashen'},
  {k:'俳句',r:'はいく',m:'haiku poetry'},
  {k:'拝見',r:'はいけん',m:'seeing, look at'},
  {k:'売店',r:'ばいてん',m:'shop, stand'},
  {k:'バイバイ',r:'バイバイ',m:'bye-bye'},
  {k:'売買',r:'ばいばい',m:'trade, buying and selling'},
  {k:'這う',r:'はう',m:'to creep, to crawl'},
  {k:'生える',r:'はえる',m:'to grow, to spring up, to cut (teeth)'},
  {k:'剥す',r:'はがす',m:'to tear off, to peel off, to rip off'},
  {k:'ばからしい',r:'ばからしい',m:'absurd'},
  {k:'秤',r:'はかり',m:'scales, weighing machine'},
  {k:'量る',r:'はかる',m:'to measure, to weigh, to survey'},
  {k:'測る',r:'はかる',m:'to measure, to weigh, to survey'},
  {k:'吐き気',r:'はきけ',m:'nausea, sickness in the stomach'},
  {k:'はきはき',r:'はきはき',m:'lucidly'},
  {k:'掃く',r:'はく',m:'to sweep, to brush, to gather up'},
  {k:'歯車',r:'はぐるま',m:'gear, cog-wheel'},
  {k:'バケツ',r:'バケツ',m:'bucket, pail'},
  {k:'挟まる',r:'はさまる',m:'to get between, to be caught in'},
  {k:'挟む',r:'はさむ',m:'to interpose, to hold between, to insert'},
  {k:'箸',r:'はし',m:'chopsticks'},
  {k:'梯子',r:'はしご',m:'ladder, stairs'},
  {k:'始めに',r:'はじめに',m:'to begin with, first of all'},
  {k:'初めに',r:'はじめに',m:'to begin with, first of all'},
  {k:'はじめまして',r:'はじめまして',m:'how do you do?, I am glad to meet you'},
  {k:'斜',r:'はす',m:'diagonal'},
  {k:'外れる',r:'はずれる',m:'to be disconnected, to get out of place, to be off, to be out (e.g. of gear)'},
  {k:'パターン',r:'パターン',m:'pattern'},
  {k:'肌着',r:'はだぎ',m:'underwear'},
  {k:'果して',r:'はたして',m:'as was expected, really'},
  {k:'鉢',r:'はち',m:'a bowl, a pot'},
  {k:'発揮',r:'はっき',m:'exhibition, demonstration, utilization, display'},
  {k:'バック',r:'バック',m:'back'},
  {k:'発射',r:'はっしゃ',m:'firing, shooting, discharge, catapult'},
  {k:'発想',r:'はっそう',m:'expression (music), conceptualization'},
  {k:'発電',r:'はつでん',m:'generation (e.g. power)'},
  {k:'発売',r:'はつばい',m:'sale'},
  {k:'派手',r:'はで',m:'showy, loud, gay, flashy, gaudy'},
  {k:'話合い',r:'はなしあい',m:'discussion, conference'},
  {k:'話し掛ける',r:'はなしかける',m:'to accost a person, to talk (to someone)'},
  {k:'話中',r:'はなしちゅう',m:'while talking, the line is busy'},
  {k:'甚だしい',r:'はなはだしい',m:'extreme, excessive, terrible'},
  {k:'花火',r:'はなび',m:'fireworks'},
  {k:'花嫁',r:'はなよめ',m:'bride'},
  {k:'放れる',r:'はなれる',m:'to leave, to get free, to cut oneself off'},
  {k:'羽根',r:'はね',m:'shuttlecock'},
  {k:'ばね',r:'ばね',m:'spring (e.g. coil, leaf)'},
  {k:'跳ねる',r:'はねる',m:'to jump, to leap'},
  {k:'破片',r:'はへん',m:'fragment, splinter, broken piece'},
  {k:'歯磨き',r:'はみがき',m:'dentifrice, toothpaste'},
  {k:'はめる',r:'はめる',m:'to get in, to insert, to put on, to make love'},
  {k:'早口',r:'はやくち',m:'fast-talking'},
  {k:'流行る',r:'はやる',m:'to flourish, to thrive, to be popular, to come into fashion'},
  {k:'払い込む',r:'はらいこむ',m:'to deposit, to pay in'},
  {k:'払い戻す',r:'はらいもどす',m:'to repay, to pay back'},
  {k:'バランス',r:'バランス',m:'balance'},
  {k:'針金',r:'はりがね',m:'wire'},
  {k:'張り切る',r:'はりきる',m:'to be in high spirits, to be full of vigor'},
  {k:'反映',r:'はんえい',m:'reflection, influence'},
  {k:'半径',r:'はんけい',m:'radius'},
  {k:'判子',r:'はんこ',m:'seal (used for signature)'},
  {k:'万歳',r:'ばんざい',m:'hurrah, cheers'},
  {k:'判事',r:'はんじ',m:'judge, judiciary'},
  {k:'反省',r:'はんせい',m:'reflection, reconsideration, introspection, meditation, contemplation'},
  {k:'番地',r:'ばんち',m:'house number, address'},
  {k:'パンツ',r:'パンツ',m:'underpants'},
  {k:'バンド',r:'バンド',m:'band'},
  {k:'半島',r:'はんとう',m:'peninsula'},
  {k:'ハンドル',r:'ハンドル',m:'handle, steering wheel'},
  {k:'日当たり',r:'ひあたり',m:'exposure to the sun, sunny place'},
  {k:'日帰り',r:'ひがえり',m:'day trip'},
  {k:'比較的',r:'ひかくてき',m:'comparatively, relatively'},
  {k:'日陰',r:'ひかげ',m:'shadow'},
  {k:'ぴかぴか',r:'ぴかぴか',m:'glitter, sparkle'},
  {k:'引受る',r:'ひきうける',m:'to undertake, to take up, to take over'},
  {k:'引返す',r:'ひきかえす',m:'to repeat, to send back, to bring back'},
  {k:'引算',r:'ひきざん',m:'subtraction'},
  {k:'引出す',r:'ひきだす',m:'to pull out, to take out, to draw out, to withdraw'},
  {k:'引き止める',r:'ひきとめる',m:'to detain, to check, to restrain'},
  {k:'卑怯',r:'ひきょう',m:'cowardice, meanness, unfairness'},
  {k:'引分け',r:'ひきわけ',m:'a draw (in competition), tie game'},
  {k:'髭',r:'ひげ',m:'mustache, beard, whiskers'},
  {k:'陽射',r:'ひざし',m:'sunlight, rays of the sun'},
  {k:'肘',r:'ひじ',m:'elbow'},
  {k:'ピストル',r:'ピストル',m:'pistol'},
  {k:'ビタミン',r:'ビタミン',m:'vitamin'},
  {k:'ぴたり',r:'ぴたり',m:'tightly, exactly'},
  {k:'引っ掛かる',r:'ひっかかる',m:'to be caught in, to be stuck in, to be cheated'},
  {k:'筆記',r:'ひっき',m:'(taking) notes, copying'},
  {k:'引っ繰り返す',r:'ひっくりかえす',m:'to turn over, to overturn, to knock over, to upset, to turn inside out'},
  {k:'引っ繰り返る',r:'ひっくりかえる',m:'to be overturned, to be upset, to topple over, to be reversed'},
  {k:'引越し',r:'ひっこし',m:'moving (dwelling etc.), changing residence'},
  {k:'引っ込む',r:'ひっこむ',m:'to draw back, to sink, to cave in'},
  {k:'筆者',r:'ひっしゃ',m:'writer, author'},
  {k:'必需品',r:'ひつじゅひん',m:'necessities, necessary article, requisite, essential'},
  {k:'人差指',r:'ひとさしゆび',m:'index finger'},
  {k:'一通り',r:'ひととおり',m:'ordinary, usual, in general, briefly'},
  {k:'人通り',r:'ひとどおり',m:'pedestrian traffic'},
  {k:'ひとまず',r:'ひとまず',m:'for the present, once, in outline'},
  {k:'瞳',r:'ひとみ',m:'pupil (of eye)'},
  {k:'一休み',r:'ひとやすみ',m:'a rest'},
  {k:'独り言',r:'ひとりごと',m:'a soliloquy, a monologue, speaking to oneself'},
  {k:'ひとりでに',r:'ひとりでに',m:'by itself, automatically, naturally'},
  {k:'ビニール',r:'ビニール',m:'vinyl'},
  {k:'皮肉',r:'ひにく',m:'cynicism, sarcasm'},
  {k:'日日',r:'ひにち',m:'every day, daily, day after day'},
  {k:'捻る',r:'ひねる',m:'to turn (a switch) on or off, to twist, to puzzle over'},
  {k:'日の入り',r:'ひのいり',m:'sunset'},
  {k:'日の出',r:'ひので',m:'sunrise'},
  {k:'響き',r:'ひびき',m:'echo, sound, reverberation, noise'},
  {k:'響く',r:'ひびく',m:'to resound'},
  {k:'皮膚',r:'ひふ',m:'skin'},
  {k:'冷やす',r:'ひやす',m:'to cool, to refrigerate'},
  {k:'ひゃっかじてん',r:'ひゃっかじてん',m:'encyclopedia'},
  {k:'美容',r:'びよう',m:'beauty of figure or form'},
  {k:'表紙',r:'ひょうし',m:'front cover, binding'},
  {k:'標識',r:'ひょうしき',m:'sign, mark'},
  {k:'標準',r:'ひょうじゅん',m:'standard, level'},
  {k:'標本',r:'ひょうほん',m:'example, specimen'},
  {k:'評論',r:'ひょうろん',m:'criticism, critique'},
  {k:'平仮名',r:'ひらがな',m:'hiragana, 47 syllables, the cursive syllabary'},
  {k:'ビルディング',r:'ビルディング',m:'building'},
  {k:'昼寝',r:'ひるね',m:'nap (at home), siesta'},
  {k:'広げる',r:'ひろげる',m:'to spread, to extend, to expand, to enlarge'},
  {k:'広さ',r:'ひろさ',m:'extent'},
  {k:'広場',r:'ひろば',m:'plaza'},
  {k:'広々',r:'ひろびろ',m:'extensive, spacious'},
  {k:'広める',r:'ひろめる',m:'to broaden, to propagate'},
  {k:'ピンク',r:'ピンク',m:'pink'},
  {k:'便箋',r:'びんせん',m:'writing paper, stationery'},
  {k:'瓶詰',r:'びんづめ',m:'bottling, bottled'},
  {k:'ファスナー',r:'ファスナー',m:'fastener, zipper'},
  {k:'風船',r:'ふうせん',m:'balloon'},
  {k:'不運',r:'ふうん',m:'unlucky, misfortune, bad luck, fate'},
  {k:'殖える',r:'ふえる',m:'to increase, to multiply'},
  {k:'深まる',r:'ふかまる',m:'to deepen, to heighten, to intensify'},
  {k:'不規則',r:'ふきそく',m:'irregularity, unsteadiness, disorderly'},
  {k:'普及',r:'ふきゅう',m:'diffusion, spread'},
  {k:'付近',r:'ふきん',m:'neighborhood, vicinity, environs'},
  {k:'拭く',r:'ふく',m:'to wipe, to dry'},
  {k:'副詞',r:'ふくし',m:'adverb'},
  {k:'複写',r:'ふくしゃ',m:'copy, duplicate'},
  {k:'複数',r:'ふくすう',m:'plural, multiple'},
  {k:'含める',r:'ふくめる',m:'to include, to instruct, to make one understand'},
  {k:'膨らます',r:'ふくらます',m:'to swell, to expand, to inflate, to bulge'},
  {k:'膨らむ',r:'ふくらむ',m:'to expand, to swell (out), to get big, to become inflated'},
  {k:'不潔',r:'ふけつ',m:'unclean, dirty, filthy, impure'},
  {k:'更ける',r:'ふける',m:'to get late, to advance, to wear on'},
  {k:'符号',r:'ふごう',m:'sign, mark, symbol'},
  {k:'夫妻',r:'ふさい',m:'man and wife, married couple'},
  {k:'塞がる',r:'ふさがる',m:'to be plugged up, to be shut up'},
  {k:'塞ぐ',r:'ふさぐ',m:'to stop up, to close up, to block (up)'},
  {k:'ふざける',r:'ふざける',m:'to romp, to gambol, to frolic, to joke'},
  {k:'無沙汰',r:'ぶさた',m:'neglecting to stay in contact'},
  {k:'武士',r:'ぶし',m:'warrior, samurai'},
  {k:'部首',r:'ぶしゅ',m:'radical (of a kanji character)'},
  {k:'襖',r:'ふすま',m:'sliding screen'},
  {k:'附属',r:'ふぞく',m:'attached, belonging, affiliated'},
  {k:'蓋',r:'ふた',m:'cover, lid, cap'},
  {k:'不通',r:'ふつう',m:'suspension, interruption, stoppage, tie-up, cessation'},
  {k:'ぶつかる',r:'ぶつかる',m:'to strike, to collide with'},
  {k:'ぶつける',r:'ぶつける',m:'to knock, to run into, to nail on, to strike hard, to hit and attack'},
  {k:'物騒',r:'ぶっそう',m:'dangerous, disturbed, insecure'},
  {k:'ぶつぶつ',r:'ぶつぶつ',m:'grumbling, complaining in a small voice'},
  {k:'船便',r:'ふなびん',m:'surface mail (ship)'},
  {k:'部品',r:'ぶひん',m:'parts, accessories'},
  {k:'吹雪',r:'ふぶき',m:'snow storm'},
  {k:'父母',r:'ふぼ',m:'father and mother, parents'},
  {k:'踏切',r:'ふみきり',m:'railway crossing, level crossing, starting line, scratch, crossover'},
  {k:'麓',r:'ふもと',m:'the foot, the bottom, the base (of a mountain)'},
  {k:'増やす',r:'ふやす',m:'to increase, to add to, to augment'},
  {k:'殖やす',r:'ふやす',m:'to increase, to add to, to augment'},
  {k:'フライパン',r:'フライパン',m:'fry pan, frying pan'},
  {k:'ブラウス',r:'ブラウス',m:'blouse'},
  {k:'ぶらさげる',r:'ぶらさげる',m:'to hang, to suspend, to dangle, to swing'},
  {k:'ブラシ',r:'ブラシ',m:'brush'},
  {k:'プラスチック',r:'プラスチック',m:'plastic'},
  {k:'プラットホーム',r:'プラットホーム',m:'platform'},
  {k:'フリー',r:'フリー',m:'free'},
  {k:'振り仮名',r:'ふりがな',m:'pronunciation key'},
  {k:'プリント',r:'プリント',m:'print, handout'},
  {k:'振舞う',r:'ふるまう',m:'to behave, to conduct oneself, to entertain (vt)'},
  {k:'ブローチ',r:'ブローチ',m:'brooch'},
  {k:'プログラム',r:'プログラム',m:'program'},
  {k:'風呂敷',r:'ふろしき',m:'wrapping cloth, cloth wrapper'},
  {k:'ふわふわ',r:'ふわふわ',m:'light, soft'},
  {k:'噴火',r:'ふんか',m:'eruption'},
  {k:'分解',r:'ぶんかい',m:'analysis, disassembly'},
  {k:'文芸',r:'ぶんげい',m:'literature, art and literature, belles-lettres'},
  {k:'文献',r:'ぶんけん',m:'literature, books (reference)'},
  {k:'噴水',r:'ふんすい',m:'water fountain'},
  {k:'分数',r:'ぶんすう',m:'fraction (in math)'},
  {k:'文体',r:'ぶんたい',m:'literary style'},
  {k:'分布',r:'ぶんぷ',m:'distribution'},
  {k:'文房具',r:'ぶんぼうぐ',m:'stationery'},
  {k:'文脈',r:'ぶんみゃく',m:'context'},
  {k:'分量',r:'ぶんりょう',m:'amount, quantity'},
  {k:'分類',r:'ぶんるい',m:'classification'},
  {k:'閉会',r:'へいかい',m:'closure'},
  {k:'平気',r:'へいき',m:'coolness, calmness, composure, unconcern'},
  {k:'並行',r:'へいこう',m:'(going) side by side, concurrent, abreast, at the same time'},
  {k:'平日',r:'へいじつ',m:'weekday, ordinary days'},
  {k:'兵隊',r:'へいたい',m:'soldier, sailor'},
  {k:'平凡',r:'へいぼん',m:'common, commonplace, ordinary, mediocre'},
  {k:'平野',r:'へいや',m:'plain, open field'},
  {k:'凹む',r:'へこむ',m:'to be dented, to be indented, to yield to, to give, to sink, to collapse, to cave in, to be snubbed'},
  {k:'へそ',r:'へそ',m:'navel, belly-button'},
  {k:'隔てる',r:'へだてる',m:'to be shut out'},
  {k:'別荘',r:'べっそう',m:'holiday house, villa'},
  {k:'別々',r:'べつべつ',m:'separately, individually'},
  {k:'ベテラン',r:'ベテラン',m:'veteran'},
  {k:'ヘリコプター',r:'ヘリコプター',m:'helicopter'},
  {k:'へる',r:'へる',m:'to decrease (in size or number), to diminish, to abate'},
  {k:'ぺん',r:'ぺん',m:'pen'},
  {k:'編集',r:'へんしゅう',m:'editing, compilation, editorial (e.g. committee)'},
  {k:'便所',r:'べんじょ',m:'toilet, lavatory, rest room, latrine, comfort station'},
  {k:'ペンチ',r:'ペンチ',m:'pliers'},
  {k:'望遠鏡',r:'ぼうえんきょう',m:'telescope'},
  {k:'方角',r:'ほうがく',m:'direction, way, compass point'},
  {k:'箒',r:'ほうき',m:'broom'},
  {k:'方言',r:'ほうげん',m:'dialect'},
  {k:'坊さん',r:'ぼうさん',m:'Buddhist priest, monk'},
  {k:'防止',r:'ぼうし',m:'prevention, check'},
  {k:'方針',r:'ほうしん',m:'objective, plan, policy'},
  {k:'包装',r:'ほうそう',m:'packing, wrapping'},
  {k:'法則',r:'ほうそく',m:'law, rule'},
  {k:'包帯',r:'ほうたい',m:'bandage, dressing'},
  {k:'膨大',r:'ぼうだい',m:'huge, bulky, enormous, extensive, swelling, expansion'},
  {k:'庖丁',r:'ほうちょう',m:'kitchen knife, carving knife'},
  {k:'方程式',r:'ほうていしき',m:'equation'},
  {k:'防犯',r:'ぼうはん',m:'prevention of crime'},
  {k:'方面',r:'ほうめん',m:'direction, district, field (e.g., of study)'},
  {k:'坊や',r:'ぼうや',m:'boy'},
  {k:'放る',r:'ほうる',m:'to let go'},
  {k:'ボーナス',r:'ボーナス',m:'bonus'},
  {k:'朗らか',r:'ほがらか',m:'brightness, cheerfulness, melodious'},
  {k:'牧場',r:'ぼくじょう',m:'farm (livestock), pasture land, meadow, grazing land'},
  {k:'牧畜',r:'ぼくちく',m:'stock-farming'},
  {k:'保健',r:'ほけん',m:'health preservation, hygiene, sanitation'},
  {k:'募集',r:'ぼしゅう',m:'recruiting, taking applications'},
  {k:'干す',r:'ほす',m:'to air, to dry, to desiccate, to drain (off), to drink up'},
  {k:'ポスター',r:'ポスター',m:'poster'},
  {k:'北極',r:'ほっきょく',m:'North Pole'},
  {k:'坊っちゃん',r:'ぼっちゃん',m:'son (of others)'},
  {k:'ほどく',r:'ほどく',m:'to unfasten'},
  {k:'堀',r:'ほり',m:'moat, canal'},
  {k:'掘る',r:'ほる',m:'to dig, to excavate'},
  {k:'彫る',r:'ほる',m:'to carve, to engrave, to sculpture, to chisel'},
  {k:'ぼろ',r:'ぼろ',m:'rag, scrap, tattered clothes, fault (esp. in a pretense)'},
  {k:'盆',r:'ぼん',m:'Lantern Festival, Festival of the Dead, tray'},
  {k:'盆地',r:'ぼんち',m:'basin (e.g. between mountains)'},
  {k:'本部',r:'ほんぶ',m:'headquarters'},
  {k:'本来',r:'ほんらい',m:'essentially, naturally, by nature'},
  {k:'まあまあ',r:'まあまあ',m:'so-so'},
  {k:'枚数',r:'まいすう',m:'the number of flat things'},
  {k:'毎度',r:'まいど',m:'each time, common service-sector greeting'},
  {k:'マイナス',r:'マイナス',m:'minus'},
  {k:'巻く',r:'まく',m:'to wind, to coil, to roll'},
  {k:'蒔く',r:'まく',m:'to sow (seeds)'},
  {k:'撒く',r:'まく',m:'to scatter, to sprinkle, to sow'},
  {k:'枕',r:'まくら',m:'pillow, bolster'},
  {k:'曲げる',r:'まげる',m:'to bend, to crook, to lean'},
  {k:'まごまご',r:'まごまご',m:'confused'},
  {k:'摩擦',r:'まさつ',m:'friction, rubbing, rubdown, chafe'},
  {k:'混ざる',r:'まざる',m:'to be mixed, to be blended with, to associate with, to mingle with, to join'},
  {k:'交ざる',r:'まざる',m:'to be mixed, to be blended with, to associate with, to mingle with, to join'},
  {k:'混じる',r:'まじる',m:'to be mixed, to be blended with, to associate with'},
  {k:'交じる',r:'まじる',m:'to be mixed, to be blended with, to associate with'},
  {k:'マスク',r:'マスク',m:'mask'},
  {k:'混ぜる',r:'まぜる',m:'to mix, to stir'},
  {k:'交ぜる',r:'まぜる',m:'to be mixed, to be blended with'},
  {k:'またぐ',r:'またぐ',m:'to straddle'},
  {k:'又は',r:'または',m:'or, otherwise'},
  {k:'待合室',r:'まちあいしつ',m:'waiting room'},
  {k:'待ち合わせる',r:'まちあわせる',m:'to rendezvous, to meet at a prearranged place and time'},
  {k:'街角',r:'まちかど',m:'street corner'},
  {k:'真っ暗',r:'まっくら',m:'total darkness, shortsightedness, pitch dark'},
  {k:'真っ黒',r:'まっくろ',m:'pitch black'},
  {k:'真っ青',r:'まっさお',m:'deep blue, ghastly pale'},
  {k:'真っ先',r:'まっさき',m:'the head, the foremost, beginning'},
  {k:'真っ白',r:'まっしろ',m:'pure white'},
  {k:'祭る',r:'まつる',m:'to deify, to enshrine'},
  {k:'窓口',r:'まどぐち',m:'ticket window'},
  {k:'纏まる',r:'まとまる',m:'to be collected, to be settled, to be in order'},
  {k:'纏める',r:'まとめる',m:'to put in order, to collect, to bring to a conclusion'},
  {k:'真似る',r:'まねる',m:'to mimic, to imitate'},
  {k:'まぶしい',r:'まぶしい',m:'dazzling, radiant'},
  {k:'まぶた',r:'まぶた',m:'eyelids'},
  {k:'マフラー',r:'マフラー',m:'muffler, scarf'},
  {k:'間も無く',r:'まもなく',m:'soon, before long, in a short time'},
  {k:'マラソン',r:'マラソン',m:'marathon'},
  {k:'円い',r:'まるい',m:'round, circular, spherical'},
  {k:'稀',r:'まれ',m:'rare, seldom'},
  {k:'回り道',r:'まわりみち',m:'detour'},
  {k:'満員',r:'まんいん',m:'full house, no vacancy, sold out'},
  {k:'マンション',r:'マンション',m:'large apartment, apartment house'},
  {k:'満点',r:'まんてん',m:'perfect score'},
  {k:'見送る',r:'みおくる',m:'to see off, to farewell, to escort, to let pass'},
  {k:'見下ろす',r:'みおろす',m:'to overlook, to command a view of, to look down on something'},
  {k:'見掛け',r:'みかけ',m:'outward appearance'},
  {k:'三日月',r:'みかづき',m:'new moon, crescent moon'},
  {k:'岬',r:'みさき',m:'cape (on coast)'},
  {k:'みじめ',r:'みじめ',m:'sad, pitiful, wretched'},
  {k:'ミシン',r:'ミシン',m:'sewing machine'},
  {k:'店屋',r:'みせや',m:'store, shop'},
  {k:'見出し',r:'みだし',m:'heading, caption, subtitle, index'},
  {k:'道順',r:'みちじゅん',m:'itinerary, route'},
  {k:'見付かる',r:'みつかる',m:'to be found, to be discovered'},
  {k:'見付ける',r:'みつける',m:'to be familiar, to discover, to detect'},
  {k:'みっともない',r:'みっともない',m:'shameful, indecent'},
  {k:'見直す',r:'みなおす',m:'to look again, to get a better opinion of'},
  {k:'見慣れる',r:'みなれる',m:'to become used to seeing, to be familiar with'},
  {k:'醜い',r:'みにくい',m:'ugly'},
  {k:'実る',r:'みのる',m:'to bear fruit, to ripen'},
  {k:'身分',r:'みぶん',m:'social position, social status'},
  {k:'見本',r:'みほん',m:'sample'},
  {k:'見舞う',r:'みまう',m:'to ask after (health), to visit'},
  {k:'未満',r:'みまん',m:'less than, insufficient'},
  {k:'名字',r:'みょうじ',m:'surname, family name'},
  {k:'ミリ',r:'ミリ',m:'milli-, 10^-3'},
  {k:'診る',r:'みる',m:'to examine (medical)'},
  {k:'民間',r:'みんかん',m:'private, civilian, civil, popular, folk, unofficial'},
  {k:'民謡',r:'みんよう',m:'folk song, popular song'},
  {k:'向う',r:'むかう',m:'to face, to go towards'},
  {k:'剥く',r:'むく',m:'to peel, to skin, to pare, to hull'},
  {k:'無限',r:'むげん',m:'infinite'},
  {k:'無地',r:'むじ',m:'plain, unfigured'},
  {k:'蒸し暑い',r:'むしあつい',m:'humid, sultry'},
  {k:'矛盾',r:'むじゅん',m:'contradiction, inconsistency'},
  {k:'蒸す',r:'むす',m:'to steam, to poultice, to be sultry'},
  {k:'無数',r:'むすう',m:'countless number, infinite number'},
  {k:'紫',r:'むらさき',m:'purple color, violet'},
  {k:'群れ',r:'むれ',m:'group, crowd, flock, herd'},
  {k:'姪',r:'めい',m:'niece'},
  {k:'名作',r:'めいさく',m:'masterpiece'},
  {k:'名刺',r:'めいし',m:'business card'},
  {k:'名詞',r:'めいし',m:'noun'},
  {k:'名所',r:'めいしょ',m:'famous place'},
  {k:'命ずる',r:'めいずる',m:'to command, to appoint'},
  {k:'迷信',r:'めいしん',m:'superstition'},
  {k:'名物',r:'めいぶつ',m:'famous product, special product, speciality'},
  {k:'銘々',r:'めいめい',m:'each, individual'},
  {k:'目上',r:'めうえ',m:'superior(s), senior'},
  {k:'メーター',r:'メーター',m:'meter (clock)'},
  {k:'恵まれる',r:'めぐまれる',m:'to be blessed with, to be rich in'},
  {k:'巡る',r:'めぐる',m:'to go around'},
  {k:'目指す',r:'めざす',m:'to aim at, to have an eye on'},
  {k:'目覚し',r:'めざまし',m:'alarm-clock'},
  {k:'目下',r:'めした',m:'at present, now'},
  {k:'目印',r:'めじるし',m:'mark, sign, landmark'},
  {k:'目立つ',r:'めだつ',m:'to be conspicuous, to stand out'},
  {k:'めちゃくちゃ',r:'めちゃくちゃ',m:'absurd, unreasonable, excessive, messed up, spoiled, wreaked'},
  {k:'めっきり',r:'めっきり',m:'remarkably'},
  {k:'めでたい',r:'めでたい',m:'happy, simple soul, propitious, joyous'},
  {k:'メニュー',r:'メニュー',m:'menu'},
  {k:'めまい',r:'めまい',m:'dizziness, giddiness'},
  {k:'目安',r:'めやす',m:'criterion, aim'},
  {k:'免税',r:'めんぜい',m:'tax exemption, duty exemption'},
  {k:'面積',r:'めんせき',m:'area'},
  {k:'面接',r:'めんせつ',m:'interview'},
  {k:'面倒臭い',r:'めんどうくさい',m:'bother to do, tiresome'},
  {k:'儲かる',r:'もうかる',m:'to be profitable, to yield a profit'},
  {k:'儲ける',r:'もうける',m:'to get, to earn, to gain, to have (bear, beget) a child'},
  {k:'申し訳ない',r:'もうしわけない',m:'inexcusable'},
  {k:'モーター',r:'モーター',m:'motor'},
  {k:'木材',r:'もくざい',m:'lumber, timber, wood'},
  {k:'目次',r:'もくじ',m:'table of contents'},
  {k:'潜る',r:'もぐる',m:'to dive (into or under water), to go underground'},
  {k:'もしかしたら',r:'もしかしたら',m:'perhaps, maybe, by some chance'},
  {k:'もしかすると',r:'もしかすると',m:'perhaps, maybe, by some chance'},
  {k:'もたれる',r:'もたれる',m:'to lean against, to lean on, to recline on, to lie heavy (on the stomach)'},
  {k:'モダン',r:'モダン',m:'modern'},
  {k:'餅',r:'もち',m:'sticky rice cake'},
  {k:'もったいない',r:'もったいない',m:'too good, more than one deserves, wasteful, sacrilegious, unworthy of'},
  {k:'モデル',r:'モデル',m:'model'},
  {k:'元々',r:'もともと',m:'originally, by nature, from the start'},
  {k:'物置',r:'ものおき',m:'storage room'},
  {k:'物語る',r:'ものがたる',m:'to tell, to indicate'},
  {k:'物差し',r:'ものさし',m:'ruler, measure'},
  {k:'物凄い',r:'ものすごい',m:'earth-shattering, staggering, to a very great extent'},
  {k:'モノレール',r:'モノレール',m:'monorail'},
  {k:'紅葉',r:'もみじ',m:'Japanese maple'},
  {k:'揉む',r:'もむ',m:'to rub, to crumple (up), to wrinkle'},
  {k:'燃やす',r:'もやす',m:'to burn'},
  {k:'催し',r:'もよおし',m:'event, festivities, function'},
  {k:'盛る',r:'もる',m:'to serve (food, etc.), to fill up, to prescribe'},
  {k:'問答',r:'もんどう',m:'questions and answers, dialogue'},
  {k:'やかましい',r:'やかましい',m:'noisy, strict, fussy'},
  {k:'夜間',r:'やかん',m:'at night, nighttime'},
  {k:'薬缶',r:'やかん',m:'kettle'},
  {k:'役者',r:'やくしゃ',m:'actor, actress'},
  {k:'役所',r:'やくしょ',m:'government office, public office'},
  {k:'訳す',r:'やくす',m:'to translate'},
  {k:'役人',r:'やくにん',m:'government official'},
  {k:'薬品',r:'やくひん',m:'medicine(s), chemical(s)'},
  {k:'役目',r:'やくめ',m:'duty, business'},
  {k:'火傷',r:'やけど',m:'burn, scald'},
  {k:'夜行',r:'やこう',m:'walking around at night, night train, night travel'},
  {k:'矢印',r:'やじるし',m:'directing arrow'},
  {k:'やたらに',r:'やたらに',m:'randomly, recklessly, blindly'},
  {k:'薬局',r:'やっきょく',m:'pharmacy, drugstore'},
  {k:'やっつける',r:'やっつける',m:'to attack (an enemy), to beat, to do away with, to finish off'},
  {k:'家主',r:'やぬし',m:'landlord'},
  {k:'やっぱり',r:'やっぱり',m:'also, as I thought, still, in spite of, absolutely, of course'},
  {k:'破く',r:'やぶく',m:'to tear, to rip'},
  {k:'破れる',r:'やぶれる',m:'to get torn, to wear out'},
  {k:'やむをえない',r:'やむをえない',m:'cannot be helped, unavoidable'},
  {k:'軟らかい',r:'やわらかい',m:'soft, tender, limp'},
  {k:'遊園地',r:'ゆうえんち',m:'amusement park'},
  {k:'夕刊',r:'ゆうかん',m:'evening paper'},
  {k:'友好',r:'ゆうこう',m:'friendship'},
  {k:'郵送',r:'ゆうそう',m:'mailing'},
  {k:'夕立',r:'ゆうだち',m:'(sudden) evening shower (rain)'},
  {k:'夕日',r:'ゆうひ',m:'(in) the evening sun, setting sun'},
  {k:'悠々',r:'ゆうゆう',m:'quiet, calm, leisurely'},
  {k:'有料',r:'ゆうりょう',m:'admission-paid, toll'},
  {k:'浴衣',r:'ゆかた',m:'bathrobe, informal summer kimono, yukata'},
  {k:'湯気',r:'ゆげ',m:'steam, vapor'},
  {k:'輸血',r:'ゆけつ',m:'blood transfusion'},
  {k:'輸送',r:'ゆそう',m:'transport, transportation'},
  {k:'油断',r:'ゆだん',m:'negligence, unpreparedness'},
  {k:'ゆでる',r:'ゆでる',m:'to boil'},
  {k:'湯飲み',r:'ゆのみ',m:'teacup'},
  {k:'緩い',r:'ゆるい',m:'loose, lenient, slow'},
  {k:'溶岩',r:'ようがん',m:'lava'},
  {k:'容器',r:'ようき',m:'container, vessel'},
  {k:'用語',r:'ようご',m:'term, terminology'},
  {k:'要旨',r:'ようし',m:'gist, essentials, summary, fundamentals'},
  {k:'幼児',r:'ようじ',m:'infant, baby, child'},
  {k:'容積',r:'ようせき',m:'capacity, volume'},
  {k:'幼稚',r:'ようち',m:'infancy, childish, infantile'},
  {k:'幼稚園',r:'ようちえん',m:'kindergarten'},
  {k:'用途',r:'ようと',m:'use, usefulness'},
  {k:'洋品店',r:'ようひんてん',m:'shop which handles Western-style apparel and accessories'},
  {k:'養分',r:'ようぶん',m:'nourishment, nutrient'},
  {k:'羊毛',r:'ようもう',m:'wool'},
  {k:'漸く',r:'ようやく',m:'gradually, finally, hardly'},
  {k:'要領',r:'ようりょう',m:'point, gist, essentials, outline'},
  {k:'欲張り',r:'よくばり',m:'avarice, covetousness, greed'},
  {k:'余計',r:'よけい',m:'too much, unnecessary, abundance, surplus, excess, superfluity'},
  {k:'よこす',r:'よこす',m:'to send, to forward, to hand over (e.g. money)'},
  {k:'汚す',r:'よごす',m:'to disgrace, to dishonor, to pollute, to contaminate, to soil, to make dirty, to stain'},
  {k:'寄せる',r:'よせる',m:'to collect, to gather, to add, to put aside'},
  {k:'余所',r:'よそ',m:'another place, somewhere else, strange parts'},
  {k:'四つ角',r:'よつかど',m:'four corners, crossroads'},
  {k:'酔っ払い',r:'よっぱらい',m:'drunkard'},
  {k:'予備',r:'よび',m:'preparation, preliminaries, reserve, spare'},
  {k:'呼び掛ける',r:'よびかける',m:'to call out to, to accost, to address (crowd), to appeal'},
  {k:'呼び出す',r:'よびだす',m:'to summon, to call (e.g. phone)'},
  {k:'蘇る',r:'よみがえる',m:'to be resurrected, to be revived, to be resuscitated, to be rehabilitated'},
  {k:'因る',r:'よる',m:'to come from'},
  {k:'慶び',r:'よろこび',m:'a joy, a delight, rapture, pleasure, gratification, rejoicing, congratulations, felicitations'},
  {k:'慶ぶ',r:'よろこぶ',m:'to be pleased'},
  {k:'来日',r:'らいにち',m:'arrival in Japan, coming to Japan, visit to Japan'},
  {k:'落第',r:'らくだい',m:'failure, dropping out of a class'},
  {k:'ラッシュアワー',r:'ラッシュアワー',m:'rush hour'},
  {k:'欄',r:'らん',m:'column of text (e.g. as in a newspaper)'},
  {k:'ランチ',r:'ランチ',m:'launch, lunch'},
  {k:'ランニング',r:'ランニング',m:'running, tank top'},
  {k:'乱暴',r:'らんぼう',m:'rude, violent, rough, lawless, unreasonable, reckless'},
  {k:'理科',r:'りか',m:'science'},
  {k:'利害',r:'りがい',m:'advantages and disadvantages, interest'},
  {k:'リズム',r:'リズム',m:'rhythm'},
  {k:'リットル',r:'リットル',m:'liter'},
  {k:'リボン',r:'リボン',m:'ribbon'},
  {k:'略す',r:'りゃくす',m:'to abbreviate'},
  {k:'流域',r:'りゅういき',m:'(river) basin'},
  {k:'寮',r:'りょう',m:'hostel, dormitory'},
  {k:'両側',r:'りょうがわ',m:'both sides'},
  {k:'漁師',r:'りょうし',m:'fisherman'},
  {k:'領事',r:'りょうじ',m:'consul'},
  {k:'領収',r:'りょうしゅう',m:'receipt, voucher'},
  {k:'臨時',r:'りんじ',m:'temporary, special, extraordinary'},
  {k:'留守番',r:'るすばん',m:'care-taking, caretaker, house-watching'},
  {k:'例外',r:'れいがい',m:'exception'},
  {k:'零点',r:'れいてん',m:'zero, no marks'},
  {k:'冷凍',r:'れいとう',m:'freezing, cold storage, refrigeration'},
  {k:'レインコート',r:'レインコート',m:'raincoat'},
  {k:'レクリェーション',r:'レクリェーション',m:'recreation'},
  {k:'レジャー',r:'レジャー',m:'leisure'},
  {k:'列島',r:'れっとう',m:'chain of islands'},
  {k:'レベル',r:'レベル',m:'level'},
  {k:'リポート',r:'リポート',m:'report, paper'},
  {k:'煉瓦',r:'れんが',m:'brick'},
  {k:'連合',r:'れんごう',m:'union, alliance'},
  {k:'レンズ',r:'レンズ',m:'lens'},
  {k:'蝋燭',r:'ろうそく',m:'candle'},
  {k:'ローマ字',r:'ローマじ',m:'romanization, Roman letters'},
  {k:'録音',r:'ろくおん',m:'(audio) recording'},
  {k:'ロッカー',r:'ロッカー',m:'locker'},
  {k:'ロビー',r:'ロビー',m:'lobby'},
  {k:'論ずる',r:'ろんずる',m:'to argue, to discuss, to debate'},
  {k:'和英',r:'わえい',m:'Japanese-English'},
  {k:'分かる',r:'わかる',m:'to be understood'},
  {k:'分かれる',r:'わかれる',m:'to branch off, to diverge from, to fork, to split, to dispense, to scatter, to divide into'},
  {k:'若々しい',r:'わかわかしい',m:'youthful, young'},
  {k:'湧く',r:'わく',m:'to boil, to grow hot, to get excited, to gush forth'},
  {k:'詫びる',r:'わびる',m:'to apologize'},
  {k:'和服',r:'わふく',m:'Japanese clothes'},
  {k:'わりあいに',r:'わりあいに',m:'comparatively'},
  {k:'割算',r:'わりざん',m:'division (math)'},
  {k:'割と',r:'わりと',m:'relatively, comparatively'},
  {k:'割引',r:'わりびき',m:'discount, reduction, rebate'},
  {k:'椀',r:'わん',m:'Japanese soup bowl, wooden bowl'},
  {k:'碗',r:'わん',m:'bowl'},
  {k:'ワンピース',r:'ワンピース',m:'one-piece dress'},
];
